### PR TITLE
Ensure that scripts without the notion of upper/lower case can create du identifiers

### LINKED ISSUE #4697: Discriminated union doesn't work with non English type constructor names
Discriminated union doesn't work with non alphabet string (e.g., Korean string 개수).

#### Repro steps

Provide the steps required to reproduce the problem

1. Type in the following
type some-type =
    | 개수

#### Expected behavior

Should compile. Korean language doesn't have uppercase/lowercase distinction so it should just work with any Korean string.

#### Actual behavior

Error code FS0053 (Discriminated union cases and exception labels must be uppercase identifiers) emitted on VS 2017

#### Known workarounds

Prefixing the string with uppercase English letter works. e.g. U개수

#### Related information 

Provide any related information 

* Windows 10
* 4.1
* VS 2017 Community

### LINKED ISSUE #9186: The requirement that DU Identifiers start with an Upper case character does not account for languages without a notion of case.
Looking through the FSharpQA testcode, I came across this test case

````
  // DU
  type ख़तरxनाक = 
               | Uअलगाववादी     // There's no uppercase/lowercase in Hindi, so I'm adding a latin char
               | Aमिलती of ख़तरनाक
               | X
````

I think we should lose the requirement that DU identifiers must be upper case.  As well as the warning about Upper case identifiers in patterns.  There are plenty of languages that do not have the notion of uppercase and lowercase, building language requirements and conventions based around our notions of the alphabet is probably something we should avoid.

In the test above, the hindi code needed to have an upper case latin character prefixed in order to successfully compile.

````
  <data name="UpperCaseIdentifierInPattern" xml:space="preserve">
    <value>Uppercase variable identifiers should not generally be used in patterns, and may indicate a missing open declaration or a misspelt pattern name.</value>
  </data>
  <data name="NotUpperCaseConstructor" xml:space="preserve">
    <value>Discriminated union cases and exception labels must be uppercase identifiers</value>
  </data>
````

### PR DESCRIPTION
**Pull request by KevinRansom**
Fixes #9186
Fixes #4697

Bicamaral scripts such as that Latin or Cyrillic alphabets have the notion of upper and lower case characters.  The F# language used this to place a requirement on DU discriminators and PatternMatch identifiers be upper case only.

This restriction is difficult for developers using a unicameral script, such as hindi, placing the requirement that they use an uppercase Latin character for example to satisfy the compiler.

This PR addresses this issue by relaxing the requirement to require an upper case character begin a DU Discriminator, or PatternMatch identifier.  The new rule becomes, where the initial character has an upper case variant, the upper case variant must be used.  If the initial character does not have an upper case variant, then it will satisfy the DU/PatternMatch id requirement.

This relaxation has some impact even on developers using a unicameral script.  For example:

this used to produce a compiler error:
````F#
let (|B1|``+B2``|) (x:int) = if x = 0 then OneA else ``+B2``
````
+B2 is a quoted identifier that had a non uppercase character.  In the new scheme it is valid because + has no identifiable upper case and so satisfies the requirement.

//cc: abelbraaksma, @cartermp, @hmnjeon

### CODE REVIEW

**Comment by abelbraaksma** [comment]
You forgot the at-sign for my name, but I found it anyway ;)

May I suggest that we disallow characters that are not allowed identifier characters? That would be more in line with how it currently works, and still allow unicameral (and I always thought that term was used for parliamentary systems) scripts to create DU cases and partial match patterns.

That'd really only apply to quoted identifiers anyway, as otherwise there's no way to include such characters.

File: src/absil/illib.fs [hunk 1]
```diff
@@ -503,9 +503,20 @@ module String =
...
-        s.Length >= 1 && Char.IsUpper s.[0] && not (Char.IsLower s.[0])
-        
+    // Scripts that distinguish between upper and lower case (bicameral) DU Discriminators and Active Pattern identifiers are required to start with an upper case character.
+    // For valid identifiers where the case of the identifier can not be determined because there is no upper and lower case we will allow DU Discriminators and upper case characters 
+    // to be used.  This means that developers using unicameral scripts such as hindi, are not required to prefix these identifiers with an Upper case latin character. 
+    // '_' is a special case'  It is a valid identifier char, it disables definite assignment checks.  And it is neither upper or lower cased.
+    let isUpperCaseCharacter c =
+        // if IsUpper and IsLower return the same value, then we can't tell if it's upper or lower case, so it is a case insensensitive language
+        // thusly the char must be good.
+        if Char.IsUpper c = Char.IsLower c then (c <> '_')
```
Comment (auduchinok) [inline src/absil/illib.fs:513]: Could it be something like
```fsharp
if Char.IsUpper c = Char.IsLower c then Char.IsLetter c
```
instead? Allowing arbitrary symbols like `+` seems to be a too big breaking change to me.

File: tests/fsharpqa/Source/Conformance/PatternMatching/Named/E_ActivePatterns01.fs [hunk 2]
```diff
@@ -1,17 +1,11 @@
...
-//<Expects id="FS0624" status="error" span="(16,9)">The '\|' character is not permitted in active pattern case identifiers</Expects>
+//<Expects id="FS0623" status="error" span="(8,7)">Active pattern case identifiers must begin with an uppercase letter</Expects>
+//<Expects id="FS0623" status="error" span="(8,16)">Active pattern case identifiers must begin with an uppercase letter</Expects>
+//<Expects id="FS0624" status="error" span="(9,7)">The '\|' character is not permitted in active pattern case identifiers</Expects>
+//<Expects id="FS0624" status="error" span="(10,9)">The '\|' character is not permitted in active pattern case identifiers</Expects>
 
 let (|positive|negative|) n = if n < 0 then positive else negative
-let (|`` A``|) (x:int) = x
-let (|B1|``+B2``|) (x:int) = if x = 0 then OneA else ``+B2``
-let (|`` C``|_|) (x:int) = if x = 0 then Some(x) else None
```
Comment (auduchinok) [inline tests/fsharpqa/Source/Conformance/PatternMatching/Named/E_ActivePatterns01.fs:14]: Would it be better to preserve these cases? So, if produced errors change one day it'll be reflected here.

File: src/absil/illib.fs (hunk 1 above)
Comment (KevinRansom) [reply src/absil/illib.fs:513]: @auduchinok, I quite like that, however, Identifiers must begin with letters already and so it's only quoted identifiers that would really be impacted and we still need to cope with '_'.
But yes I will make that adjustment we have the restriction today, and keeping it as is, has a lot of value.

File: tests/fsharpqa/Source/Conformance/PatternMatching/Named/E_ActivePatterns01.fs (hunk 2 above)
Comment (KevinRansom) [reply tests/fsharpqa/Source/Conformance/PatternMatching/Named/E_ActivePatterns01.fs:14]: @auduchinok once we do the is letter thingy they will be errors again :-).

**Comment by KevinRansom** [comment]
@abelbraaksma , it was 2:30 in the morning, I'm sorry I forgot the @.  I wish I had thought of the @IsLetter gizmo @auduchinok found a really nice solution.

**Comment by KevinRansom** [comment]
@abelbraaksma , if you look up Bicameral on-line they seem to prefer to show the split parliament definition.  To get a definition about languages I searched bicameral script.  Unicameral is the logical term, but it doesn't really roll of the tongue either.

**Comment by abelbraaksma** [comment]
>  it was 2:30 in the morning,

In normal times, you ought to be in a bar drinking a beer at such times! 

> I wish I had thought of the IsLetter gizmo @auduchinok found a really nice solution. 

I vaguely remember there's an `isIdChar` function somewhere. Not sure if it does the same as `IsLetter`. 

Btw, iirc, these BCL methods are not Astral plane aware. Meaning that the fix won't hold for valid code points above the BMP. Not sure that's a problem though.

**Comment by KevinRansom** [comment]
@abelbraaksma I will take a look for isIdChar, we have to validate id's somewhere :-)

File: tests/fsharpqa/Source/Conformance/PatternMatching/Named/E_ActivePatterns01.fs (hunk 2 above)
Comment (auduchinok) [reply tests/fsharpqa/Source/Conformance/PatternMatching/Named/E_ActivePatterns01.fs:14]: Yes, it'll be OK. :)

What I wanted to say was if there is a test for some particular behavior that is being changed it could be good to keep the test just in case it might be changed again (even accidentally, e.g. if fixing an issue produced by the initial change). It's probably just a good thing to record how the particular behavior is changed anyway.

Comment (KevinRansom) [reply tests/fsharpqa/Source/Conformance/PatternMatching/Named/E_ActivePatterns01.fs:14]: Thanks @auduchinok mate, I understood mate, was messin' with ya :-)

**Comment by KevinRansom** [comment]
@abelbraaksma , @auduchinok updated, please take a look.

Thanks

File: src/absil/illib.fs [hunk 3]
```diff
@@ -503,9 +503,21 @@ module String =
...
         s.ToUpperInvariant()
 
-    let isUpper (s: string) = 
-        s.Length >= 1 && Char.IsUpper s.[0] && not (Char.IsLower s.[0])
-        
+    // Scripts that distinguish between upper and lower case (bicameral) DU Discriminators and Active Pattern identifiers are required to start with an upper case character.
+    // For valid identifiers where the case of the identifier can not be determined because there is no upper and lower case we will allow DU Discriminators and upper case characters 
+    // to be used.  This means that developers using unicameral scripts such as hindi, are not required to prefix these identifiers with an Upper case latin character. 
+    //
+//@@@@@@    // note trim quotes for quoted identifiers and prefixed _ used to disable definite assignment before checking identifier
```
Comment (KevinRansom) [inline src/absil/illib.fs:510]: Oh bugger need to lose these.

File: src/absil/illib.fs [hunk 4]
```diff
@@ -503,9 +503,19 @@ module String =
...
+    // Scripts that distinguish between upper and lower case (bicameral) DU Discriminators and Active Pattern identifiers are required to start with an upper case character.
+    // For valid identifiers where the case of the identifier can not be determined because there is no upper and lower case we will allow DU Discriminators and upper case characters 
+    // to be used.  This means that developers using unicameral scripts such as hindi, are not required to prefix these identifiers with an Upper case latin character. 
+    //
+    let isLeadingIdentifierCharacterUpperCase (s:string) =
+        let isUpperCaseCharacter c =
+            // if IsUpper and IsLower return the same value, then we can't tell if it's upper or lower case, so it is a case insensensitive language
+            // thusly the char must be good.
+            if Char.IsUpper c = Char.IsLower c then Char.IsLetter c
+            else Char.IsUpper c
```
Comment (auduchinok) [inline src/absil/illib.fs:515]: Sorry for suggesting another option, just thought it could be better to call `IsUpper` once and, well, first, since it's what we're looking for in the first place. 🙂 
```suggestion
            Char.IsUpper c || Char.IsLetter c && not Char.IsLower c
```

Comment (abelbraaksma) [reply src/absil/illib.fs:515]: Is it defined that `IsUpper` implies `IsLetter` always?

Comment (auduchinok) [reply src/absil/illib.fs:515]:
```csharp
```
https://github.com/dotnet/runtime/blob/87f78fe5424ace6e3de3693d0fda5cd25011cb1d/src/libraries/System.Private.CoreLib/src/System/Char.cs#L272-L278

Comment (KevinRansom) [reply src/absil/illib.fs:515]: @cloudRoutine 
For sure this is easier to describe and reason about:
````
            if Char.IsUpper c = Char.IsLower c then Char.IsLetter c
            else Char.IsUpper c
````
than
````
Char.IsUpper c || Char.IsLetter c && not Char.IsLower c
```` 
Also inlining and hoisting IsUpper, is something I believe the jit should do, although I don't know if it does.  And finally, if for reasons, I can't even fathom an implementation of a script caused IsUpper and IsLower to both return true then we are back where we are now.  But TBH the readability of the current impl wins for me.

Comment (abelbraaksma) [reply src/absil/illib.fs:515]: > And finally, if for reasons, I can't even fathom an implementation of a script caused IsUpper and IsLower to both return true then we are back where we are now. 

@KevinRansom The Unicode standard has characters where both properties are true. However, .NET doesn't follow those rules strictly and returns `false` and `false` for these cases:

image

```f#
> Char.IsUpper(char(0x02B0));;
val it : bool = false

> Char.IsLower(char(0x02B0));;
val it : bool = false

> Array.init 65535 id |> Array.tryFind(fun x -> Char.IsUpper(char x) && Char.IsLower(char x));;
val it : int option = None
```

Comment (abelbraaksma) [reply src/absil/illib.fs:515]: > For sure this is easier to describe and reason about:

You can prevent an extra call to `GetUnicodeCategory` (which is relatively expensive) by changing it to the following, which is still readable:

```f#
let isUpper = Char.IsUpper c
if isUpper = Char.IsLower c then Char.IsLetter c
else isUpper
```

Or, this is arguable more readable and also has max 3 checks for the UnicodeCategory.

```f#
match Char.IsUpper c, Char.IsLower c with
| true, true
| false, false -> Char.IsLetter c
| isUpper, _ -> isUpper
````

Comment (KevinRansom) [reply src/absil/illib.fs:515]: I will make it this:
````
let isUpper = Char.IsUpper c
if isUpper = Char.IsLower c then Char.IsLetter c
else isUpper
````

File: tests/fsharpqa/Source/Globalization/Hindi.fs [hunk 5]
```diff
@@ -14,8 +14,8 @@ module पिछले =
   
   // DU
   type ख़तरxनाक = 
-               | Uअलगाववादी     // There's no uppercase/lowercase in Hindi, so I'm adding a latin char
-               | Aमिलती of ख़तरनाक
+               | अलगाववादी     // There's no uppercase/lowercase in Hindi, so I'm adding a latin char
```
Comment (cartermp) [inline tests/fsharpqa/Source/Globalization/Hindi.fs:17]: Comment is out of date

Comment (KevinRansom) [reply tests/fsharpqa/Source/Globalization/Hindi.fs:17]: Nice .... that's the problem with comments ... they bit-rot so fast.

Comment (KevinRansom) [reply tests/fsharpqa/Source/Globalization/Hindi.fs]: fixed

Comment (smoothdeveloper) [reply tests/fsharpqa/Source/Globalization/Hindi.fs]: > they bit-rot so fast.

Is MSFT working on NLP versus code analysis already to help with this?

Comment (cartermp) [reply tests/fsharpqa/Source/Globalization/Hindi.fs]: Nope

Comment (KevinRansom) [reply tests/fsharpqa/Source/Globalization/Hindi.fs]: When I was working on Indigo the rule was no comments.   That still bothers everyone I work with :-)

Comment (cartermp) [reply tests/fsharpqa/Source/Globalization/Hindi.fs]: 'tis a silly rule

File: src/absil/illib.fs [hunk 6]
```diff
@@ -503,9 +503,20 @@ module String =
     let uppercase (s: string) =
         s.ToUpperInvariant()
 
-    let isUpper (s: string) = 
-        s.Length >= 1 && Char.IsUpper s.[0] && not (Char.IsLower s.[0])
-        
+    // Scripts that distinguish between upper and lower case (bicameral) DU Discriminators and Active Pattern identifiers are required to start with an upper case character.
```
Comment (cartermp) [inline src/absil/illib.fs:506]: Nit: `Scripts` - this comment implies that this change is only relevant for F# scripts. It's also relevant to regular .fs files, yes?

Comment (KevinRansom) [reply src/absil/illib.fs:506]: @cartermp , scripts in this case means written form of a language.
