### PR TITLE
Fix #9255 --- regression in `--staticlink`

### LINKED ISSUE #9255: SDK 3.1.300 : regression in `--staticlink`
On updating to VS16.6/SDK3.1.300 `--staticlink:Newtonsoft.Json`  fails with

```
Error in pass4 for type Newtonsoft.Json.IArrayPool`1, error: Error in GetMethodRefAsMethodDefIdx for mref = (".ctor", "System.Runtime.CompilerServices.NullableAttribute"), error: Exception of type 'FSharp.Compiler.AbstractIL.ILBinaryWriter+MethodDefNotFound' was thrown.
```

**Repro steps**

Project file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <OtherFlags>--staticlink:Newtonsoft.Json</OtherFlags>    
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

</Project>
```

Source file
```
open System
open Newtonsoft.Json.Linq

[<EntryPoint>]
let main argv =
    let o = JObject.Parse "{}"
    printfn "%A" o
    0
```

Execute `dotnet build` with SDK Version:   3.1.300

**Expected behavior**

Clean compilation

**Actual behavior**

```
05/21/2020 11:19:02>dotnet build
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
FSC : error FS2014: A problem occurred writing the binary 'C:\Users\steve\Documents\scratch\staticlink\obj\Debug\netcoreapp3.1\staticlink.dll': Error in pass4 for type Newtonsoft.Json.IArrayPool`1, error: Error in GetMethodRefAsMethodDefIdx for mref = (".ctor", "System.Runtime.CompilerServices.NullableAttribute"), error: Exception of type 'FSharp.Compiler.AbstractIL.ILBinaryWriter+MethodDefNotFound' was thrown. [C:\Users\steve\Documents\scratch\staticlink\staticlink.fsproj]

Build FAILED.

FSC : error FS2014: A problem occurred writing the binary 'C:\Users\steve\Documents\scratch\staticlink\obj\Debug\netcoreapp3.1\staticlink.dll': Error in pass4 for type Newtonsoft.Json.IArrayPool`1, error: Error in GetMethodRefAsMethodDefIdx for mref = (".ctor", "System.Runtime.CompilerServices.NullableAttribute"), error: Exception of type 'FSharp.Compiler.AbstractIL.ILBinaryWriter+MethodDefNotFound' was thrown. [C:\Users\steve\Documents\scratch\staticlink\staticlink.fsproj]
    0 Warning(s)
    1 Error(s)
```

**Known workarounds**

Stick with/revert to SDK 3.1.201

**Related information**

Provide any related information (optional):

* Operating system -- Windows 10 Home
* .NET Runtime kind (.NET Core, .NET Framework, Mono) -- reproduces for target frameworks netstandard2.0, netcoreapp2.0 and net45 at least
* Editing Tools (e.g. Visual Studio Version, Visual Studio) -- n/a

### PR DESCRIPTION
**Pull request by KevinRansom**
Okay so ... firstly I'm sorry this was quite hard to pin down and so took a while.

The issue arises because when we import dependent assemblies such as the static link assemblies.  We don't have access to the same set of system references as can be found in ILGlobals are just not wired up to enable this.  Instead we use [PrimaryAssemblyILGlobals ](https://github.com/dotnet/fsharp/blob/main/src/absil/il.fs#L3711).

The issue occures because when we load types from IlGlobals instead of a PrimaryAssemblyReference they use ILAssemblyReferences.  This was of course necessary so type unification could occur.

However, types whose scope is from PrimaryAssemblyILGlobals, don't have this ... by definition.

So the fix was to:
1.   Make a PrimaryAssembly reference take an optional assembly scope ref.
2.   When we do a compare in MethodDefKey to ensure that two types are equal (this happens for method arguments and return types) We check to see if their assembly references match.

So this fixes the embedding thing, but has shown up different issue:
````
c:\Temp\repro>c:\kevinransom\fsharp\artifacts\bin\fsc\Debug\net472\fsc.exe @repro.rsp
Microsoft (R) F# Compiler version 11.0.0.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.
Duplicate in method table is:
 Type index: 30
 Method name: ToString
 Method arity (num generic params): 0

error FS2014: A problem occurred writing the binary 'c:\Temp\repro\obj\Debug\netcoreapp3.1\ConsoleApp1.dll': Error in pass2 for type Newtonsoft.Json.JsonConvert, error: duplicate entry 'ToString' in method table
````
This type has thousands of overloads for too string so perhaps overload our resolution is a bit iffy.  I will invetigate in a seperate PR.

Note:
This is a change in the way that we handle PrimaryAssemblyScopeRefs, there is existing code that uses an assemblyref held elsewhere.

I propose fixing it in this PR, but first I wanted Will and Don to run their eyes over this and see if they hate it, or whether I should move forward with it.

It probably needs a test case too, however, until the ToString() bug is addressed, that may be tricky.

Thanks

Kevin

### CODE REVIEW

File: src/absil/ilwrite.fs [hunk 1]
```diff
@@ -426,28 +426,49 @@ type MethodDefKey(tidx: int, garity: int, nm: string, rty: ILType, argtys: ILTyp
...
-            rty = y.ReturnType && 
-            List.lengthsEqAndForall2 (fun a b -> a = b) argtys y.ArgTypes &&
-            isStatic = y.IsStatic
+        | :? MethodDefKey as y ->
+            // Compare method def keys rearranged slightly to improve debugging experience.
+            let compareILTypes o1 o2 =
+                //
+                let getScopeAssemRef (o:ILType) =
+                    match o with
+                    | ILType.Value v ->
```
Comment (KevinRansom) [inline src/absil/ilwrite.fs:449]: Note:  What to do when both are primary assembly and they have different arefs?. 

I think that's okay, thaey should probably be considered a match .... but I'm not sure ... I'm also not sure how it would arise.

File: src/absil/il.fs [hunk 2]
```diff
@@ -487,7 +487,7 @@ type ILScopeRef =
     | Local
     | Module of ILModuleRef
     | Assembly of ILAssemblyRef
-    | PrimaryAssembly
+    | PrimaryAssembly of ILAssemblyRef option
```
Comment (TIHan) [inline src/absil/il.fs:490]: I need to look at this tomorrow. My gut tells me we shouldn't have to add a field to ILScopeRef.PrimaryAssembly. Is there no way around this?

Comment (TIHan) [reply src/absil/il.fs:490]: @KevinRansom we should take some time and chat about it tomorrow

File: src/absil/ilwrite.fs [hunk 3]
```diff
@@ -439,15 +440,40 @@ type MethodDefKey(tidx: int, garity: int, nm: string, rty: ILType, argtys: ILTyp
...
+                             match v.Scope with
+                             | ILScopeRef.PrimaryAssembly -> Some (ilg.primaryAssemblyRef.QualifiedName)
+                             | ILScopeRef.Assembly aref -> Some (aref.QualifiedName)
+                             | _ -> None
+                         | _ -> None
+
+                     let scope1 = getScopeAssemblyRef o1
+                     let scope2 = getScopeAssemblyRef o2
+                     match scope1, scope2 with
+                     | Some s1, Some s2 ->
```
Comment (TIHan) [inline src/absil/ilwrite.fs:458]: Handling this case doesn't check the types themselves but only their scopes.

Comment (TIHan) [reply src/absil/ilwrite.fs:458]: Before, we were doing structural equality on ILType. But because we want to have equivalency for ILScope.PrimaryAssembly based on what is in `ILGlobals`, we might have to right a custom equality function that goes through the `ILType`. Another possible way to do this were to rescope ILType to replace the ILScopeRef.Primary with a ILScopeRef.Assembly.

**Comment by KevinRansom** [comment]
@tihan, I think this is done.

File: src/absil/il.fs [hunk 4]
```diff
@@ -610,11 +613,31 @@ type ILTypeRef =
...
-         (x.Scope = y.Scope) &&
-         (x.Name = y.Name) &&
-         (x.Enclosing = y.Enclosing)
+        let y = (yobj :?> ILTypeRef)
+        (x.ApproxId = y.ApproxId) &&
+        (x.Scope = y.Scope) &&
+        (x.Name = y.Name) &&
+        (x.Enclosing = y.Enclosing)
+
+    member x.EqualsWithPrimaryScopeRef (primaryScopeRef:ILScopeRef) (yobj:obj) =
```
Comment (TIHan) [inline src/absil/il.fs:622]:
```suggestion
    member x.EqualsWithPrimaryScopeRef (primaryScopeRef:ILScopeRef, y:ILTypeRef) =
```

File: src/absil/il.fs [hunk 5]
```diff
@@ -682,6 +705,10 @@ and [<StructuralEquality; StructuralComparison; StructuredFormatDisplay("{DebugT
     [<DebuggerBrowsable(DebuggerBrowsableState.Never)>]
     member x.DebugText = x.ToString()
 
+    member x.EqualsWithPrimaryScopeRef (primaryScopeRef:ILScopeRef) (yobj:obj) =
```
Comment (TIHan) [inline src/absil/il.fs:708]:
```suggestion
    member x.EqualsWithPrimaryScopeRef (primaryScopeRef:ILScopeRef, y:ILTypeSpec) =
```

File: src/absil/il.fsi [hunk 6]
```diff
@@ -220,6 +222,11 @@ type ILTypeSpec =
     /// The name of the type in the assembly using the '.' notation for nested types.
     member FullName: string
     
+    /// The basic qualified name of the type in the assembly.
+    member internal BasicQualifiedName: string
```
Comment (TIHan) [inline src/absil/il.fsi:226]: I think we don't need to expose this anymore.

**Review by TIHan — APPROVED** [review]
Yes, this looks good. Only a few comments.

I guess it's hard to tell if re-computing and comparing the hash is quicker vs. just comparing the fields directly.

File: src/absil/il.fsi (hunk 6 above)
Comment (KevinRansom) [reply src/absil/il.fsi:226]: ooo good catch
