### PR TITLE
Fix #7582

### LINKED ISSUE #7582: [release/fsharp5] Computation of `dotnetHostPath` is incorrect in `FSharp.DependencyManager.Utilities.fs`.
When FSI and the nuget dependency manager are hosted inside any process that starts with "dotnet", [the computation of `dotnetHostPath`](https://github.com/dotnet/fsharp/blob/e548076c52dc9eec851bae16d36f94941abaf7bc/src/fsharp/FSharp.DependencyManager/FSharp.DependencyManager.Utilities.fs#L124-L135) is incorrect.

E.g., hosting this inside of the `dotnet-try` assembly incorrectly results in `dotnetHostPath` being `C:\path\to\dotnet-try.exe`.

Workaround:
Set the environment variable `DOTNET_HOST_PATH` to "dotnet.exe" ahead of time.

### PR DESCRIPTION
**Pull request by KevinRansom**
The dependency manager code probed for dotnet.exe poorly.  This tightens it up a bit, and Fixes the specific bug: #7582

The updated algorithm looks like:
````
        // How to find dotnet.exe --- woe is me; probing rules make me sad.
        // Algorithm:
        // 1. Look for DOTNET_HOST_PATH environment variable
        //    this is the main user programable override .. provided by user to find a specific dotnet.exe
        // 2. Probe for are we part of an .NetSDK install
        //    In an sdk install we are always installed in:   sdk\3.0.100-rc2-014234\FSharp
        //    dotnet or dotnet.exe will be found in the directory that contains the sdk directory
        // 3. We are loaded in-process to some other application ... Eg. try .net
        //    See if the host is dotnet.exe ... from netcoreapp3.0 on this is fairly unlikely
        // 4. If it's none of the above we are going to have to rely on the path containing the way to find dotnet.exe
````

### CODE REVIEW

File: src/fsharp/FSharp.DependencyManager/FSharp.DependencyManager.Utilities.fs [hunk 1]
```diff
@@ -122,15 +122,38 @@ module Utilities =
...
+
+                if File.Exists(dotnetLocation) then
+                    Some dotnetLocation
                 else
-                    None
+                    let main = Process.GetCurrentProcess().MainModule
+                    if main.ModuleName ="dotnet" then
+                        Some main.FileName
+                    else
+                        None
```
Comment (brettfo) [inline src/fsharp/FSharp.DependencyManager/FSharp.DependencyManager.Utilities.fs]: Shouldn't this be `Some dotnetLocation` to fall back to the path?

Comment (KevinRansom) [reply src/fsharp/FSharp.DependencyManager/FSharp.DependencyManager.Utilities.fs]: dotnetLocation is the full path to dotnet. or dotnet.exe.   dotnetApp is either dotnet. or dotnet.exe depending on OS.

This else codepath looks to see if it has been activated using dotnet.exe or dotnet, but the directory containing the dependency manager dll is not the FSharp directory, Ie, from a global tool or a unit test.  If so then the path to that dotnet.exe can be got from main.FileName.  The remaining case is the "we have no idea, lets just admit it" and so we return None.

Did that make sense?

Comment (brettfo) [reply src/fsharp/FSharp.DependencyManager/FSharp.DependencyManager.Utilities.fs]: No, because in the case where we found this by using scripting from `dotnet-try`, the flow will be this:

```
if set %DOTNET_HOST_PATH% ... false
else
    dotnetLocation =
        assemblyLocation = DependencyManagerLocation = C:\Users\Brett\.dotnet\tools\.store\dotnet-try\1.0.44142.42\dotnet-try\1.0.44142.42\tools\netcoreapp3.0\any\FSharp.DependencyManager.dll
            => C:\Users\Brett\.dotnet\tools\.store\dotnet-try\1.0.44142.42\dotnet-try\1.0.44142.42\tools\netcoreapp3.0\any\..\..\..\dotnet.exe
            => C:\Users\Brett\.dotnet\tools\.store\dotnet-try\1.0.44142.42\dotnet-try\1.0.44142.42\dotnet.exe
    if exist dotnetLocation => false
    else
        main.ModuleName = "dotnet-try"
        => None

Finally, looking down to executeBuild, pathToExe is None so it just fails immediately.
```

Comment (brettfo) [reply src/fsharp/FSharp.DependencyManager/FSharp.DependencyManager.Utilities.fs]: Hence the very last `None` should be `dotnet`/`dotnet.exe` to hope that it's on the path somewhere.

Comment (KevinRansom) [reply src/fsharp/FSharp.DependencyManager/FSharp.DependencyManager.Utilities.fs]: @brettfo, yes, that makes sense, I typed rely on path in the algorithm, and then never dealt with it in code.  good eyes.

File: src/fsharp/FSharp.DependencyManager/FSharp.DependencyManager.Utilities.fs [hunk 2]
```diff
@@ -122,18 +122,42 @@ module Utilities =
...
-                let main = Process.GetCurrentProcess().MainModule
-                if main.ModuleName.StartsWith("dotnet") then
-                    Some main.FileName
+                // Probe for netsdk install
+                let dotnetLocation =
+                    let dotnetApp =
+                        let platform = Environment.OSVersion.Platform
+                        if platform = PlatformID.Unix then "dotnet" else "dotnet.exe"
+                    let assemblyLocation = typeof<DependencyManagerAttribute>.GetTypeInfo().Assembly.Location
+                    Path.Combine(assemblyLocation, "../../..", dotnetApp)
```
Comment (brettfo) [inline src/fsharp/FSharp.DependencyManager/FSharp.DependencyManager.Utilities.fs]: You can remove `dotnetApp` and replace with `dotnet` defined above on line 84.
