### PR TITLE
Bugfix :: Fix 'Type inference problem too complicated' for SRTP with "T:null and T:struct" dummy constraint

### LINKED ISSUE #18288: Regression in overload resolution
After updating to F#9 I'm observing many regressions in overload resolution.
Here I managed to capture one of them, this one keeps failing even using the langversion flag.

**Repro steps**

Try this in fsi
```
type ToSeq =
    static member inline Invoke (source: 'FldT) : seq<'T>  =
        let inline call (mthd: ^M, input1: ^I) = ((^M or ^I) : (static member ToSeq : _*_ -> _) input1, mthd)
        call (Unchecked.defaultof<ToSeq>, source)

    static member inline ToSeq (x: 'Foldable                      , _: ToSeq) = (^Foldable: (static member ToSeq : _ -> _) x)
    static member inline ToSeq (_: 'T when 'T: null and 'T: struct, _: ToSeq) = ()

type Append =    
    static member inline Append (x: 'AltT        , y: 'AltT           , _: obj   ) = (^AltT : (static member Append : _*_ -> _) x, y) : 'AltT
    static member inline Append (_: ^t when ^t: null and ^t: struct, _, _: obj   ) = ()
    static member inline Append (x: Result<_,_>  , y                  , _: Append) = match x, y with Ok _, _ -> x | Error x, Error y -> Error (x + y) | _, _ -> y

    static member inline Invoke (x: 'AltT) (y: 'AltT) : 'AltT =
        let inline call (mthd: ^M, input1: ^I, input2: ^I) = ((^M or ^I) : (static member Append : _*_*_ -> _) input1, input2, mthd)
        call (Unchecked.defaultof<Append>, x, y)

    static member inline Append (x: 'R -> 'AltT  , y                  , _: Append) = fun r -> Append.Invoke (x r) (y r)

type Choice =
    static member inline Choice (x: ref<'RAltT>, _: obj) =
        let t = ToSeq.Invoke x.Value
        use e = t.GetEnumerator ()
        e.MoveNext() |> ignore
        let mutable res = e.Current
        while e.MoveNext() do res <- Append.Invoke res e.Current
        res

    static member inline Choice (x: ref<'FAltT> , _: Choice) = (^FAltT : (static member Choice : _ -> _) x.Value) : 'AltT
    static member inline Choice (_: ref< ^t> when ^t: null and ^t: struct, _: Choice) = ()

    static member inline Invoke (x: 'FAltT) : 'AltT =
        let inline call (mthd: ^M, input1: ^I) = ((^M or ^I) : (static member Choice : _*_ -> _) (ref input1, mthd))
        call (Unchecked.defaultof<Choice>, x)

type WrappedSeqE<'s> = WrappedSeqE of 's seq with static member ToSeq (WrappedSeqE x) = x

let v1 = [Ok 1; Error "a" ]
let v2 = Choice.Invoke (WrappedSeqE v1)
```

**Expected behavior**

```
val v2: Result<int,string> = Ok 1
```

**Actual behavior**

```
error FS0465: Type inference problem too complicated (maximum iteration depth reached). Consider adding further type annotations.

Stopped due to error
```

**Known workarounds**

Make the last two lines a single one: `let v = Choice.Invoke (WrappedSeqE [Ok 1; Error "a" ])`

**Related information**

Provide any related information (optional):

* Operating system: Windows
* .NET Runtime kind (.NET Core, .NET Framework, Mono): net9 / F#9
* Editing Tools (e.g. Visual Studio Version, Visual Studio): VIsual Studio: `Microsoft (R) F# Interactive version 12.9.101.0 for F# 9.0`* Operating system

### PR DESCRIPTION
**Pull request by T-Gro**
Fixes #18288.

The problem occured when inferring types and the solution contained a method defined like `_: 'T when 'T: null and 'T: struct`.
This problem is fixed.

I have also added consistency checks for pairs of typar constraints that are invalid - will wait in the issue comments for @gusty to see if reporting an error for this combination will break an essential trick without providing alternative.

I also realized that combination of `delegate` and `comparison` constraints is invalid as well, but was misusing a wrong error message -> it gets a new error message now.

With all the logic around typarTy and checks for their constraints having the following form:
```fsharp
            isTyparTy g ty
            && (destTyparTy g ty).Constraints
               |> List.exists (function
                   | TyparConstraint...._ -> true
                   | _ -> false)
```
,the code got convoluted with this boilerplate.
I extracted this logic into helper functions and applied them where they made sense:
```fsharp
ty |> IsTyparTyWithConstraint g _.Is....
```

### CODE REVIEW

**Review by psfinaki — APPROVED** [review]

File: src/Compiler/CodeGen/IlxGen.fs [hunk 1]
```diff
@@ -5676,32 +5676,14 @@ and GenGenericParam cenv eenv (tp: Typar) =
...
-            | TyparConstraint.SupportsNull _ -> true
-            | _ -> false)
+        tp |> HasConstraint(fun tc -> tc.IsIsReferenceType || tc.IsSupportsNull) // `null` implies not struct
 
-    let notNullableValueTypeConstraint =
-        tp.Constraints
-        |> List.exists (function
-            | TyparConstraint.IsNonNullableStruct _ -> true
-            | _ -> false)
+    let notNullableValueTypeConstraint = tp |> HasConstraint _.IsIsNonNullableStruct
```
Comment (abonie) [inline src/Compiler/CodeGen/IlxGen.fs:5681]: Isn't this supposed to be `IsNonNullableStruct`?

File: src/Compiler/CodeGen/IlxGen.fs [hunk 2]
```diff
@@ -5714,17 +5696,11 @@ and GenGenericParam cenv eenv (tp: Typar) =
...
-            | _ -> false)
+        tp |> HasConstraint _.IsRequiresDefaultConstructor
 
     let emitUnmanagedInIlOutput =
         cenv.g.langVersion.SupportsFeature(LanguageFeature.UnmanagedConstraintCsharpInterop)
-        && tp.Constraints
-           |> List.exists (function
-               | TyparConstraint.IsUnmanaged _ -> true
-               | _ -> false)
+        && tp |> HasConstraint _.IsIsUnmanaged
```
Comment (abonie) [inline src/Compiler/CodeGen/IlxGen.fs:5703]: `IsUnmanaged`?
```suggestion
        && tp |> HasConstraint _.IsUnmanaged
```

Comment (T-Gro) [reply src/Compiler/CodeGen/IlxGen.fs:5703]: This is autogenerated, I do not have control over it.
(the generated name is "Is" + name of the case)

File: src/Compiler/TypedTree/TypedTreeOps.fs [hunk 3]
```diff
@@ -9150,41 +9150,34 @@ let IsUnionTypeWithNullAsTrueValue (g: TcGlobals) (tycon: Tycon) =
...
+
 // Note, isStructTy does not include type parameters with the ': struct' constraint
 // This predicate is used to detect those type parameters.
-let isNonNullableStructTyparTy g ty = 
-    match tryDestTyparTy g ty with 
-    | ValueSome tp -> 
-        tp.Constraints |> List.exists (function TyparConstraint.IsNonNullableStruct _ -> true | _ -> false)
-    | ValueNone ->
-        false
+let IsNonNullableStructTyparTy g ty = ty |> IsTyparTyWithConstraint g _.IsIsNonNullableStruct
```
Comment (abonie) [inline src/Compiler/TypedTree/TypedTreeOps.fs:9168]: Okay, there is a couple more of this `IsIs-` type of "typo" so I am starting to wonder if it is in fact a typo

Comment (T-Gro) [reply src/Compiler/TypedTree/TypedTreeOps.fs:9168]: It is not a typo, it is just making use of the auto-generated construct.

Comment (abonie) [reply src/Compiler/TypedTree/TypedTreeOps.fs:9168]: What is that auto-generated construct? For my own edification

Comment (brianrourkeboll) [reply src/Compiler/TypedTree/TypedTreeOps.fs:9168]: https://github.com/fsharp/fslang-design/blob/main/FSharp-9.0/FS-1079-union-properties-visible.md
