### PR TITLE
#6928 - Removed SByte and Byte from default case requirement and added check for complete match.

### LINKED ISSUE #6928: Exhaustive pattern matches on numeric values yield compiler warning
I created a function to compute the AES S-Box. This is its code:

``` fsharp
    let sBox k =
        match k with
        | 0uy ->  0x63uy
        | 1uy ->  0x7cuy
        | 2uy ->  0x77uy
        | 3uy ->  0x7buy
       /// It lasts forever...
        | 251uy ->  0x0fuy
        | 252uy ->  0xb0uy
        | 253uy ->  0x54uy
        | 254uy ->  0xbbuy
        | 255uy ->  0x16uy
```

However, the compiler raises an "Incomplete pattern matches on this expression" warning, even though my code handles _all 256 possible cases_ for the `byte` type.

**Repro steps**

_Already covered._

**Expected behavior**

Code compiles successfuly without warnings.

**Actual behavior**

image

**Known workarounds**

Have a redundant wildcard case at the end of `match` statement.

### PR DESCRIPTION
**Pull request by gdziadkiewicz**
Fix #6928

### CODE REVIEW

File: tests/fsharp/Compiler/Warnings/PatternMatchingWarningTests.fs [hunk 1]
```diff
@@ -0,0 +1,536 @@
...
+
+open NUnit.Framework
+open FSharp.Compiler.SourceCodeServices
+
+[<TestFixture>]
+module PatternMatchingWarningTests =
+
+    [<Test>]
+    let ``Complete pattern match on byte should not trigger FS0025 warning`` () =
+        CompilerAssert.CompileExe
```
Comment (cartermp) [inline tests/fsharp/Compiler/Warnings/PatternMatchingWarningTests.fs]: `Pass` would be better here, since we're not really interested in running an executable.

Comment (gdziadkiewicz) [reply tests/fsharp/Compiler/Warnings/PatternMatchingWarningTests.fs]: Changed to Pass.

**Comment by dsyme** [comment]
That was easier to fix than I realized :)

**Comment by cartermp** [comment]
Thanks @gdziadkiewicz!
