### PR TITLE
Fix10880 - ValueTuple can't be cast to System.IComparable<ValueTuple>

### LINKED ISSUE #10880: ValueTuple can't be cast to System.IComparable<ValueTuple>
```fsharp
open System

ValueTuple.Create(0,0) :> IComparable<ValueTuple<int,int>>
```
gives
```
error FS0193: Type constraint mismatch. The type 
    'struct (int * int)'    
is not compatible with type
    'IComparable<struct (int * int)>'
```

In the spec the types are compatible, and in C# this works fine:

```csharp
var x = ValueTuple.Create(0, 0);
var y = (IComparable<ValueTuple<int, int>>) x;
```

F# reference tuples also fail, but this could be a missing feature rather than a casting issue:

```fsharp
(0,0) :> IComparable<int *int> // FS0193...
```

### PR DESCRIPTION
**Pull request by KevinRansom**
This fixes #10880 - ValueTuple can't be cast to System.IComparable<ValueTuple>.

And adds a couple of unit tests.

It doesn't fix reference tuples.  I need to investigate that a bit more.
Reference Tuples do not implement IComparable<Tuple<T, U>>  so I don't think it can ever work.

### CODE REVIEW

File: src/fsharp/infos.fs [hunk 1]
```diff
@@ -106,6 +106,30 @@ type SkipUnrefInterfaces = Yes | No
 /// Collect the set of immediate declared interface types for an F# type, but do not
 /// traverse the type hierarchy to collect further interfaces.
 let rec GetImmediateInterfacesOfType skipUnref g amap m ty =
+
+    let getInterfaces ty (tcref:TyconRef) tinst =
+        match metadataOfTy g ty with
+        #if !NO_EXTENSIONTYPING
```
Comment (dsyme) [inline src/fsharp/infos.fs:112]: column zero for `#if` please

**Review by dsyme — APPROVED** [review]
👍

File: src/fsharp/infos.fs (hunk 1 above)
Comment (KevinRansom) [reply src/fsharp/infos.fs:112]: oh yes ... thanks

**Review by cartermp — APPROVED** [review]
