### PR TITLE
fix `AddBoundValue` to account for arrays

### LINKED ISSUE #12605: `FsiEvaluationSession.AddBoundValue` doesn't support arrays

### PR DESCRIPTION
**Pull request by brettfo**
`FsiEvaluationSession.AddBoundValue` doesn't support arrays, this fixes that.  The fix is simply to first make type refs for the underlying element type and then the array type and to make sure both of those get added to the compiler state.

Fixes #12605.

### CODE REVIEW

File: src/fsharp/fsi/fsi.fs [hunk 1]
```diff
@@ -1361,18 +1372,24 @@ type internal FsiDynamicCompiler
                     ccuinfos
             ccuinfos, ty
 
-        let ilTy = convertReflectionTypeToILType reflectionTy
```
Comment (brettfo) [inline src/fsharp/fsi/fsi.fs:1364]: This part is much clearer if you're using the split view; the next 11 lines were simply placed into a function.

**Review by jonsequitur — APPROVED** [review]

**Review by KevinRansom — APPROVED** [review]
