### PR TITLE
Fix concurrency issue in `ILPreTypeDefImpl`

### LINKED ISSUE #17803: Synchronization bug in `ILPreTypeDefImpl`
Stack trace obtained under multithreaded test run:
```
[xUnit.net 00:00:01.02]     FSharp.Compiler.UnitTests.SpanTests.Script_ReadOnlySpanForInDo [FAIL]
[xUnit.net 00:00:01.02]       System.Exception : Error creating evaluation session: System.AggregateException: One or more errors occurred. (Value cannot be null.)
[xUnit.net 00:00:01.02]        ---> System.ArgumentNullException: Value cannot be null.
[xUnit.net 00:00:01.02]          at System.Threading.Monitor.Enter(Object obj)
[xUnit.net 00:00:01.02]          at FSharp.Compiler.AbstractIL.IL.ILPreTypeDefImpl.FSharp.Compiler.AbstractIL.IL.ILPreTypeDef.GetTypeDef() in E:\repos\fsharp\src\Compiler\AbstractIL\il.fs:line 2927
[xUnit.net 00:00:01.02]          at FSharp.Compiler.Import.entities@729-1.Invoke(Tuple`2 tupledArg) in E:\repos\fsharp\src\Compiler\Checking\import.fs:line 731
[xUnit.net 00:00:01.02]          at FSharp.Compiler.Import.multisetDiscriminateAndMap[Key,Value,a](FSharpFunc`2 nodef, FSharpFunc`2 tipf, FSharpList`1 items) in E:\repos\fsharp\src\Compiler\Checking\import.fs:line 689
[xUnit.net 00:00:01.02]          at FSharp.Compiler.Import.ImportILTypeDefList(FSharpFunc`2 amap, Range m, CompilationPath cpath, FSharpList`1 enc, FSharpList`1 items) in E:\repos\fsharp\src\Compiler\Checking\import.fs:line 724
[xUnit.net 00:00:01.02]          at FSharp.Compiler.Import.modty@727.Invoke(Unit _arg2) in E:\repos\fsharp\src\Compiler\Checking\import.fs:line 727
[xUnit.net 00:00:01.02]          at Internal.Utilities.Library.InterruptibleLazy`1.get_Value() in E:\repos\fsharp\src\Compiler\Utilities\illib.fs:line 33
[xUnit.net 00:00:01.02]          at Internal.Utilities.Library.Extras.MaybeLazy`1.Force() in E:\repos\fsharp\src\Compiler\Utilities\lib.fs:line 396
[xUnit.net 00:00:01.02]          at FSharp.Compiler.CompilerImports.TcImports.ccuHasType(CcuThunk ccu, FSharpList`1 nsname, String tname, Boolean publicOnly) in E:\repos\fsharp\src\Compiler\Driver\CompilerImports.fs:line 1296
[xUnit.net 00:00:01.02]          at FSharp.Compiler.CompilerImports.TcImports.tryFindSysTypeCcu@2596-1.Invoke(CcuThunk ccu) in E:\repos\fsharp\src\Compiler\Driver\CompilerImports.fs:line 2596
[xUnit.net 00:00:01.02]          at Microsoft.FSharp.Collections.ArrayModule.loop@1144-40[T](FSharpFunc`2 predicate, T[] array, Int32 i) in E:\repos\fsharp\src\FSharp.Core\array.fs:line 1147
[xUnit.net 00:00:01.02]          at Microsoft.FSharp.Collections.ArrayModule.TryFind[T](FSharpFunc`2 predicate, T[] array) in E:\repos\fsharp\src\FSharp.Core\array.fs:line 1152
[xUnit.net 00:00:01.02]          at FSharp.Compiler.TcGlobals.TcGlobals.tryFindSysTypeCcu(FSharpList`1 path, String nm) in E:\repos\fsharp\src\Compiler\TypedTree\TcGlobals.fs:line 216
[xUnit.net 00:00:01.02]          at FSharp.Compiler.TcGlobals.TcGlobals.tryFindSysAttrib(String nm) in E:\repos\fsharp\src\Compiler\TypedTree\TcGlobals.fs:line 320
[xUnit.net 00:00:01.02]          at FSharp.Compiler.TcGlobals.TcGlobals..ctor(Boolean compilingFSharpCore, ILGlobals ilg, CcuThunk fslibCcu, String directoryToResolveRelativePaths, Boolean mlCompatibility, Boolean isInteractive, Boolean checkNullness, Boolean useReflectionFreeCodeGen, FSharpFunc`2 tryFindSysTypeCcuHelper, Boolean emitDebugInfoInQuotations, Boolean noDebugAttributes, PathMap pathMap, LanguageVersion langVersion, Boolean realsig) in E:\repos\fsharp\src\Compiler\TypedTree\TcGlobals.fs:line 1079
[xUnit.net 00:00:01.02]          at FSharp.Compiler.CompilerImports.TcImports.BuildFrameworkTcImports@2589-10.Invoke(FSharpList`1 _arg10) in E:\repos\fsharp\src\Compiler\Driver\CompilerImports.fs:line 2602
[xUnit.net 00:00:01.02]          at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in E:\repos\fsharp\src\FSharp.Core\async.fs:line 528
[xUnit.net 00:00:01.02]          at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\repos\fsharp\src\FSharp.Core\async.fs:line 112
[xUnit.net 00:00:01.02]          --- End of inner exception stack trace ---
[xUnit.net 00:00:01.02]          at Internal.Utilities.Library.PervasiveAutoOpens.Async.RunImmediate.Static[T](FSharpAsync`1 computation, FSharpOption`1 cancellationToken) in E:\repos\fsharp\src\Compiler\Utilities\illib.fs:line 151
[xUnit.net 00:00:01.02]          at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible, FSharpOption`1 legacyReferenceResolver) in E:\repos\fsharp\src\Compiler\Interactive\fsi.fs:line 4673
[xUnit.net 00:00:01.02]       Stack Trace:
[xUnit.net 00:00:01.02]            at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1448.Invoke(String message)
[xUnit.net 00:00:01.02]         E:\repos\fsharp\src\Compiler\Interactive\fsi.fs(4676,0): at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible, FSharpOption`1 legacyReferenceResolver)
[xUnit.net 00:00:01.02]         E:\repos\fsharp\src\Compiler\Interactive\fsi.fs(5007,0): at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, FSharpOption`1 collectible, FSharpOption`1 legacyReferenceResolver)
[xUnit.net 00:00:01.02]         E:\repos\fsharp\tests\FSharp.Test.Utilities\CompilerAssert.fs(1004,0): at FSharp.Test.CompilerAssert.RunScriptWithOptionsAndReturnResult(String[] options, String source)
[xUnit.net 00:00:01.02]         E:\repos\fsharp\tests\FSharp.Test.Utilities\CompilerAssert.fs(1019,0): at FSharp.Test.CompilerAssert.RunScriptWithOptions(String[] options, String source, FSharpList`1 expectedErrorMessages)
[xUnit.net 00:00:01.02]         E:\repos\fsharp\tests\FSharp.Test.Utilities\CompilerAssert.fs(1029,0): at FSharp.Test.CompilerAssert.RunScript(String source, FSharpList`1 expectedErrorMessages)
[xUnit.net 00:00:01.02]         E:\repos\fsharp\tests\fsharp\Compiler\Language\SpanTests.fs(91,0): at FSharp.Compiler.UnitTests.SpanTests.Script_ReadOnlySpanForInDo()
[xUnit.net 00:00:01.02]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[xUnit.net 00:00:01.02]            at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[xUnit.net 00:00:05.32]       failing on main
```

The code in question:

https://github.com/dotnet/fsharp/blob/05cf88673f59c802438b7f6e213bab5cd47946b7/src/Compiler/AbstractIL/il.fs#L2914-L2944

### PR DESCRIPTION
**Pull request by majocha**
Custom lazy implementation does not seem to be needed in this particular case.
Fixes #17803

### CODE REVIEW

File: src/Compiler/AbstractIL/il.fs [hunk 1]
```diff
@@ -2913,35 +2913,17 @@ and [<NoEquality; NoComparison>] ILPreTypeDef =
 
 /// This is a memory-critical class. Very many of these objects get allocated and held to represent the contents of .NET assemblies.
 and [<Sealed>] ILPreTypeDefImpl(nameSpace: string list, name: string, metadataIndex: int32, storage: ILTypeDefStored) =
-    let mutable store: ILTypeDef = Unchecked.defaultof<_>
-    let mutable storage = storage
+    let stored =
+        lazy
+        match storage with
+        | ILTypeDefStored.Given td -> td
+        | ILTypeDefStored.Computed f -> f ()
```
Comment (T-Gro) [inline src/Compiler/AbstractIL/il.fs:2920]: I think the manual solution was in place to avoid allocations for Lazy and the closure passed into it, as per the comment above.
Also see how the "storage" was set to null to avoid holding it.

Comment (majocha) [reply src/Compiler/AbstractIL/il.fs:2920]: Yes I've been thinking about it. This is almost identical to `System.Lazy<_>` implementation which also does not keep the delegate after executing it.

My reasoning was that this will not allocate any less than standard System.Lazy, so the reimplementation is not worth the cognitive overhead here.

I admit I didn't profile it. I just looked at the benchmarks in CI and concluded allocations look the same.

Comment (majocha) [reply src/Compiler/AbstractIL/il.fs:2920]: We must keep the `storage` somewhere up to the point it is unwrapped, one way or another. The open question is what is the difference in performance / allocations between a member method (before) and the System.Lazy taking a delegate (this pr) and how well this gets optimized. I'll try doing a dedicated benchmark.

Comment (T-Gro) [reply src/Compiler/AbstractIL/il.fs:2920]: The storage as a field will be still there.
But the contents of that reference, if no longer held, could have been GC'd in the original implementation and now can't - I hope I am interpreting the difference correctly.

Comment (majocha) [reply src/Compiler/AbstractIL/il.fs:2920]: The point is we're not holding it at all. Once it's captured by the closure it should only be there and only for the lifetime of the delegate (?) Now I'm tempted to also decompile this and see what's what :)

Comment (majocha) [reply src/Compiler/AbstractIL/il.fs:2920]: https://sharplab.io/#gist:dafe4d03aef26e424e6ac8e72350a738 This is kind of what I meant.

Anyway, this here was just a quick fix to get me unblocked.
There is value in having a carefully crafted performant implementation for memory critical stuff, I'll try to fix the current implementation and compare properly.

Comment (T-Gro) [reply src/Compiler/AbstractIL/il.fs:2920]: The arguments are passed as part of the closure to Lazy. But if Lazy gets rid of the closure object, it will work the same.
https://sharplab.io/#v2:DYLgZgzgNAJiDUAfAsAKDQFwJ4AcCmABAJIAyAKrngCJ5gEC8BEGATgJYB2A5mgNoA8AOQD2AUQCOAVwCGwNtgDcIgMLCAtjmnsIwjgD4AupkrFylGmADKGYSzwwGBVRskZ7BYXQAUkjvIIAtHqmFPgWAJRoxvgEApZ4svaGpgAKdqHUtEQawF4c0mp4lpoAxnggTKycXARyzFAE+YUVzOzcDYUY0jDSXUQcMHgAHhWcGADMAEwNzLbSXOUh5rTWtvbhDGgE27V4GJVrDvRbO6fA0gBeWCen22q9JQAWByzzhADu8o83t4hLYSsbHYYAA6Zw4VzuOhBAjeSKoW47H6FNQAIzwLAIAH0QQBxPZeDaMWbAkEANVkkjwUXQtKAA
OK, I am convinced - will approve.

**Review by T-Gro — APPROVED** [review]

**Review by vzarytovskii — APPROVED** [review]
