### PR TITLE
Fix access checking for properies setters in attribute arguments

### LINKED ISSUE #18571: Compiler allows setting a value of a private property on attribute
Compiler allows to "set" a value of a property _with private setter_ on an attribute. This doesn't work in runtime and isn't allowed by the C# compiler, even though it has _some_ representation in the assembly metadata.

**Repro steps**

1. Create a new F# project on .NET 9.0.300 SDK
2. Install package `CommandLineParser` v2.9.1
3. Write this:
   ```fsharp
   [<CommandLine.Verb("start", HelpText = "Start the game", IsDefault = true)>]
   type StartGame() = class end
   ```

Here's a ZIP archive with the project: [ConsoleApp19.zip](https://github.com/user-attachments/files/20274404/ConsoleApp19.zip)

**Expected behavior**

The code should not compile. Inspect the `VerbAttribute` and note that it has a _constructor parameter_ named `isDefault` (starting from lowercase) that's accessible, and a _property_ (starting from a capital letter) `IsDefault` that _has a private setter_.

See this code: https://github.com/commandlineparser/commandline/blob/1e3607b97af6141743edb3c434c06d5b492f6fb3/src/CommandLine/VerbAttribute.cs#L67-L70

> ```csharp
> public bool IsDefault { get; private set; }
> ```

A corresponding C# program doesn't compile:
```csharp
using CommandLine;

Console.WriteLine("Hello, World!");

[Verb("foo", IsDefault = true)]
class Foo ;
```

> Error CS0617 : 'IsDefault' is not a valid named attribute argument. Named attribute arguments must be fields which are not readonly, static, or const, or read-write properties which are public and not static.

**Actual behavior**

F# compiler happily compiles the code above, and as far as I see this assignment has no effect in runtime, even though it (surprisingly) gets compiled to some metadata.

**Known workarounds**

Do not use the erroneous construction in F# code. In the particular case, use the (valid) `isDefault = true` instead of `IsDefault = true`.

**Related information**

Provide any related information (optional):

* Operating system: Windows
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET SDK 9.0.300
* Editing Tools (e.g. Visual Studio Version, Visual Studio): doesn't matter, happens in console compiler as well

### PR DESCRIPTION
**Pull request by evgTSV**
## Description

Fixes #18571

I use checking from `MethInfoChecks`

## Checklist

- [x] Test cases added
- [ ] Release notes entry updated:

### CODE REVIEW

**Comment by evgTSV** [comment]
@vzarytovskii I don't think #18575 can solve this problem, I looked into the code of the `IsPropInfoAccessible` function, it only defines access to the property getter, so I used the code from checking the property during the processing of the constructors args of a type that is not an attribute

**Comment by evgTSV** [comment]
Ok, I can close this pr and go to #18575

**Comment by vzarytovskii** [comment]
> Ok, I can close this pr and go to #18575

It's fine to process here, I was just curious whether it overlaps or not. I can close that one down and you can incorporate changes into one/this one. Conversing with copilot is a bit tiresome.

**Comment by evgTSV** [comment]
> It's fine to process here, I was just curious whether it overlaps or not. I can close that one down and you can incorporate changes into one/this one. Conversing with copilot is a bit tiresome.

Yeah, I'll work on this pr then

**Comment by T-Gro** [comment]
For sure carry on, please consider the currently open copilot PRs more of an exercise of the capabilities - pick anything good from there and we can close it down and keep yours only :)

File: src/Compiler/Checking/Expressions/CheckExpressions.fs [hunk 1]
```diff
@@ -11411,6 +11411,9 @@ and TcAttributeEx canFail (cenv: cenv) (env: TcEnv) attrTgt attrEx (synAttr: Syn
                       | Item.Property (info = [pinfo]) ->
                           if not pinfo.HasSetter then
                             errorR(Error(FSComp.SR.tcPropertyCannotBeSet0(), m))
+                          let setterMeth = pinfo.SetterMethod
+                          if not (setterMeth.IsProtectedAccessibility) && not(IsTypeAndMethInfoAccessible cenv.amap m ad ad setterMeth) then
```
[the remark this answers is not in the document]
Comment (smoothdeveloper) [reply src/Compiler/Checking/Expressions/CheckExpressions.fs]: @copilot I think it is fine as is.

**Comment by evgTSV** [comment]
@dotnet-policy-service agree

**Comment by evgTSV** [comment]
@dotnet-policy-service agree

File: tests/FSharp.Compiler.ComponentTests/Attributes/AttributeCtorSetPropAccess.fs [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+    
+    module TestAttributeModule =
+
+        [<FooAttribute(X = 100)>]
+        let myFunction() = ()
+    """
+
+    [<Theory>]
+    [<InlineData("private", setPrivatePropFsCode)>]
+    [<InlineData("internal", setInternalPropFsCode)>]
```
Comment (T-Gro) [inline tests/FSharp.Compiler.ComponentTests/Attributes/AttributeCtorSetPropAccess.fs:46]: Can you include `protected` in that test setup as well?

File: tests/FSharp.Compiler.ComponentTests/Attributes/AttributeCtorSetPropAccess.fs [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+    open TestAttribute
+    
+    module TestAttributeModule =
+
+        [<FooAttribute(X = 100)>]
+        let myFunction() = ()
+    """
+    
+    [<Literal>]
+    let private setInternalPropFsCode = """
```
Comment (T-Gro) [inline tests/FSharp.Compiler.ComponentTests/Attributes/AttributeCtorSetPropAccess.fs:33]: These 2 code blocks are the same.. ?

File: tests/FSharp.Compiler.ComponentTests/Attributes/AttributeCtorSetPropAccess.fs (hunk 2 above)
Comment (evgTSV) [reply tests/FSharp.Compiler.ComponentTests/Attributes/AttributeCtorSetPropAccess.fs]: Added for all modifiers

**Review by T-Gro — APPROVED** [review]
