### PR TITLE
FSharp.Core 'query' related fixes

### LINKED ISSUE #47: Tuples in query expression with grouping cannot be translated to SQL
Opened by tomasp on CodePlex

When answering  this StackOverflow question, I came across an odd behavior that appears to be a bug:

``` fsharp
#r "FSharp.Data.TypeProviders.dll"
#r "System.Data.Linq.dll"
open System
open System.Data
open System.Linq
open Microsoft.FSharp.Data.TypeProviders

type dbSchema = SqlDataConnection< @"Server=.\SQLExpress;AttachDbFilename=C:\Temp\Northwind.mdf;Database=dbname;Trusted_Connection=Yes;">
let db = dbSchema.GetDataContext()

query {
    for p in db.Products do
    join c in db.Categories on (p.ProductID = c.CategoryID)
    groupBy p.CategoryID.Value into g
    select (g.Key, g.Select(fun (p, c) -> if p.ProductName = c.CategoryName then 1.0 else 0.0).Average()) }
|> Array.ofSeq
```

Running this gives the following message:

System.InvalidOperationException: Member access 'Products Item1' of 'System.Tuple2[Products,Categories]' not legal on type 'Microsoft.FSharp.Linq.RuntimeHelpers.Grouping2[System.Int32,System.Tuple`2[Products,Categories]].

It appears that somewhere during the translation, the translator attempts to generate (or process) code that accesses the Item1 property (which should be a property of the elements in the collection) as if it was a property of the entire grouping. 

Is the F# library doing some pre-processing here? I remember that tuples were always a problem in F# queries, because they are immutable and so they behave differently than C# anonymous types (which the translator handles well)...

> comments
> latkin wrote Apr 24, 2014 at 12:56 PM [x] 
> Yes, we have rather nasty issues that arise due to immutable/mutable tuple conversions in queries. See this issue, for example.
> 
> > tomasp wrote Apr 25, 2014 at 8:44 AM [x] 
> > Thanks for the clarification! This makes sense - I remember trying to get that to work in some earlier versions of F# LINQ and it was pretty messy.
> > Could someone who knows the code share a few pointers to the relevant bits in the F# codebase? >>This sounds like an issue that people from the F# community could help to fix (because it is quite separate stand-alone component that can be modified without knowing everything about the compiler :-)).
> > I'm sure that with a bit of help & starting points, we could get a nice pull request for this one!
> > 
> > > dsyme wrote Apr 28, 2014 at 7:28 AM [x] 
> > > The general area is here:
> > > [https://github.com/fsharp/fsharp/blob/65eb229125713caa2a97d85e6541313f9da4d9f7/src/fsharp/FSharp.Core/Query.fs#L1065](https://github.com/fsharp/fsharp/blob/65eb229125713caa2a97d85e6541313f9da4d9f7/src/fsharp/FSharp.Core/Query.fs#L1065)
> > > The implementation is non-trivial I'm afraid, one of the hardest parts of FSharp.Core 
> > > 
> > > > vladima wrote Apr 28, 2014 at 9:21 AM [x] 
> > > > Some time ago I've prototyped implementation that 1) converts quotations to the shape similar to ETs produced by C# compiler 2) delays translation Tuple <-> AnonymousObject to the last step so query composition should not be affected by it. Maybe it is time to publish it as possible alternative that can replace existing implementation somewhere in the future (far far away)

### LINKED ISSUE #422: Query expressions and --warnon:1182
In query expressions, variables bound using `for` are not recognized as used if they are not `select`ed, even if they are otherwise used for example in a `where` or a `let`.

Example:

``` fsharp
// Expected: no warning
// Actual:   warning FS1182: The value 'x' is unused
query { for x in [1;2;3] do
        where (x > 2)
        select 1 }

// Expected: no warning
// Actual:   warning FS1182: The value 'x' is unused
query { for x in [1;2;3] do
        let y = x
        select y }

// Expected: no warning
// Actual:   no warning
query { for x in [1;2;3] do
        where (x > 2)
        select x }
```

Tested on F# 3.1.2 and 4.0-RC.

### LINKED ISSUE #3445: Bug in query translation of conditionals
#### Repro steps

Evaluate 

    query {if 1 = 2 then select 3};; 

in fsi.exe

#### Expected behavior

works 

#### Actual behavior

```
System.ArgumentException: Type mismatch when building 'cond': types of true and false branches differ. Expected 'System.Linq.IQueryable`1[Microsoft.FSharp.Core.Unit]', but received type 'System.Linq.IQueryable`1[System.Linq.IQueryable`1[Microsoft.FSharp.Core.Unit]]'.
Parameter name: receivedType
   at Microsoft.FSharp.Quotations.PatternsModule.checkTypesSR[a](Type expectedType, Type receivedType, a name, String threeHoleSR)
   at Microsoft.FSharp.Quotations.PatternsModule.mkIfThenElse(FSharpExpr e, FSharpExpr t, FSharpExpr f)
   at Microsoft.FSharp.Quotations.FSharpExpr.IfThenElse(FSharpExpr guard, FSharpExpr thenExpr, FSharpExpr elseExpr)
   at Microsoft.FSharp.Linq.QueryModule.TransInner(CanEliminate canElim, Boolean check, FSharpExpr immutQuery)
   at Microsoft.FSharp.Linq.QueryModule.TransInnerApplicative(Boolean check, FSharpExpr source, FSharpVar immutConsumingVar, FSharpExpr immutConsumingExpr)
   at Microsoft.FSharp.Linq.QueryModule.TransInner(CanEliminate canElim, Boolean check, FSharpExpr immutQuery)
   at Microsoft.FSharp.Linq.QueryModule.TransInnerAndCommit(CanEliminate canElim, Boolean check, FSharpExpr x)
   at Microsoft.FSharp.Linq.QueryModule.TransInnerWithFinalConsume(CanEliminate canElim, FSharpExpr immutSource)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedOuter(CanEliminate canElim, FSharpExpr tm)
   at Microsoft.FSharp.Linq.QueryModule.clo@1730-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error
```

#### Known workarounds

Don't use this particular shape of query

### LINKED ISSUE #3782: Query builder with EF core can't return fsharp tuples (and sometimes new objects) using async methods
I'm getting an exсeption when using this code

```
    [<CLIMutable>]
    type Product =
        {
            Id: string
            Name: string
        }

    let db = new MyContext()
    let q = query {
        for p in db.Products do
        select (p.Id, p.Name)
    }
    let result = q.ToListAsync().Result
```
If I choose `select p`  or `select p.Id` insead of `select (p.Id, p.Name)` , this works fine. If I write `ToList` instead of `ToListAsync` this works fine as well. C# version with Tuples works well. With provided F# code it fails with this exception:

```
Unhandled Exception: System.InvalidOperationException: The source IQueryable doesn't implement IAsyncEnumerable<System.Tuple`2[System.String,System
.String]>. Only sources that implement IAsyncEnumerable can be used for Entity Framework asynchronous operations.
   at Microsoft.EntityFrameworkCore.Extensions.Internal.QueryableExtensions.AsAsyncEnumerable[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToke
n)
```
Also noticed that `select { Id = p.Id; Name = p.Name }` works, while `select { Name = p.Name; Id = p.Id }` doesn't and fails with exception:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (When called from 'VisitLambda', rewriting a node of type 'System.Linq
.Expressions.ParameterExpression' must return a non-null value of the same type. Alternatively, override 'VisitLambda' and change it to not visit c
hildren of this type.) ---> System.InvalidOperationException: When called from 'VisitLambda', rewriting a node of type 'System.Linq.Expressions.Par
ameterExpression' must return a non-null value of the same type. Alternatively, override 'VisitLambda' and change it to not visit children of this
type.
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallE
xpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvide
r, IDatabase database)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass24_0`1.<CompileAsyncQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
```

* Windows 10
* .NET Core 2.0.0
* Microsoft.EntityFrameworkCore 2.0
* FSharp.Core 4.2.3
* FSharp.NET.Sdk 1.0.5

### LINKED ISSUE #7885: Query expression with join on tuple doesn't work
Joining on a composite key tuple within a query expression doesn't seem to work for plain records.
Note that this does work when using SQLProvider.

**Repro steps**

Repro repo is [here](https://github.com/2sComplement/linq-join-bug). Basically queries that join on a tuple return nothing.

No matches are returned from this, even when matches exist in the underlying data:
```fsharp
    let joinedInline =
        query {
            for t1 in queryable1s do
            join t2 in queryable2s on ((t1.Id1, t1.Id2) = (t2.Id1, t2.Id2))
            select (t1.Key, t2.Value)
        }
```
When the tuples are created in a function, matches are returned correctly:
```fsharp
    let joinedFunction =
        query {
            for t1 in queryable1s do
            join t2 in queryable2s on (Test1.Composite t1 = Test2.Composite t2)
            select (t1.Key, t2.Value)
        }
```

**Expected behavior**

A query with a join should return matches based on tuple equality. In other words, the two above queries should be equivalent. 

**Actual behavior**

No matches are returned for inline tuple joins.

**Known workarounds**

Call a function to generate the tuple inside the join condition. Note: this is not supported by SQLProvider.

**Related information**

* .NET Core 3.0

### LINKED ISSUE #11131: Different property order of a LINQ select expression cannot be translated
# Different property order of a LINQ select expression cannot be translated

This issue has a strong connection to my findings on [Stack Overflow](https://stackoverflow.com/questions/66232611/why-could-the-f-linq-expression-not-be-translated-at-least-partially) but I think it is important to put it in the right place (hopefully). Furthermore, there is a similar issue ([#3782](https://github.com/dotnet/fsharp/issues/3782)) which highlights the usage of a tuple type for the select expression of a query. 

For this issue I would like to emphasise that unfortunately, the F# LINQ expression cannot be translated, when the order of the property names of an anonymous or type record changes. 

In order to evaluate the issue and make it testable I implemented some XUnit tests. Apart from that, I also have a minimum testable example which can be applied with LINQPad.

Any suggestions or solutions would be greatly appreciated. 

**The following error appears**

```f#
System.InvalidOperationException : The LINQ expression 'LastName' could not
be translated. Either rewrite the query in a form that can be translated, or 
switch to client evaluation explicitly by inserting a call to 'AsEnumerable',
'AsAsyncEnumerable', 'ToList', or 'ToListAsync'*
```

## Test and evaluation with LINQPad 6

I tested the behaviour with LINQPad in order to make the use case more simple. Therefore, I used the DemoDB which should be available for everyone.

```f#
// successful query
query { 
    for c in this.Categories do
    select {| A = c.CategoryID; B = c.CategoryName; |}
}
```

```f#
// failed query
query { 
    for c in this.Categories do
    select {| B = c.CategoryID; A = c.CategoryName; |}
}

The argument 'value' was the wrong type. Expected 
'System.Func`2[System.Int32,<>f__AnonymousType1383943985`2[System.String,System.Int32]]'. 
Actual '<>f__AnonymousType1383943985`2[System.String,System.Int32]'.
```

### Test result summary

I tested the behaviour with .NET 3.1 and .NET 5.0 (projects as well as LINQPad 6). Furthermore, all dependencies have been adjusted accordingly (e.g. Entity Framework 5.0 or 3.1). 

| Test | Result    |
| ---- | --------- |
| A anonymous record   | successful|
| B anonymous record   | successful|
| C anonymous record   | failed    |
| D anonymous record   | failed    |
| E partial person type   | failed |
| F partial person type   | successful    |
| G partial person type   | successful    |
| H partial person type   | failed    |
| I partial person type   | failed    |

### Test outcome

```f#
System.InvalidOperationException : The LINQ expression 'LastName' could not be translated. Either rewrite the query in a form that can be translated, or switch
    to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'
Entity Framework Core "5.0.3" initialized 
'"TestContext"' using provider '"Microsoft.EntityFrameworkCore.InMemory"'
```

### EF core code first database .NET 5 project

```c#
public class Person
{
     public int Id { get; set; }
     public string LastName { get; set; }
}
...
public void Configure(EntityTypeBuilder<Person> builder)
{
      builder.ToTable("PERSON");
      builder.HasKey(x => x.Id);
      builder.Property(x => x.Id)
             .HasColumnName("ID")
             .ValueGeneratedNever();
      builder.Property(x => x.LastName)
             .HasColumnName("LASTNAME")
             .HasMaxLength(512)
             .IsUnicode(false);
}
...
public class TestContext : DbContext
{
     public DbSet<Person> Persons { get; private set; }
     public TestContext(DbContextOptions<TestContext> options) : base(options)
     {}
     protected override void OnModelCreating(ModelBuilder modelBuilder)
     {
          modelBuilder.ApplyConfiguration(new PersonConfig());
     }
}
```

## F# xunit test project in order to evaluate the EF core database context access

```f#
type PartialPerson = { LastName: string; ID : int; }

type ``success database execution queries`` (output: ITestOutputHelper) =
    let sLogger =
        LoggerConfiguration()
            .MinimumLevel.Verbose()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
            .MinimumLevel.Override("Microsoft.EntityFrameworkCore", LogEventLevel.Information)
            .Enrich.FromLogContext()
            .WriteTo.TestOutput(output, Events.LogEventLevel.Verbose)
            .WriteTo.Debug()
            .CreateLogger()
    let loggerFactory =
        (new LoggerFactory())
            .AddSerilog(sLogger)
    let options = DbContextOptionsBuilder<TestContext>()
                      .EnableSensitiveDataLogging(true)
                      .UseLoggerFactory(loggerFactory)
                      .UseInMemoryDatabase(Guid.NewGuid().ToString())
                      .Options;
    let context = new TestContext(options)
    [<Fact>]
    let ``success person select lastname Test A`` () =
        let rs =
            context.Persons.Select(
                fun person -> {| Name = person.LastName |} )
        rs |> should be Empty // successful
    [<Fact>]
    let ``success person select id and lastname Test B`` () =
        let rs =
            context.Persons.Select(
                fun person ->
                    {| ID = person.Id
                       LastName = person.LastName |})
        rs |> should be Empty // successful
    [<Fact>]
    let ``success person select id and lastname Test C`` () =
        let rs =
            context.Persons.Select(
                fun person ->
                    {| LastName = person.LastName
                       ID = person.Id |} )
        rs |> should be Empty // failed
    [<Fact>]
    let ``success person select id and lastname Test D`` () =
        let rs =
            query {
                for person in context.Persons do
                select 
                    {| LastName = person.LastName
                       ID = person.Id |}
            }
        rs |> should be Empty // failed

    // avoid anonymous record and use the partial person type
    // type PartialPerson = { LastName: string; ID : int; }
    [<Fact>]
    let ``success partial person select id and lastname Test E`` () =
        let rs =
            context.Persons.Select(
                fun person ->
                    { ID = person.Id
                      LastName = person.LastName })
        rs |> should be Empty // failed
    [<Fact>]
    let ``success partial person select id and lastname Test F`` () =
        let rs =
            context.Persons.Select(
                fun person ->
                    { LastName = person.LastName
                      ID = person.Id } )
        rs |> should be Empty // successful
    [<Fact>]
    let ``success partial person select id and lastname Test G`` () =
        let rs =
            query {
                for person in context.Persons do
                select 
                     { LastName = person.LastName
                       ID = person.Id }
            }
        rs |> should be Empty // successful
    [<Fact>]
    let ``success partial person select id and lastname Test H`` () =
        let rs =
            query {
                for person in context.Persons do
                select 
                     { ID = person.Id
                       LastName = person.LastName }
            }
        rs |> should be Empty // failed
    [<Fact>]
    let ``success partial person select id and lastname Test I`` () =
        let rs =
            query {
                for person in context.Persons do
                select 
                     { ID = person.Id
                       LastName = person.LastName }
            }
        rs.ToList() |> should be Empty // failed
```

### LINKED ISSUE #15133: Select multiple values in a query expression will make it not able to reuse to generate other SQL
In C#:
图片

图片

In F#:
图片

图片

**Expected behavior**

Queries selecting multiple value can be reuse to generate other SQL like C#

**Actual behavior**

The original query can be translate to SQL but new-added query not

**Related information**

.NET 7.0
Microsoft.EntityFrameworkCore.Sqlite 7.0.5

### LINKED ISSUE #15648: Inconsistent anonymous record instantiation on IQueryable
When projecting an anonymous record on `IQueryable` the generated tree contains a `Delegate.Invoke`  for the anonymous type constructor, this causes some parsers/drivers to be unable to understand the operation (eg. `Entity Framework`)

This looks to happen when accessing deep members and having long record member names.

**Repro steps**

Provide the steps required to reproduce the problem:

```fsharp
open System
open System.Linq

type Person = { Name: string; Id : int }
type Wrapper = { Person: Person }

let data = [
    { Person = { Name = "One"; Id = 1 } }
    { Person = { Name = "Two"; Id = 2 } }
    { Person = { Name = "Three"; Id = 3 } } 
  ]

let queryWithInvoke = 
    data
      .AsQueryable()
      .Select(fun x -> {| Other = {| Name = x.Person.Name; Id = x.Person.Id |} |})
      
// short label names do not generate an invoke call
let queryWithoutInvoke = 
    data
      .AsQueryable()
      .Select(fun x -> {| Other = {| A = x.Person.Name; B = x.Person.Id |} |})

printfn "%A" queryWithInvoke.Expression;
printfn "------"
printfn "%A" queryWithoutInvoke.Expression
```

Outputs:
```csharp
[{ Person = { Name = "One"
             Id = 9a093c1d-9a3c-4366-806e-7c32b4388a1d }
  Value = 0 }; { Person = { Name = "Two"
             Id = ded2fd37-69cd-4d56-bc05-69e539264301 }
  Value = 1 }; { Person = { Name = "Three"
             Id = 798c98fb-a772-4911-84cc-63101b369cb9 }
  Value = 2 }].Select(x => new <>f__AnonymousType1021199106`1(Name => new <>f__AnonymousType3987781292`2(x.Person.Id, Name).Invoke(x.Person.Name)))
------
[{ Person = { Name = "One"
             Id = 9a093c1d-9a3c-4366-806e-7c32b4388a1d }
  Value = 0 }; { Person = { Name = "Two"
             Id = ded2fd37-69cd-4d56-bc05-69e539264301 }
  Value = 1 }; { Person = { Name = "Three"
             Id = 798c98fb-a772-4911-84cc-63101b369cb9 }
  Value = 2 }].Select(x => new <>f__AnonymousType1021199106`1(new <>f__AnonymousType2589797714`2(x.Person.Name, x.Person.Id)))
```
The problem is:
```csharp
new <>f__AnonymousType1021199106`1(
    Name => new <>f__AnonymousType3987781292`2(
        x.Person.Id, Name
)
.Invoke(x.Person.Name)) // <- here
```

The first case generates a **plain constructor**, and the second injects an **IIFE** for `Person.Name` which causes inconsistency in query parsing

from: https://github.com/fsharp/fslang-suggestions/issues/1249

**Expected behavior**

No difference between the expressions

**Actual behavior**

Delegate invocation inside the expression

**Known workarounds**
Use small record labels 

**Related information**
* Windows 11 / MacOs / Arch Linux
* .NET6
* Editing Tools (any)

### LINKED ISSUE #16918: System.Linq.Expressions array indexer get maps to GetArray, not get_Item
Please provide a succinct description of the issue.

Array indexing within a an `Expression<'A -> 'B>` is mapped to a `GetArray` call (in line with how it works for `Expr` ?) rather than a `get_Item` invocation.

There does not appear to be a clean workaround aside from using a `list` or a `ResizeArray` instead (as the `get_Item` mechanism is not exposed).

Provide the steps required to reproduce the problem:

```
#r "nuget: Microsoft.Azure.Cosmos, 3.38.1"

open Microsoft.Azure.Cosmos
open Microsoft.Azure.Cosmos.Linq
open System.Linq

type Doc =
    {   p: string
        u: Unfold[] }
and Unfold =
    {   c: string }
let client = new CosmosClient(conns)
let c = client.GetDatabase("name").GetContainer("container")
let q = c.GetItemLinqQueryable<Doc>(allowSynchronousQueryExecution = true)
let i = q.Where(fun x -> x.p = "Snapshotted" )
         .OrderBy(fun d -> d.u[0].c)
         .Select(fun x -> x.u.[0].c)
printfn "%O" i.Expression
printfn "%s" (i.ToQueryDefinition().QueryText)
for x in i.Take(2) do
    printfn $"%A{x}"
```

**Expected behavior**

Should generate SQL of the form:

> `dbs/name/colls/container.Where(x => (x.p == "Snapshotted")).OrderBy(d => d.u.get_Item(0).c).Select(x => x.u.get_Item(0).c)`

Which yields correct SQL:

`SELECT VALUE root["u"][0]["c"] FROM root WHERE (root["p"] = "Snapshotted") ORDER BY root["u"][0]["c"] ASC`

**Actual behavior**

> `dbs/name/colls/container.Where(x => (x.p == "Snapshotted")).OrderBy(d => GetArray(d.u, 0).c).Select(x => GetArray(x.u, 0).c)`

>`Microsoft.Azure.Cosmos.Linq.DocumentQueryException: Method 'GetArray' is not supported.`

**Known workarounds**

Switch the `u: Unfold[]` to be a `ResizeArray` (or event a `list` !)

**Related information**

(Rider F# interactive 3032.3.2, SDK 8.0.101)

### LINKED ISSUE #19099: `LeafExpressionConverter.EvaluateQuotation` fails to handle some cases
**Repro steps and actual behavior**

`FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation` raises a `NotSupportedException` when the quotation contains sequencing or variable/property/field mutation:

```fsharp
let eval = LeafExpressionConverter.EvaluateQuotation

eval <@ a; b @>
eval <@ a <- b @>
eval <@ a.b <- c @>
// System.NotSupportedException: Could not convert the following F# Quotation to a LINQ Expression Tree
```

Also, when the quotation is of type `unit` and the compiled expression tree is of type `System.Void` (such as a void method call) or something else (a mutation), Linq raises an `ArgumentException`:

```fsharp
eval <@ System.Console.WriteLine("Hello, World") @>
// System.ArgumentException: Expression of type 'System.Void' cannot be used for return type 'Microsoft.FSharp.Core.Unit'
```

**Expected behavior**

The function should correctly compile the expression to Linq tree and execute in these cases.

**Known workarounds**

Avoid these problematic constructs in the quotation. For example, write `a.set_b(c)` instead of `a.b <- c`.

### PR DESCRIPTION
**Pull request by T-Gro**
## Summary

Fixes **10 query expression bugs** affecting LINQ provider compatibility (EF Core, Cosmos DB, etc.).

## Fixed Issues

- **Expression Tree Generation** (`src/FSharp.Core/Linq.fs`)
  - Fixes #11131, Fixes #15648 — Anonymous record field ordering
    - Let-bindings now inlined instead of `Lambda.Invoke` pattern
    - Tests: `QueryTests.fs` — field order tests
  - Fixes #16918 — Array indexer generates `ArrayIndex` instead of `GetArray`
    - Fixed `ArrayLookupQ` pattern match (1 type param, not 3)
    - Tests: `FSharpQuotations.fs` — 3 array indexing tests
  - Fixes #19099 — `EvaluateQuotation` fails for Sequential/VarSet/unit
    - Added handlers for `Sequential`, `VarSet`, `FieldSet`, `PropertySet`
    - Tests: `QueryTests.fs` — 7 EvaluateQuotation tests

- **Query Translation** (`src/FSharp.Core/Query.fs`)
  - Fixes #3782, Fixes #15133 — Tuple select breaks IQueryable
    - Use `Queryable.Select` instead of `Enumerable.Select` + `AsQueryable`
    - Tests: `QueryTests.fs` — IQueryable preservation tests
  - Fixes #3445 — Conditional query translation bug
    - Extract element type for `MakeEmpty` in `IfThenElse`
    - Tests: `QueryTests.fs` — conditional query tests

- **AnonymousObject Equality** (`src/FSharp.Core/MutableTuple.fs`)
  - Fixes #7885, Fixes #47 — Join/GroupBy with tuple keys fails
    - Added `Equals`/`GetHashCode` to `AnonymousObject<T>` types
    - Tests: `QueryTests.fs` — tuple join/groupBy tests

- **Compiler** (`src/Compiler/.../CheckComputationExpressions.fs`)
  - Fixes #422 — FS1182 false positive in query expressions
    - Mark synthetic query lambda parameters as compiler-generated
    - Tests: `ComputationExpressionTests.fs` — 6 FS1182 tests

## Not Fixed

- #3845 — `headOrDefault` with struct/tuple returns null
  - Requires future `'T : default` constraint ([fslang-suggestions#1423](https://github.com/fsharp/fslang-suggestions/issues/1423))
  - Workaround: `select (Some x)` + `headOrDefault` with pattern matching

## Breaking Changes

See [`BREAKING_CHANGES.md`](./BREAKING_CHANGES.md). Summary:
- 🔴 `AnonymousObject<T>` now uses structural equality
- 🟡 Expression tree structure changes (let-bindings, array access)
- 🟡 Tuple projections preserve `IQueryable` type

### CODE REVIEW

File: src/Compiler/Checking/Expressions/CheckComputationExpressions.fs [hunk 1]
```diff
@@ -123,11 +123,29 @@ let mkSimplePatForVarSpace m (patvs: Val list) =
     let spats =
         match patvs with
```
Comment (abonie) [inline src/Compiler/Checking/Expressions/CheckComputationExpressions.fs]: A little confused why this whole pattern match is necessary instead of just `pavts |> List.map (fun v -> mkSynCompGenSimplePatVar v.Id)`, although this comment also applies to the code before the changes

File: src/FSharp.Core/Linq.fs [hunk 2]
```diff
@@ -34,10 +34,21 @@ module LeafExpressionConverter =
         {   varEnv : Map<Var, Expression> }
     let asExpr x = (x :> Expression)
 
-    let instanceBindingFlags = BindingFlags.Instance ||| BindingFlags.Public ||| BindingFlags.NonPublic ||| BindingFlags.DeclaredOnly
+    let _instanceBindingFlags = BindingFlags.Instance ||| BindingFlags.Public ||| BindingFlags.NonPublic ||| BindingFlags.DeclaredOnly
```
Comment (abonie) [inline src/FSharp.Core/Linq.fs]: I suppose this can be removed now?

**Comment by vzarytovskii** [comment]
Since it introduces a bunch of breaking changes, shall minor/major version of fslib be bumped?

File: tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs [hunk 3]
```diff
@@ -2258,4 +2258,109 @@ but here has type
...
+    // compiler-generated, which prevents the FS1182 warning from firing.
+    // =====================================================================
+
+    [<Fact>]
+    let ``Query expression variable with underscore prefix should not warn FS1182 - issue 422`` () =
+        FSharp """
+module Test
+
+let result = 
+    query { for _x in [1;2;3] do
```
Comment (auduchinok) [inline tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs]: Are there also tests that show that the warning is still reported where expected?

Comment (T-Gro) [reply tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs]: Good catch @auduchinok  - you're right, those tests were missing. I've added two tests that verify FS1182 is still reported where expected:

- Query with unused variable in select scope still warns FS1182 - verifies let unused = 42 inside a select (...) expression still triggers the warning
- Local unused variable in function with query still warns FS1182 - verifies let unused = 42 in a function containing a query still triggers the warning

The fix only marks synthetic lambda parameters (created by query translation for join/groupJoin/zip) as compiler-generated - user-written bindings still warn as expected.

File: tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs [hunk 4]
```diff
@@ -2363,4 +2363,40 @@ let result =
...
+        |> ignore
+
+    [<Fact>]
+    let ``Local unused variable in function with query still warns FS1182`` () =
+        FSharp """
+module Test
+
+let f () =
+    let unused = 42
+    query { for x in [1;2;3] do select x }
```
Comment (auduchinok) [inline tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs]: I'm not sure what does this case actually test, relative to the changes in the PR. Are outer bindings somehow rewritten as well?

**Review by auduchinok — COMMENTED** [review]
@T-Gro Could you please also add the test covering the case from the original comment but without making the name ignore the warning?

File: tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs (hunk 3 above)
Comment (auduchinok) [reply tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs]: @T-Gro Is this comment AI-generated?..

Comment (auduchinok) [reply tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs]: > The fix only marks synthetic lambda parameters (created by query translation for join/groupJoin/zip) as compiler-generated

The original patterns still need to be reported if unused, even when there're compiler generated ones introduced.

Comment (T-Gro) [reply tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs]: Yes, it is AI-assisted.
Do the newly added two tests not cover the warnings for original patterns? Or do you have other tests in mind?

Comment (auduchinok) [reply tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs]: No, they do not, they only cover the cases where non-rewritten patterns are unused.
I'd add the case that's exactly the same as this one, except for the allow-to-be-ignored name.

Comment (T-Gro) [reply tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs]: Ah ok, now I see what you meant. Will add.

File: tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs [hunk 5]
```diff
@@ -2258,4 +2258,147 @@ but here has type
...
+        """
+        |> withOptions ["--warnon:FS1182"]
+        |> asLibrary
+        |> compile
+        |> withSingleDiagnostic (Warning 1182, Line 4, Col 9, Line 4, Col 15, "The value 'unused' is unused")
+        |> ignore
+
+    // =====================================================================
```
Comment (T-Gro) [inline tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs]: Putting a blocker comment here, massive thanks to @auduchinok for spotting the lack of testing.
This is solvable, the commenting below is rubbish.

(it did trigger as unused before this PR, the 'fix' for including things like `where(x>2)` went too far.

File: tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs [hunk 6]
```diff
@@ -2258,4 +2258,110 @@ but here has type
...
+    let ``Genuinely unused query loop variable warns FS1182`` () =
+        FSharp """
+module Test
+let result = query { for x in [1;2;3] do select 1 }
+        """
+        |> withOptions ["--warnon:FS1182"]
+        |> asLibrary
+        |> compile
+        |> shouldFail
+        |> withSingleDiagnostic (Warning 1182, Line 3, Col 26, Line 3, Col 27, "The value 'x' is unused")
```
Comment (T-Gro) [inline tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs]: @auduchinok :

This is the feature saved by your eagle eyes.
Would you mind having another look? The implementation over at CheckComputationExpressions is redone, and IMO now a lot better isolated (dedicated query handling logic and transfer of flag about being used from the generated code back to the original Vals)

File: src/Compiler/Checking/Expressions/CheckComputationExpressions.fs [hunk 7]
```diff
@@ -113,27 +113,55 @@ let mkSourceExprConditional isFromSource callExpr sourceMethInfo builderValName
...
 
 let mkPatForVarSpace m (patvs: Val list) =
     match patvs with
     | [] -> SynPat.Const(SynConst.Unit, m)
     | [ v ] -> mkSynPatVar None v.Id
     | vs -> SynPat.Tuple(false, (vs |> List.map (fun x -> mkSynPatVar None x.Id)), [], m)
 
+/// Transfer HasBeenReferenced across query lambda Vals with the same name.
+/// In queries, multiple lambdas may have Vals with the same name (for, where, join).
+/// If any is referenced by user code, mark all as referenced to avoid FS1182 false positives.
```
Comment (auduchinok) [inline src/Compiler/Checking/Expressions/CheckComputationExpressions.fs]: Are there any tests covering how FS1182 works in relation with shadowing?

File: src/Compiler/Checking/Expressions/CheckComputationExpressions.fs [hunk 8]
```diff
@@ -113,27 +113,55 @@ let mkSourceExprConditional isFromSource callExpr sourceMethInfo builderValName
 let inline mkSynLambda p e m =
     SynExpr.Lambda(false, false, p, e, None, m, SynExprLambdaTrivia.Zero)
 
+// Use synthetic ranges so compiler-generated varSpace refs don't mark vals as referenced for FS1182
 let mkExprForVarSpace m (patvs: Val list) =
     match patvs with
     | [] -> SynExpr.Const(SynConst.Unit, m)
-    | [ v ] -> SynExpr.Ident v.Id
-    | vs -> SynExpr.Tuple(false, (vs |> List.map (fun v -> SynExpr.Ident(v.Id))), [], m)
+    | [ v ] -> SynExpr.Ident(Ident(v.Id.idText, v.Id.idRange.MakeSynthetic()))
```
Comment (auduchinok) [inline src/Compiler/Checking/Expressions/CheckComputationExpressions.fs]: Maybe I'd add something like `MakeSynthetic` method to `Ident` type if this is a repeated pattern across the codebase. It's fine as it is, though 🙂

File: src/Compiler/Checking/Expressions/CheckComputationExpressions.fs [hunk 9]
```diff
@@ -113,27 +113,55 @@ let mkSourceExprConditional isFromSource callExpr sourceMethInfo builderValName
...
+                    noInterceptF z e
+            valBindingSiteIntercept = fun z (_, v) -> addVal v z
+        }
+
+    let valsByName = FoldExpr folder NameMultiMap.empty expr
+
+    // If any Val with a name is referenced, mark all Vals with that name as referenced
+    for KeyValue(_, vals) in valsByName do
+        if vals |> List.exists _.HasBeenReferenced then
+            vals |> List.iter _.SetHasBeenReferenced()
```
Comment (auduchinok) [inline src/Compiler/Checking/Expressions/CheckComputationExpressions.fs]: If the shadowing issue actually exists, is the original value declaration range still available at this point? Would it be possible to use it instead of relying on the names to prevent marking extra values?

File: tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs [hunk 10]
```diff
@@ -2258,4 +2258,110 @@ but here has type
...
+    [<Fact>]
+    let ``Unused variable in select scope warns FS1182`` () =
+        FSharp """
+module Test
+
+let result = 
+    query { for x in [1;2;3] do
+            select (
+                let unused = 42
+                x) }
```
Comment (auduchinok) [inline tests/FSharp.Compiler.ComponentTests/Language/ComputationExpressionTests.fs]: Something like this could be useful to have to show how the shadowing works now:
```fsharp
query { for x in [1;2;3] do
        select (
            let x = 42
            x) }
```

```fsharp
query { for x in [1;2;3] do
        select (
            let x = x
            1) }
```

**Review by auduchinok — COMMENTED** [review]
@T-Gro The implementation looks good now! I'd only check how the shadowing works 🙂

File: src/Compiler/Checking/Expressions/CheckComputationExpressions.fs (hunk 9 above)
Comment (T-Gro) [reply src/Compiler/Checking/Expressions/CheckComputationExpressions.fs]: Trying that approach now, keying by original range instead of names, and detect unused even when shadowing is in place.

**Review by auduchinok — APPROVED** [review]
@T-Gro Great!

**Comment by Thorium** [comment]
Hmm, the users report that FSharp.Core 10.0.105 was working, but after 10.1.201 there has been weird behaviour with database queries using `query { .. }` starting to silently return wrong results instead of correct results.
This is due to the database tool having to adopt a new layer of AnonymousObj mappings in LINQ Select projections.

I know what to do, just wanted to highlight this breaking change between FSharp.Core versions.
