### PR TITLE
Fix #17719

### LINKED ISSUE #17719: `InvalidProgramException` on string interpolation
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Create a console project with this code

```fsharp
type Foo() =

    let sb = System.Text.StringBuilder()

    member _.Bar(s: System.ReadOnlySpan<char>) = sb.Append(s) |> ignore

let foo = Foo()
let foos = "foo"
foo.Bar($"{foos} is bar")
```

2. Build and run the project

**Expected behavior**

~~`InvalidProgramException`~~

**Actual behavior**

`InvalidProgramException`

**Known workarounds**

* Use let binding for interpolated string and use that in function call
* Use `string` instead of `ReadOnlySpan<char>`
* Do not use string interpolation

**Related information**

Provide any related information (optional):

* Windows 11
* .NET 9 RC1
* Version 17.12.0 Preview 2.0

### PR DESCRIPTION
**Pull request by vzarytovskii**
Fixes #17719

### CODE REVIEW

File: src/Compiler/Checking/Expressions/CheckExpressions.fs [hunk 1]
```diff
@@ -7530,9 +7530,9 @@ and TcInterpolatedStringExpr cenv (overallTy: OverallTy) env m tpenv (parts: Syn
             let concatenableExprs = if canLower then concatenable [] fillExprs parts else []
 
             match concatenableExprs with
-            | [p1; p2; p3; p4] -> mkStaticCall_String_Concat4 g m p1 p2 p3 p4, tpenv
-            | [p1; p2; p3] -> mkStaticCall_String_Concat3 g m p1 p2 p3, tpenv
-            | [p1; p2] -> mkStaticCall_String_Concat2 g m p1 p2, tpenv
+            | [p1; p2; p3; p4] -> TcPropagatingExprLeafThenConvert cenv overallTy g.string_ty env m (fun () -> mkStaticCall_String_Concat4 g m p1 p2 p3 p4, tpenv)
+            | [p1; p2; p3] -> TcPropagatingExprLeafThenConvert cenv overallTy g.string_ty env m (fun () -> mkStaticCall_String_Concat3 g m p1 p2 p3, tpenv)
+            | [p1; p2] -> TcPropagatingExprLeafThenConvert cenv overallTy g.string_ty env m (fun () -> mkStaticCall_String_Concat2 g m p1 p2, tpenv)
```
Comment (vzarytovskii) [inline src/Compiler/Checking/Expressions/CheckExpressions.fs:7535]: We can de-duplicate some other time.

**Review by abonie — APPROVED** [review]

**Comment by vzarytovskii** [comment]
If CI passes, I intend to force-merge it for it to go into main -> 17.12 merge and then into SDK, so we can have it in release.

File: tests/FSharp.Compiler.ComponentTests/EmittedIL/StringFormatAndInterpolation.fs [hunk 2]
```diff
@@ -88,4 +88,46 @@ IL_0014:  call       string [runtime]System.String::Concat(string,
...
+        let [<EntryPoint>] main _ =
+            let foo = Foo()
+            let foos = "foo"
+            foo.Bar($"{{foos}} is bar")
+            0
+                """
+
+        compilation |> compile |> shouldSucceed |> ignore
+
+        compilation |> asExe |> compileAndRun |> shouldSucceed |> ignore
```
Comment (T-Gro) [inline tests/FSharp.Compiler.ComponentTests/EmittedIL/StringFormatAndInterpolation.fs:113]: Why is this getting compiled three times?
Can be done just once, and then:
- run
- verify
The same compilation result

Comment (vzarytovskii) [reply tests/FSharp.Compiler.ComponentTests/EmittedIL/StringFormatAndInterpolation.fs:113]: I just decided to do independent compilations. It probably can. I don't want to change it now though, since I don't want to wait for another run and postpone release build for another hour or so.

**Review by KevinRansom — APPROVED** [review]

**Review by T-Gro — APPROVED** [review]
