### PR TITLE
Prefer nullable over other conversions

### LINKED ISSUE #14302: F# 6.0 -> 7.0: A unique overload for method could not be determined
Please provide a succinct description of the issue.

I had the following TorchSharp code working fine in F# 6.0:
```fsharp
let xs = torch.zeros([|10L|], dtype=torch.float32)
```
After upgrading to F# 7.0 the compiler started complaining:  
```
*A unique overload for method 'zeros' could not be determined based on type information prior to this program point. A type annotation may be needed.Known types of arguments: int64 array * dtype: torch.ScalarType * device: torch.Device * requiresGrad: bool

Candidates:
- torch.zeros(size: ReadOnlySpan<int64>, ?dtype: Nullable<torch.ScalarType>, ?device: torch.Device, ?requiresGrad: bool) : torch.Tensor 
- torch.zeros(size: ReadOnlySpan<int64>, ?dtype: Nullable<torch.ScalarType>, ?device: torch.Device, ?requiresGrad: bool) : torch.Tensor 
- torch.zeros(size: int64 array, ?dtype: Nullable<torch.ScalarType>, ?device: torch.Device, ?requiresGrad: bool) : torch.Tensor*
```

It does work in F# 7.0 if I change the code to:
```fsharp
let xs = torch.zeros([|10L|], ?dtype=Some torch.float32)
```
... but having to sprinkle this all over the code (in this way) is clumsy and hinders readability.

Yes, there's a workaround,  
but from a usability perspective, I'd call this a regression.

### PR DESCRIPTION
**Pull request by NinoFloris**
Prefer nullable over other conversions, fixes #14302

### CODE REVIEW

File: src/Compiler/Checking/ConstraintSolver.fs [hunk 1]
```diff
@@ -3225,7 +3225,11 @@ and GetMostApplicableOverload csenv ndeep candidates applicableMeths calledMethG
         if c <> 0 then c else
             
         // Prefer methods that need less type-directed conversion
-        let c = compare (match usesTDC1 with TypeDirectedConversionUsed.Yes(_, false) -> 1 | _ -> 0) (match usesTDC2 with TypeDirectedConversionUsed.Yes(_, false) -> 1 | _ -> 0)
+        let c = compare (match usesTDC1 with TypeDirectedConversionUsed.Yes(_, false, _) -> 1 | _ -> 0) (match usesTDC2 with TypeDirectedConversionUsed.Yes(_, false, _) -> 1 | _ -> 0)
+        if c <> 0 then c else
+
+        // Prefer methods that only have nullable type-directed conversions
+        let c = compare (match usesTDC1 with TypeDirectedConversionUsed.Yes(_, _, true) -> 1 | _ -> 0) (match usesTDC2 with TypeDirectedConversionUsed.Yes(_, _, true) -> 1 | _ -> 0)
```
Comment (dsyme) [inline src/Compiler/Checking/ConstraintSolver.fs:3232]: Looking at the ordering of these preference checks, and their global action across the overload, I'm concerned that they're too strong - preferring "methods that need less type-directed conversion" and "methods that only have nullable type-directed conversions" over all else in all situations, regardless of what else is happening (assuming there is some TDC in play in both overloads at all).   This would affect method overloads where there's some TDC, and some other things in play too.

For the original addition of the "no TDC" check that's reasonable, as we didn't want that feature to affect any existing overloading.  But I'm wondering whether these two further checks should go at the end of the preference list, or should be done argument by argument in `compareArg`

Comment (NinoFloris) [reply src/Compiler/Checking/ConstraintSolver.fs:3232]: That would be option 4 in #14302, because I agree, this is absolutely a kludge. It isn't really low risk to push such a refactor into a patch though.

**Review by T-Gro — APPROVED** [review]

File: src/Compiler/Checking/ConstraintSolver.fs (hunk 1 above)
Comment (T-Gro) [reply src/Compiler/Checking/ConstraintSolver.fs:3232]: @NinoFloris  : I would be for merging this PR as is now, and doing a bigger change later (after next VS update/release)

**Review by vzarytovskii — APPROVED** [review]

**Comment by vzarytovskii** [comment]
I will go ahead and pre-created a backport, so we can merge it faster if approved by Don

File: src/Compiler/Checking/ConstraintSolver.fs (hunk 1 above)
Comment (NinoFloris) [reply src/Compiler/Checking/ConstraintSolver.fs:3232]: To balance the situation a bit @dsyme, we are not making more overload sets ambiguous than we were doing in F# 6 (correct me if I'm wrong). Overload sets where per argument checks will start to resolve to some other overload seem uncommon as they require a high amount of caller participation (passing arguments in the right nullable/numeric mix, all needing various conversions).

Subsequently we should be able to move from whole signature to per argument later in 7.0 or 8.0 without changing any but the most theoretic overload resolutions, strictly expanding the set of overloads that will resolve without error.

Additionally, if a user encounters an overload set with a high average arity - and where the caller arguments are (almost) all subject to conversions - they always have the option to do as many conversions by hand as necessary to disambiguate. For any other overload ambiguity issues a user might be able to use a parameter name difference to disambiguate (if any exists) but beyond that has no other options. 

BC and risk wise this is a big difference, this PR can unblock the affected users and at the same time we don't realistically dig ourselves deeper into a BC hole.
