### PR TITLE
Caches: remove EntityPool, improve metrics, add eviction stress test

### LINKED ISSUE #18819: Tests: wierd compilation errors
Recently started showing up.
For example:
```
  Failed EmittedIL.Structure.ModuleArity01_fs(compilation: File: ModuleArity01.fs) [1 s]
  Error Message:
   System.Exception : Mismatch in Errors, expected '0', got '1'.
All errors:
[(Error 193, Line 136, Col 7, Line 136, Col 33, "Type constraint mismatch. The type 
    'Type'    
is not compatible with type
    'MemberInfo'    
")]
  Stack Trace:
     at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1448.Invoke(String message)
   at Microsoft.FSharp.Core.PrintfModule.gprintf[a,TState,TResidue,TResult,TPrinter](FSharpFunc`2 envf, PrintfFormat`4 format) in D:\a\_work\1\s\src\FSharp.Core\printf.fs:line 1398
   at FSharp.Test.CompilerAssertHelpers.assertErrors(Int32 libAdjust, Boolean ignoreWarnings, FSharpDiagnostic[] errors, Tuple`4[] expectedErrors) in D:\a\_work\1\s\tests\FSharp.Test.Utilities\CompilerAssert.fs:line 503
   at FSharp.Test.CompilerAssertHelpers.evaluateReferences@574.Invoke(Tuple`2 tupledArg) in D:\a\_work\1\s\tests\FSharp.Test.Utilities\CompilerAssert.fs:line 576
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\a\_work\1\s\src\FSharp.Core\local.fs:line 247
   at FSharp.Test.CompilerAssertHelpers.evaluateReferences(DirectoryInfo outputDir, Boolean ignoreWarnings, Compilation cmpl) in D:\a\_work\1\s\tests\FSharp.Test.Utilities\CompilerAssert.fs:line 573
   at FSharp.Test.CompilerAssertHelpers.compileCompilationAux(DirectoryInfo outputDirectory, Boolean ignoreWarnings, Compilation cmpl) in D:\a\_work\1\s\tests\FSharp.Test.Utilities\CompilerAssert.fs:line 534
   at FSharp.Test.Compiler.compileFSharpCompilation(Compilation compilation, Boolean ignoreWarnings, CompilationUnit cUnit) in D:\a\_work\1\s\tests\FSharp.Test.Utilities\Compiler.fs:line 828
   at FSharp.Test.Compiler.compileAndRun@1115.Invoke(CompilationUnit x)
   at EmittedIL.Structure.verifyExecution(CompilationUnit compilation) in D:\a\_work\1\s\tests\FSharp.Compiler.ComponentTests\EmittedIL\Structure\Structure.fs:line 31
   at EmittedIL.Structure.ModuleArity01_fs(CompilationHelper compilation) in D:\a\_work\1\s\tests\FSharp.Compiler.ComponentTests\EmittedIL\Structure\Structure.fs:line 182
```

Possibly it is because of reusing the checker while the same generated filename "test.fs" shows up in multiple tests?

### PR DESCRIPTION
**Pull request by majocha**
Edit: 

First of all, this fixes #18819 by removing `EntityPool` from Cache.
The problem manifested itself when executing `EmittedIL.Structure` tests in parallel.
It was reproducible locally. I checked locally that it's fixed by running many iterations ("run until failure" in VS) without fail.

Some additional checks and tests around eviction added around a singular possible eviction fail I noticed in the CI:
```
Data collector 'Blame' message: The specified inactivity time of 5 minutes has elapsed. Collecting hang dumps from testhost and its child processes.
Data collector 'Blame' message: Dumping 29900 - testhost.net472.
Results File: D:\a\_work\1\s\artifacts\TestResults\Release\FSharp.Compiler.ComponentTests_NETFramework472_batch2.xml
Test Run Aborted.
The active Test Run was aborted because the host process exited unexpectedly. Please inspect the call stack above, if available, to get more information about where the exception originated from.

The test running when the crash occurred: 
Passed!  - Failed:     0, Passed:   427, Skipped:    17, Total:   444, Duration: 3 m 19 s - FSharp.Compiler.ComponentTests.dll (net472)
Miscellaneous.FsharpSuiteMigrated_CoreTests.lift-FSI

Miscellaneous.FsharpSuiteMigrated_CoreTests.test int32-FSI
CompilerService.Caches.Eviction of least recently used
Language.NullableCSharpImport.TypeBuilder CreateTypeInfo with an upcast
```

This could mean that the test that waits for eviction event never gets that event in some rare circumstances.
So, this adds another diagnostic event `EvictionFail`. If it ever happens (again?), it should show up in CI.

A basic stress test is added. I also cleaned up `CacheMetrics` code a bit.

Another thing: depending on the dotnet test's `--blame-hang-timeout` instead of using explicit timeouts in the tests. This sounds good in theory. In practice, if the testhost timeouts while executing tests in parallel, the only info we get is a bunch of tests that were executing at the moment. A pragmatic solution would probably be:

```fsharp
#if DEBUG
let shouldNeverTimeout = 15_000
#else
// accomodate unpredictable CI thread scheduling
let shouldNeverTimeout = 200_000
#endif
```

### CODE REVIEW

**Comment by majocha** [comment]
That's weird, `Delegates01_fs(compilation: File: Delegates01.fs)` on MacOS: 
image

File: src/Compiler/Checking/TypeRelations.fs [hunk 1]
```diff
@@ -101,20 +101,6 @@ let TypesFeasiblyEquiv ndeep g amap m ty1 ty2 =
 let TypesFeasiblyEquivStripMeasures g amap m ty1 ty2 =
     TypesFeasiblyEquivalent true 0 g amap m ty1 ty2
 
-let inline TryGetCachedTypeSubsumption (g: TcGlobals) (amap: ImportMap) key =
```
Comment (majocha) [inline src/Compiler/Checking/TypeRelations.fs:104]: This is just refactored.

File: src/Compiler/Utilities/Caches.fs [hunk 2]
```diff
@@ -47,112 +48,80 @@ type CachedEntity<'Key, 'Value> =
...
+                updateRatio ())
 
-    static member RemoveInstrumentation(cacheId) =
-        observedCaches[cacheId].Dispose()
-        observedCaches.TryRemove(cacheId) |> ignore
+        listener.Start()
 
-// Creates and after reclaiming holds entities for reuse.
-// More than totalCapacity can be created, but it will hold for reuse at most totalCapacity.
-type EntityPool<'Key, 'Value>(totalCapacity, cacheId) =
```
Comment (majocha) [inline src/Compiler/Utilities/Caches.fs:141]: Pooling is just removed for now. If there is impact on allocations, we can think how to do it correctly. It should be governed in full by the mailbox queue, probably, to avoid races.

**Review by T-Gro — APPROVED** [review]
Thanks @majocha for finding the mistake which caused tests randomly to fail!

The race was within the pool usage?

**Comment by majocha** [comment]
> The race was within the pool usage?

Yes, see https://github.com/dotnet/fsharp/issues/18819#issuecomment-3159833337

I tried disabling the pool and it fixed things. Then went through the file with copilot, some diagnosis was misguided but it did catch it and explain what's going on.
