### PR TITLE
Error for partial implementation of interface with static and non static abstract members

### LINKED ISSUE #17138: No compile-time error for partial implementation of interface with static abstract members
There is no compile-time error if a type only partially implements an interface with static abstract members (IWSAM). If you try to use the partial implementation, a `System.TypeLoadException` is raised at runtime.

**Repro steps**

```fsharp
#nowarn "3535"

type IFace =
    static abstract P1 : int
    static abstract P2 : int

type T =
    interface IFace with
        static member P1 = 1

let inline p1<'T & #IFace> = 'T.P1

p1<T>
```

Runtime error:

```stderr
Unhandled exception. System.TypeLoadException: Virtual static method 'get_P2' is not implemented on type 'T' from assembly 'ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at <StartupCode$ConsoleApp1>.$Program.main@()
```

**Expected behavior**

There should be a compile-time error indicating that all abstract methods on the interface must be implemented.

**Actual behavior**

There is no compile-time error; there is an error at runtime instead.

**Known workarounds**

N/A

**Related information**

.NET 8/9 preview.

### PR DESCRIPTION
**Pull request by edgarfgp**
## Description

Fixes #17138

## Checklist

- [x] Test cases added
- [x] Release notes entry updated

### CODE REVIEW

File: src/Compiler/Checking/MethodOverrides.fs [hunk 1]
```diff
@@ -380,8 +380,7 @@ module DispatchSlotChecking =
                     let compiledSig = CompiledSigOfMeth g amap m dispatchSlot
                     
                     let noimpl() =
-                        if dispatchSlot.IsInstance then
-                            missingOverloadImplementation.Add((isReqdTyInterface, lazy NicePrint.stringOfMethInfo infoReader m denv dispatchSlot))
+                        missingOverloadImplementation.Add((isReqdTyInterface, lazy NicePrint.stringOfMethInfo infoReader m denv dispatchSlot))
```
Comment (vzarytovskii) [inline src/Compiler/Checking/MethodOverrides.fs:383]: It should probably account for object expression:
If it's object expression, then only check for instance ones
If it's just normal inheritance, then check all.

Comment (edgarfgp) [reply src/Compiler/Checking/MethodOverrides.fs:383]: @vzarytovskii 

We currently only show an error for: 
`Object expressions cannot implement interfaces with static abstract members or declare static members.`

But personally I think it should be more correct to also show that `static abstract member Execute: string -> unit` has not been implemented. As that is what you expect from a "type" implementing an interface ? 

```fsharp
type ILogger =
    abstract member Log: string -> unit
    static abstract member Execute: string -> unit
        
let consoleLogger =
    { new ILogger with
        member this.Log(message: string) =
            printfn "%s" message
    }
    
consoleLogger.Log("Hello World")
```

Comment (edgarfgp) [reply src/Compiler/Checking/MethodOverrides.fs:383]: Even if the user will implement the `static abstract member` `Error 3860` will still be there.

Comment (vzarytovskii) [reply src/Compiler/Checking/MethodOverrides.fs:383]: What I meant is that if you just remove the condition, then if you try to use object expression with both static and instance abstract methods, you will get 

No implementation was given for 'static abstract ...'.

For it. Which is wrong, because you can't implement static abstracts in object expressions.

Comment (edgarfgp) [reply src/Compiler/Checking/MethodOverrides.fs:383]: Done

**Review by T-Gro — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]

**Comment by edgarfgp** [comment]
👍
