### PR TITLE
Fix AttributeUsage.AllowMultiple not inherited for C#-defined attributes

### LINKED ISSUE #17107: AttributeUsage.AllowMultiple is not inherited for attributes defined (subclassed) in C#
Seems related to #9256.

C# attribute definitions:

```c#
[AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
public class BaseAttribute : Attribute;

public class ChildAttribute : BaseAttribute;
```

This works fine in C#, i.e., the following compiles:

```c#
[Child]
[Child]
public class Foo;
```

However, the following F# code does not:

```f#
[<Child>]
[<Child>]
type Foo() = class end
```

This fails on the second `[<Child>]` line with FS0429:

> Error FS0429 : The attribute type 'ChildAttribute' has 'AllowMultiple=false'. Multiple instances of this attribute cannot be attached to a single language element.

If `ChildAttribute` is defined in F# instead, it works.

A simple, but of course suboptimal workaround is to subclass the desired (already subclassed) attribute and set the correct `AttributeUsage` on it.

### PR DESCRIPTION
**Pull request by edgarfgp**
## Description

The F# compiler was not walking the inheritance chain for IL-imported (C#) attribute types when checking AllowMultiple. The `supersOfTyconRef` function only used `tcaug_super`, which is not populated for IL types.

This fix parameterizes `TryFindAttributeUsageAttribute` with a getSuper resolver function. The caller in PostInferenceChecks now passes a resolver using GetSuperTypeOfType, which correctly handles both F# and IL-imported types via ILTypeDef.Extends.

Fixes #17107

## Checklist

- [x] Test cases added
- [x] Release notes entry updated

### CODE REVIEW

**Comment by edgarfgp** [comment]
This is ready!

File: src/Compiler/TypedTree/TypedTreeOps.fs [hunk 1]
```diff
@@ -3514,12 +3514,12 @@ let superOfTycon (g: TcGlobals) (tycon: Tycon) =
     | None -> g.obj_ty_noNulls 
     | Some ty -> ty 
 
-/// walk a TyconRef's inheritance tree, yielding any parent types as an array
-let supersOfTyconRef (tcref: TyconRef) =
+/// Walk a TyconRef's inheritance tree using the provided super-type resolver, yielding parent types as an array.
```
Comment (T-Gro) [inline src/Compiler/TypedTree/TypedTreeOps.fs]: Is this effectively
https://github.com/dotnet/fsharp/blob/f089f3e4de98396f9e9234faec9be2528ef04ae6/src/Compiler/Checking/TypeHierarchy.fsi#L83

?

File: src/Compiler/Checking/PostInferenceChecks.fs [hunk 2]
```diff
@@ -2037,7 +2037,16 @@ and CheckAttribs cenv env (attribs: Attribs) =
...
+        |> List.filter (fun (tcref, _, m) ->
+            let getSuper (tcref: TyconRef) =
+                let ty = generalizedTyconRef cenv.g tcref
+                match GetSuperTypeOfType cenv.g cenv.amap m ty with
+                | Some superTy ->
+                    match tryTcrefOfAppTy cenv.g superTy with
+                    | ValueSome sup -> Some sup
+                    | ValueNone -> None
+                | None -> None
+            TryFindAttributeUsageAttribute cenv.g m getSuper tcref <> Some true)
```
Comment (T-Gro) [inline src/Compiler/Checking/PostInferenceChecks.fs]: This is the only caller of TryFindAttributeUsageAttribute?

The indirection by passing "getSuper" (which exists elsewhere, TypeHieararchy module has logic for this) seems artificial induced - is it because file ordering and/or required dependencies?

( `amap` likely?)

**Review by T-Gro — APPROVED** [review]
This is good now, thanks for the fix!

**Comment by edgarfgp** [comment]
@T-Gro this is ready!!

**Comment by edgarfgp** [comment]
@T-Gro Closing this PR. I do not have much time to keep fixing merge conflicts . Feel free to pick the changes if needed. Thanks

**Comment by T-Gro** [comment]
@edgarfgp , ok, let me try resolving them 👍
