### PR TITLE
Fix race in graph checking of type extensions

### LINKED ISSUE #19033: Benign race condition in graph based type checking of type extensions but breaks determinism
This is a race condition in a very specific scenario when we have two or more type extensions of the same type in two independent (from graph checking pov) files:

https://github.com/dotnet/fsharp/blob/12efe3b5121d8a662d1431763796dfd278af9129/src/Compiler/Checking/CheckDeclarations.fs#L4219-L4228

If each extension updates the type var name, we have a race during parallel checking. In effect some of the extensions will end up with a randomly wrong typar name.

This happens when compiling FCS.dll using graph based type checking because `LexBuffer<_>` has such multiple independent extensions: https://github.com/dotnet/fsharp/pull/19028#issuecomment-3442351177

**Repro steps**

[SetIdentRace repo](https://github.com/majocha/SetIdentRace) or 

[SetIdentRace.zip](https://github.com/user-attachments/files/23172706/SetIdentRace.zip)

`dotnet build --no-incremental` a few times.

observe the dumped sigdata or inspect dll:

correct with sequential checking:

Image

wrong with graph based (`Print<'X>` instead of `Print<'U>`):
Image

This is not very severe and rather an edge case, apart from the fact that it prevents graph based type checking from being deterministic.

### PR DESCRIPTION
**Pull request by majocha**
## Description

Fixes #19033

By saving the declared type argument name instead of mutating (possibly concurrently) the source typar.

## Checklist

- [x] Test cases added
- [x] Release notes entry updated:

### CODE REVIEW

**Comment by majocha** [comment]
To unblock #19028

**Comment by nojaf** [comment]
It has been too long since I understood all this, so could you high-level explain to me why this works? 

Does signature conformance happen after the parallel phase?

**Comment by majocha** [comment]
> It has been too long since I understood all this, so could you high-level explain to me why this works?
> 
> Does signature conformance happen after the parallel phase?

No, it seems it just does SetIdent in the opposite direction sig -> impl. Or extended type -> extensions. :) So what is being mutated is naturally isolated by graph checking.

This seems the only place this happens so we can save the declared ident here.

**Comment by nojaf** [comment]
Thanks, this is a clever solution. Well done!

File: src/Compiler/TypedTree/TypedTree.fs [hunk 1]
```diff
@@ -2364,7 +2367,7 @@ type Typar =
         | [], Some { typar_il_name = None; typar_xmldoc = doc; typar_constraints = []; typar_is_contravariant = false } when doc.IsEmpty ->
```
Comment (T-Gro) [inline src/Compiler/TypedTree/TypedTree.fs]:
```suggestion
        | [], Some { typar_il_name = None; typar_xmldoc = doc; typar_constraints = []; typar_is_contravariant = false; typar_declared_name = None } when doc.IsEmpty ->
```

File: src/Compiler/TypedTree/TypedTree.fs [hunk 2]
```diff
@@ -2394,14 +2410,14 @@ type Typar =
         | [], Some { typar_il_name = None; typar_xmldoc = doc; typar_attribs = [];typar_is_contravariant = false } when doc.IsEmpty ->
```
Comment (T-Gro) [inline src/Compiler/TypedTree/TypedTree.fs]:
```suggestion
        | [], Some { typar_il_name = None; typar_xmldoc = doc; typar_attribs = [];typar_is_contravariant = false; typar_declared_name = None } when doc.IsEmpty ->
```

File: tests/FSharp.Test.Utilities/Compiler.fs [hunk 3]
```diff
@@ -1367,6 +1370,7 @@ Actual:
                 match ILChecker.verifyILAndReturnActual [] p expected with
                 | true, _, _ -> result
                 | false, errorMsg, _actualIL ->
+                    //printfn $"{actualIL}"
```
Comment (T-Gro) [inline tests/FSharp.Test.Utilities/Compiler.fs]:
```suggestion
```

File: src/Compiler/TypedTree/TypedTree.fs [hunk 4]
```diff
@@ -2260,6 +2260,9 @@ type TyparOptionalData =
 
       /// Set to true if the typar is contravariant, i.e. declared as <in T> in C#
       mutable typar_is_contravariant: bool
+
+      /// The declared name of the type parameter.
+      mutable typar_declared_name: string option
```
Comment (T-Gro) [inline src/Compiler/TypedTree/TypedTree.fs:2265]: How does it make its way into the generated IL ?

File: tests/FSharp.Compiler.ComponentTests/Signatures/TypeTests.fs [hunk 5]
```diff
@@ -308,4 +308,38 @@ let foo = Foo()
...
             Assert.False(mfv.IsUnionCaseTester, "IsUnionCaseTester returned true")
             Assert.True(mfv.IsConstructor)
-        | _ -> failwith "Expected FSharpMemberOrFunctionOrValue"
\ No newline at end of file
+        | _ -> failwith "Expected FSharpMemberOrFunctionOrValue"
+
+
+
+[<Fact>]
+let ``Type extension type parameters do not overwrite the type being extended`` () =
```
Comment (T-Gro) [inline tests/FSharp.Compiler.ComponentTests/Signatures/TypeTests.fs:316]: It would be good to also have a test which covers the addition to SignatureConformance.

Comment (majocha) [reply tests/FSharp.Compiler.ComponentTests/Signatures/TypeTests.fs:316]: Pretty much the existing signature printing TypeTests cover it now.

File: src/Compiler/TypedTree/TypedTree.fs (hunk 4 above)
Comment (majocha) [reply src/Compiler/TypedTree/TypedTree.fs:2265]: It does not, that's the point :) 

The original issue was https://github.com/dotnet/fsharp/issues/15286 and the original fix for it was to overwrite the incoming typar idents with the ones from extensions (#15287) . This PR kind of reverts to standard behavior in this regard, so the IL for type extensions contains the type parameters of the extended type.

File: tests/FSharp.Compiler.ComponentTests/Signatures/TypeTests.fs (hunk 5 above)
Comment (majocha) [reply tests/FSharp.Compiler.ComponentTests/Signatures/TypeTests.fs:316]: I added also an explicit test for this.
