### PR TITLE
Fix 13926 - Disallow using base to invoke an abstract base method. 

### LINKED ISSUE #13926: BadImageFormatException : Bad IL format when using `base`
Using `base.XXX` to call a base method causes a `BadImageFormatException` to be raised.

**Repro steps**

The following code (requires Giraffe and FsUnit to run the test) throws a `BadImageFormatException`

```
namespace Test

open Giraffe
open Xunit
open FsUnit.Xunit

open System.Text.Json
open System.Text.Json.Serialization

type StringTrimJsonSerializer(o: JsonSerializerOptions) =
    inherit JsonConverter<string>()

    override this.Read(reader, _, _) =
        match reader.TokenType with
        | JsonTokenType.String -> reader.GetString().Trim(): string
        | _ -> JsonException("Type is not a string") |> raise

    /// This causes a BadImageFormatException
    override this.Write(writer, objectToWrite, options) = base.Write(writer, objectToWrite, options)


module SerializationTests =

    type SomeType = { Amount: decimal; Currency: string }

    let serialize item =
        let options = SystemTextJson.Serializer.DefaultOptions
        StringTrimJsonSerializer options |> options.Converters.Add
        JsonSerializer.Serialize(item, options)

    let deserialize<'T> (stringValue: string) =
        let options = SystemTextJson.Serializer.DefaultOptions
        StringTrimJsonSerializer options |> options.Converters.Add
        JsonSerializer.Deserialize<'T>(stringValue, options)

    [<Fact>]
    let ``Roundtip type should trim currency whitespace`` () =
        { Amount = 42.99M; Currency = "  USD   " }
        |> serialize
        |> deserialize<SomeType>
        |> should equal { Amount = 42.99M; Currency = "USD" }
```

### Expected behavior

Should call the base method.

### Actual behavior

Throws:

> BadImageFormatException : Bad IL format.

### Known workarounds

Don't use `base` in a derived method.

### Related information

On dotnet 6, using `System.Text.Json` serialization BCL classes, Windows 10/11.

### PR DESCRIPTION
**Pull request by KevinRansom**
Fixes #13926

### CODE REVIEW

**Review by edgarfgp — APPROVED** [review]

File: src/Compiler/AbstractIL/il.fs [hunk 1]
```diff
@@ -1910,6 +1910,8 @@ type ILMethodDef
         metadataIndex: int32
     ) =
 
+    let _x = ()
+
```
Comment (T-Gro) [inline src/Compiler/AbstractIL/il.fs:1914]:
```suggestion
```

File: src/Compiler/FSharp.Compiler.Service.fsproj [hunk 2]
```diff
@@ -21,6 +21,7 @@
     <OtherFlags>$(OtherFlags) --warnon:3218</OtherFlags>
     <!-- 3390: xmlDocBadlyFormed -->
     <OtherFlags>$(OtherFlags) --warnon:3390</OtherFlags>
+    <!--<OtherFlags>$(OtherFlags) - - allsigs</OtherFlags>-->
```
Comment (T-Gro) [inline src/Compiler/FSharp.Compiler.Service.fsproj:24]:
```suggestion
```

**Review by T-Gro — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]
