### PR TITLE
Fix accessibility and type-matching for generic extension method lookups

### LINKED ISSUE #19349: Unexpected type inference for Run method - generic constraints are checked too late
**Repro steps**
```fsharp
open System.Runtime.CompilerServices

// -------------------------
// "View engine" bits
// -------------------------
type HtmlContainer() = class end

type HtmlContainerFun = HtmlContainer -> unit

[<Extension>]
type HtmlContainerExtensions =
    [<Extension>]
    static member inline Run(this: #HtmlContainer, [<InlineIfLambda>] runExpr: HtmlContainerFun) =
        runExpr this
        this

// -------------------------
// "AsyncSeq-like" CE builder bits
// -------------------------
type AsyncSeq<'T> = private AsyncSeq of 'T list

type AsyncSeqBuilder() =
    member _.Yield(x: 'T) : AsyncSeq<'T> =
        AsyncSeq [x]

let asyncSeq = AsyncSeqBuilder()

let xs : AsyncSeq<int> =
    asyncSeq {
        yield 1
    }
```
From Don's comment:
>This could be onsidered an F# compiler bug but we'd have to check the spec - the compiler commits to using this Run before it knows the constraint check #HtmlContainer will fail.

**Expected behavior**

Code compiles just fine - `Run` method from `HtmlContainerExtensions` isn't used for asyncSeq

**Actual behavior**

error FS0193: The type 'AsyncSeqBuilder' is not compatible with the type 'HtmlContainer'

**Known workarounds**

No workarounds are known

**Related information**

Related issues:
https://github.com/Lanayx/Oxpecker/issues/93
https://github.com/fsprojects/FSharp.Control.AsyncSeq/issues/239

.NET SDK 10.0.102

### PR DESCRIPTION
**Pull request by evgTSV**
Fixes #19349

-> Fix accessibility and type-matching for pattern-based extension lookups (CE, Dispose, etc.)

## Summary

This PR fixes an issue where pattern-based extension method lookups (specifically for Computation Expressions and use bindings) would incorrectly resolve methods that are either inaccessible (private/internal) or belong to incompatible types.

## Problem

Previously, the compiler's name resolution for CE-specific methods (like Bind, Delay, Run, etc.) and the Dispose pattern for resource cleanup was overly optimistic. It often bypassed accessibility checks, leading to incorrect method resolution or even compilation of calls to private extension methods from outside their scope.

## Checklist

- [x] Test cases added
- [x] Release notes entry updated:

### CODE REVIEW

**Comment by evgTSV** [comment]
It seems that my changes broke FSharp.Core. I suppose that we have to adjust type equality check to work with the core code.

File: src/Compiler/Checking/NameResolution.fs [hunk 1]
```diff
@@ -754,7 +760,27 @@ let AllMethInfosOfTypeInScope collectionSettings infoReader nenv optFilter ad fi
     if collectionSettings = ResultCollectionSettings.AtMostOneResult && not (isNil intrinsic) then 
         intrinsic
     else
-        intrinsic @ ExtensionMethInfosOfTypeInScope collectionSettings infoReader nenv optFilter LookupIsInstance.Ambivalent m ty
+        intrinsic @ ExtensionMethInfosOfTypeInScope collectionSettings infoReader nenv ad optFilter LookupIsInstance.Ambivalent m ty
+
+let IsExtensionMethCompatibleWithTy g amap m (ty: TType) (minfo: MethInfo) =
```
Comment (auduchinok) [inline src/Compiler/Checking/NameResolution.fs]: I'm wondering how is it already done in other cases? Is there a place that this function could be unified with?

File: src/Compiler/Checking/NameResolution.fs [hunk 2]
```diff
@@ -754,7 +760,27 @@ let AllMethInfosOfTypeInScope collectionSettings infoReader nenv optFilter ad fi
...
+        let ty1 = thisTy |> stripTyEqns g
+        let ty2 = ty |> stripTyEqns g
+
+        match ty1, ty2 with
+        | TType_var (tp1, _), _ ->
+            tp1.Constraints |> List.exists (function
+                | TyparConstraint.CoercesTo(targetCTy, _) ->
+                    let cTy = targetCTy |> stripTyEqns g
+                    TypeRelations.TypeFeasiblySubsumesType 0 g amap m cTy TypeRelations.CanCoerce ty2
+                | _ -> false)
```
Comment (T-Gro) [inline src/Compiler/Checking/NameResolution.fs]: [Breaking Changes] When `ty1` is a `TType_var` with no `CoercesTo` constraint, `List.exists` returns `false` and the extension method is silently excluded. This incorrectly filters out:

- C# extensions like `public static T Run<T>(this T x)` (unconstrained generic `this`)
- F# extensions like `static member Run(this: 'T)` with non-CoercesTo constraints (e.g. `'T : struct`)
- Any extension where the `this` parameter is a type variable constrained only by member/struct/equality constraints

An unconstrained (or non-CoercesTo-constrained) type variable should match any target type. Consider:

```fsharp
| TType_var (tp1, _), _ ->
    let coercesToConstraints =
        tp1.Constraints |> List.choose (function
            | TyparConstraint.CoercesTo(targetCTy, _) -> Some targetCTy
            | _ -> None)
    match coercesToConstraints with
    | [] -> true  // No CoercesTo constraint means it could match anything
    | constraints ->
        constraints |> List.exists (fun targetCTy ->
            let cTy = targetCTy |> stripTyEqns g
            TypeRelations.TypeFeasiblySubsumesType 0 g amap m cTy TypeRelations.CanCoerce ty2)
```

File: tests/FSharp.Compiler.ComponentTests/Conformance/Expressions/ComputationExpressions/CEExtensionMethodCapture.fs [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+        let asyncSeq = AsyncSeqBuilder()
+
+        let xs : AsyncSeq<int> =
+            asyncSeq {
+                yield 1
+            }
+    """
+    |> asExe
+    |> compile
+    |> shouldFail
```
Comment (T-Gro) [inline tests/FSharp.Compiler.ComponentTests/Conformance/Expressions/ComputationExpressions/CEExtensionMethodCapture.fs:136]: [Test Coverage] The existing tests all use `#SomeType` (which produces a `CoercesTo` constraint). Please add a test for a C# or F# extension with a truly unconstrained generic `this` parameter, e.g.:

```fsharp
[<Extension>]
type GenericExtensions =
    [<Extension>]
    static member inline Run(this: 'T) = this
```

This would currently fail due to the `TType_var` / no-CoercesTo bug noted above.

**Review by T-Gro — COMMENTED** [review]
> :warning: **Automated Copilot Review** — AI-assisted initial review. Feedback welcome.

**[Breaking Changes]** `IsExtensionMethCompatibleWithTy` has a logic gap in the `TType_var` branch: when the extension method's `this` parameter is a type variable with **no** `CoercesTo` constraint (unconstrained generic, or constrained only by struct/member/equality), the current code returns `false` and the method is silently excluded. This affects C# extensions like `public static T Run<T>(this T x)` and F# extensions with `(this: 'T)` or `(this: 'T when 'T : struct)`. A type variable with no CoercesTo bounds should match any target type — the `[] -> true` fallback is missing.

**[Test Coverage]** All CE extension method tests use `#SomeType` (which always has a `CoercesTo` constraint). A test with a genuinely unconstrained `'T` on the `this` parameter would catch the above bug.

File: src/Compiler/Checking/NameResolution.fs (hunk 1 above)
Comment (evgTSV) [reply src/Compiler/Checking/NameResolution.fs]: It seems that each method, which uses `TryFindIntrinsicOrExtensionMethInfo`, has its own internal checking. Therefore, I suppose we shoud leave this function in order to make a checking in the common place. This function can help to filter obsiously unsuitable methods in advance.

**Review by T-Gro — APPROVED** [review]
