### PR TITLE
Error message that explicitly disallows static abstract members in classes.

### LINKED ISSUE #17044: Static abstract method on class or abstract class yields internal error
Declaring a static abstract method on an abstract class fails with an internal error that does not surface in the tooling (VS or Ionide).

**Repro steps**

1. Define a static abstract member in an abstract class.
2. The tooling shows no errors, but attempting to build yields an internal error.

```fsharp
#nowarn "3535"

[<AbstractClass>]
type A () =
    static abstract M : unit -> unit

type B () =
    inherit A ()
    static member M () = printfn "99"

B.M ()
```

```stderr
error FS0193: internal error: Unable to load one or more of the requested types.
Virtual Static Method.
Virtual Static Method.
```

A similar error happens for regular classes:

```fsharp
#nowarn "3535"

type A () =
    static abstract M : unit -> unit
```

```
error FS0193: internal error: Unable to load one or more of the requested types.
Abstract method in non-abstract class.
```

**Expected behavior**

I would expect an error message that explicitly disallowed static abstract methods in classes and abstract classes. I would also expect this message to show in the IDE.

**Actual behavior**

An internal error is raised in the compiler, and no error message is shown in the IDE.

**Known workarounds**

N/A.

**Related information**

This happens on current `main` (and probably earlier versions).

### PR DESCRIPTION
**Pull request by edgarfgp**
## Description

Fixes #17044

## Before
`error FS0193: internal error: Unable to load one or more of the requested types.
Virtual Static Method.
Virtual Static Method.`

### After
`(Error 3867, Line 6, Col 21, Line 6, Col 22, "Static abstract members are not allowed on abstract classes.")`

## Checklist

- [x] Test cases added
- [x] Release notes entry updated
- [x] RFC

### CODE REVIEW

**Comment by edgarfgp** [comment]
RFC PR https://github.com/fsharp/fslang-design/pull/768

File: src/Compiler/Checking/CheckDeclarations.fs [hunk 1]
```diff
@@ -3681,6 +3681,12 @@ module EstablishTypeDefinitionCores =
                                   
                                   for slot in slots do 
                                       yield mkLocalValRef slot ]
+                            
+                        if hasAbstractAttr then
```
Comment (brianrourkeboll) [inline src/Compiler/Checking/CheckDeclarations.fs:3685]: Hmm. I guess #17044 should really have been about classes in general. This also yields an internal error:

```fsharp
#nowarn "3535"

type A () =
    static abstract M : unit -> unit
```

```
error FS0193: internal error: Unable to load one or more of the requested types.
Abstract method in non-abstract class.
```

I guess we don't really need to check for structs, since they already give an error for _any_ abstract members, static or not.

Comment (edgarfgp) [reply src/Compiler/Checking/CheckDeclarations.fs]: Yeah make sense.

**Review by vzarytovskii — APPROVED** [review]
Nice, thanks!

**Review by psfinaki — APPROVED** [review]
This was quick, thanks!
