### PR TITLE
Remove time exec from root build scripts

### LINKED ISSUE #19209: Fsharp's build scripts don't return a non zero exit code when there's a failure
I believe there is an issue in eng/build.ps1 and potentially also eng/build.sh that causes the exit code to be zero, even when there's a failure. Example screenshot:

Image

Console log:
> C:\git\dotnet\src\fsharp\build.cmd -pack -publish -noVisualStudio  -productBuild -fromVMR -configuration Release -verbosity minimal /p:TargetRid=win-x64 /p:DotNetPackageVersionPropsPath=C:\git\dotnet\artifacts\obj\PackageVersions\PackageVersions.fsharp.props /p:SourceBuiltAssetsDir=C:\git\dotnet\artifacts\assets\Release\ /p:SourceBuiltAssetManifestsDir=C:\git\dotnet\artifacts\obj\manifests\Release\fsharp\ /p:RepositoryName=fsharp /p:RepositoryUrl=https://github.com/dotnet/dotnet -msbuildEngine dotnet /p:TargetArchitecture=x64 /p:TargetOS=windows /p:SourceBuiltShippingPackagesDir=C:\git\dotnet\artifacts\packages\Release\Shipping\fsharp\ /p:SourceBuiltNonShippingPackagesDir=C:\git\dotnet\artifacts\packages\Release\NonShipping\fsharp /p:SourceBuiltPdbArtifactsDir=C:\git\dotnet\artifacts\SymStore\Release\fsharp /p:SourceBuiltArtifactsBasePath=C:\git\dotnet /p:UsingToolMicrosoftNetCompilers=false /p:PortableBuild=true /p:PortableTargetRid=win-x64 /p:RepoOriginalSourceRevisionId=95d597122c8ace890da82c59f2433433325a1b13  -bl /p:GenerateResourceUsePreserializedResources=true > C:\git\dotnet\artifacts\log\Release\fsharp\fsharp.log 2>&1

```
TryDownloadDotnetFrameworkSdk -- Test-IsAdmin = 'False'
Processing C:\git\dotnet\src\fsharp\global.json
perl.exe already exists; replacing...
Native tools are available from  C:\Users\vihofer\.netcoreeng\native\bin
##vso[task.prependpath]C:\Users\vihofer\.netcoreeng\native\bin
variable:NativeToolsOnMachine = unset or false
Path = C:\Users\vihofer\.netcoreeng\native\bin\perl\5.38.2.2\perl\bin\perl.exe
Building bootstrap 'net10.0' compiler with 'net10.0' .NET Core product TFM
C:\git\dotnet\.dotnet\dotnet.exe publish "C:\git\dotnet\src\fsharp\proto.proj" -c Proto /bl:"C:\git\dotnet\src\fsharp\artifacts\log\Release\bootstrap.binlog"

  Determining projects to restore...
  Restored C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj (in 12.7 sec).
  Restored C:\git\dotnet\src\fsharp\buildtools\fslex\fslex.fsproj (in 1.09 min).
  Determining projects to restore...
  Restored C:\git\dotnet\src\fsharp\buildtools\fsyacc\fsyacc.fsproj (in 179 ms).
  1 of 2 projects are up-to-date for restore.
  Determining projects to restore...
  Restored C:\git\dotnet\src\fsharp\buildtools\AssemblyCheck\AssemblyCheck.fsproj (in 43 ms).
  1 of 2 projects are up-to-date for restore.
  Determining projects to restore...
  Restored C:\git\dotnet\src\fsharp\src\FSharp.Build\FSharp.Build.fsproj (in 4.07 sec).
  Restored C:\git\dotnet\src\fsharp\src\FSharp.DependencyManager.Nuget\FSharp.DependencyManager.Nuget.fsproj (in 5.52 sec).
  Restored C:\git\dotnet\src\fsharp\src\Compiler\FSharp.Compiler.Service.fsproj (in 5.53 sec).
  Restored C:\git\dotnet\src\fsharp\src\fsc\fscProject\fsc.fsproj (in 8.5 sec).
  1 of 5 projects are up-to-date for restore.
  Determining projects to restore...
  Restored C:\git\dotnet\src\fsharp\src\FSharp.Compiler.Interactive.Settings\FSharp.Compiler.Interactive.Settings.fsproj (in 456 ms).
  Restored C:\git\dotnet\src\fsharp\src\fsi\fsiProject\fsi.fsproj (in 459 ms).
  3 of 5 projects are up-to-date for restore.
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fsi(1750,18): error FS0010: Unexpected keyword 'or' in value signature [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fsi(1750,17): error FS1244: Attempted to parse this as an operator name, but failed [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(650,18): error FS0010: Unexpected keyword 'or' in pattern. Expected ')' or other token. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(650,17): error FS0583: Unmatched '(' [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(727,40): error FS0010: Unexpected keyword 'or' in expression [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(727,17): error FS0589: Incomplete conditional. Expected 'if <expr> then <expr>' or 'if <expr> then <expr> else <expr>'. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(729,17): error FS0010: Unexpected keyword 'else' in binding. Expected incomplete structured construct at or before this point or other token. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(726,13): error FS3118: Incomplete value or function definition. If this is in an expression, the body of the expression must be indented to the same column as the 'let' keyword. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(734,13): error FS0010: Incomplete structured construct at or before this point in implementation file. Expected incomplete structured construct at or before this point or other token. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(921,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(934,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(938,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(943,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(946,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1068,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1075,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1079,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1139,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1213,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1228,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1247,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1250,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1253,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1262,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1306,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1314,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1323,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1332,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1342,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1351,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1392,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1412,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1432,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1452,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1479,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1494,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1509,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1525,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1541,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1556,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1573,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1612,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1672,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1860,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1867,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1876,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1890,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1923,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1948,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1976,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1989,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(1996,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2002,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2008,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2011,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2038,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2058,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2075,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2093,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2105,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2119,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2135,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2153,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2164,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2176,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2189,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2203,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2215,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2229,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2245,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2392,9): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2758,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(2764,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(5265,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(5286,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(5307,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(5328,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(5349,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
C:\git\dotnet\src\fsharp\src\FSharp.Core\prim-types.fs(5370,13): warning FS3520: XML comment is not placed on a valid language element. [C:\git\dotnet\src\fsharp\src\FSharp.Core\FSharp.Core.fsproj::TargetFramework=netstandard2.0]
Command failed to execute with exit code 1: C:\git\dotnet\.dotnet\dotnet.exe publish "C:\git\dotnet\src\fsharp\proto.proj" -c Proto /bl:"C:\git\dotnet\src\fsharp\artifacts\log\Release\bootstrap.binlog"
System.Management.Automation.RuntimeException: Command failed to execute with exit code 1: C:\git\dotnet\.dotnet\dotnet.exe publish "C:\git\dotnet\src\fsharp\proto.proj" -c Proto /bl:"C:\git\dotnet\src\fsharp\artifacts\log\Release\bootstrap.binlog"
at Exec-CommandCore, C:\git\dotnet\src\fsharp\eng\build-utils.ps1: line 51
at Exec-Console, C:\git\dotnet\src\fsharp\eng\build-utils.ps1: line 120
at Make-BootstrapBuild, C:\git\dotnet\src\fsharp\eng\build-utils.ps1: line 252
at <ScriptBlock>, C:\git\dotnet\src\fsharp\eng\build.ps1: line 562
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1
Failure building bootstrap compiler

TotalMinutes TotalSeconds
------------ ------------
 2.896840205  173.8104123
```

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/fsharp/issues/19209

## Description

Fixes # (issue, if applicable)

## Checklist

- [ ] Test cases added
- [ ] Performance benchmarks added in case of performance changes
- [ ] Release notes entry updated:
    > Please make sure to add an entry with short succinct description of the change as well as link to this pull request to the respective release notes file, if applicable.
    >
    > Release notes files:
    > - If anything under `src/Compiler` has been changed, please make sure to make an entry in `docs/release-notes/.FSharp.Compiler.Service/<version>.md`, where `<version>` is usually "highest" one, e.g. `42.8.200`
    > - If language feature was added (i.e. `LanguageFeatures.fsi` was changed), please add it to `docs/release-notes/.Language/preview.md`
    > - If a change to `FSharp.Core` was made, please make sure to edit `docs/release-notes/.FSharp.Core/<version>.md` where version is "highest" one, e.g. `8.0.200`.

    > Information about the release notes entries format can be found in the [documentation](https://fsharp.github.io/fsharp-compiler-docs/release-notes/About.html).
    > Example:
    > * More inlines for Result module. ([PR #16106](https://github.com/dotnet/fsharp/pull/16106))
    > * Correctly handle assembly imports with public key token of 0 length. ([Issue #16359](https://github.com/dotnet/fsharp/issues/16359), [PR #16363](https://github.com/dotnet/fsharp/pull/16363))
    > *`while!` ([Language suggestion #1038](https://github.com/fsharp/fslang-suggestions/issues/1038), [PR #14238](https://github.com/dotnet/fsharp/pull/14238))

    > **If you believe that release notes are not necessary for this PR, please add `NO_RELEASE_NOTES` label to the pull request.**

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@mmitche FYI, that fixes the exit code=0 when there's a failure in fsharp building inside the VMR

**Review by T-Gro — APPROVED** [review]

File: build.sh [hunk 1]
```diff
@@ -13,4 +13,4 @@ while [[ -h $source ]]; do
 done
 
 scriptroot="$( cd -P "$( dirname "$source" )" && pwd )"
-time "$scriptroot/eng/build.sh" --build --restore "$@"
+"$scriptroot/eng/build.sh" --restore --build $@
```
Comment (omajid) [inline build.sh:16]: This removes the double quotes around `$@`, which I don't think was intentional. It breaks when any arguments have spaces in them, such as:

```
./build.sh /p:OfficialBuilder="Red Hat"
```
