### PR TITLE
Fix ctrl - c handling on the coreclr

### LINKED ISSUE #7277: dotnet fsi complaining about missing Mono.Posix assembly
**Repro steps**

In Ubuntu 18.04 LTS when I download the latest nightly build:

```
wget -q https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-linux-x64.tar.gz -O nightly.tgz && 
mkdir -p nightly && 
tar xfz nightly.tgz -C nightly && 
nightly/dotnet fsi
```
When quitting the REPL I get the following error message:
```
Microsoft (R) F# Interactive version 10.6.0.0 for F# 4.7
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #q;;
Failed to install ctrl-c handler - Ctrl-C handling will not be available. Error was:
        Could not load file or assembly 'Mono.Posix, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'. The system cannot find the file specified.
```
* Operating system
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
````

This may or may not be a bug, the official .deb 3.0 prerelease does not exhibit this behaviour. @cartermp indicated that this is happening because of [this line](https://github.com/dotnet/fsharp/blob/14be76788d84639b8ed11bfcaf3c36d741e4902c/src/fsharp/fsi/fsi.fs#L1455).

### PR DESCRIPTION
**Pull request by KevinRansom**
The desktop and mono builds of F# had some crazy complex pinvoke ctrl-c handling code.  That code didn't work at all on the coreclr, and was #ifdefed out.

However, recently we updated the build to netstandard 2.0 … a side effect of that, is what stopped #ifdefing out the crazy stuff.

Anyway this PR, removes some of the crazy pinvoke stuff and replaces it with the the .NET Console ctrl-c handler, which is sweet … smooth and easy to chew, also it is the same on all platforms.

Fixes #7277

### CODE REVIEW

File: src/fsharp/fsi/fsi.fs [hunk 1]
```diff
@@ -787,14 +787,12 @@ type internal FsiCommandLineOptions(fsi: FsiEvaluationSessionHostConfig, argv: s
     member __.Gui = gui
 
 /// Set the current ui culture for the current thread.
-#if FX_LCIDFROMCODEPAGE
```
Comment (cartermp) [inline src/fsharp/fsi/fsi.fs]: is this define used anywhere else?

Comment (KevinRansom) [reply src/fsharp/fsi/fsi.fs]: Yes: https://github.com/dotnet/fsharp/blob/e55650818551825cd387169af3353484ed9ba73a/src/fsharp/fsi/fsimain.fs#L43
https://github.com/dotnet/fsharp/blob/b651877c763cce9474d55f1b72caa69425dbfe94/src/fsharp/fsc.fs#L1778

It can probably be cleared up, but that is not relevant to this PR.

File: src/fsharp/fsi/fsi.fs [hunk 2]
```diff
@@ -1366,149 +1360,74 @@ type internal FsiInterruptControllerKillerThreadRequest =
...
-              exitViaKillThread <- false  
-#endif
 
+        let fsiInterruptHandler (args:ConsoleCancelEventArgs) =
+            args.Cancel <- true
+            ctrlEventHandlers |> List.iter(fun handler -> handler.Invoke(CTRL_C) |> ignore)
+
+        do Console.CancelKeyPress.Add(fsiInterruptHandler)
+
+        // WINDOWS TECHNIQUE: .NET has more safe points, and you can do more when a safe point.
```
Comment (cartermp) [inline src/fsharp/fsi/fsi.fs]: Is the following code also going to run on non-Windows? What are the ramifications of that?

Comment (KevinRansom) [reply src/fsharp/fsi/fsi.fs]: Yes it does and I even tested it on a mac … crazily :-)

the coreclr implements the .NET abstraction Console.CancelKeyPress event handler on all platforms, this eliminates the need for all of the pinvoke, and mono.posix.dll load nonsense, and instead uses the really ... really simple CancelKeyPress handler instead.

I kept the what happens inside the handler from the previous code, to ensure that I wasn't missing some subtle behaviour.  Although at some point we should spend a few days, understanding if we need all of the killthread stuff.

In order for you to better understand the change it is essentially:

1.  Eliminate all of the non windows code paths, because, they primarily involve mechanisms for wiring up the control-c handler.
2.  For the windows code path replace the pinvoke wire-up for ctrl-c handling, with a mechanism bassed on Console.CancelKeyPress.
3  Use the above on all platforms.

Simplifys the code a lot, and removes all of the platform distinctive code.

Kevin

**Comment by seva0stapenko** [comment]
Apparently those fixes didn't make it into .NET 3.0 release:

The issue can be observed with the released .NET SDK 3.0 on OSX 10.14.6

```
$ dotnet --list-sdks
2.2.300 [/usr/local/share/dotnet/sdk]
3.0.100 [/usr/local/share/dotnet/sdk]
$ dotnet --version
3.0.100
$ uname -a    
Darwin MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
$ dotnet fsi

Microsoft (R) F# Interactive version 10.6.0.0 for F# 4.7
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> Failed to install ctrl-c handler - Ctrl-C handling will not be available. Error was:
	Could not load file or assembly 'Mono.Posix, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'. The system cannot find the file specified.

- 
- ;;
> 
```
