### PR TITLE
Bugfix for DotLambda - (a, (b, c))  was incorrectly detected as a discard (a compiler generated one was there)

### LINKED ISSUE #16276: Unexpected ambiguity warning for DotLambda
**Repro steps**

```fsharp
let f (a, (b, c)) = _.ToString()
```

image

Reproducible in the latest main

### PR DESCRIPTION
**Pull request by T-Gro**
Fixes #16276 .

This change makes sure that only real "_" discards produce a warning.
Hidden compiler-generated discards that cover a different construct (e.g. a discard for a tuple which is not reference as a whole) are not going to produce a warning for ambiguity.

**At the same time, this also changes the warning to be an optional one.**

### CODE REVIEW

File: src/Compiler/Checking/CheckExpressions.fs [hunk 1]
```diff
@@ -5585,9 +5585,13 @@ and TcExprUndelayed (cenv: cenv) (overallTy: OverallTy) env tpenv (synExpr: SynE
         CallExprHasTypeSink cenv.tcSink (m, env.NameEnv, overallTy.Commit, env.AccessRights)
         TcConstExpr cenv overallTy env m tpenv synConst
     | SynExpr.DotLambda (synExpr, m, trivia) ->
-        if env.NameEnv.eUnqualifiedItems |> Map.containsKey "_arg1"
-        then
+        match env.NameEnv.eUnqualifiedItems |> Map.tryFind "_arg1" with        
+        // Compiler-generated _arg items can have more forms, the real underscore will be 1-character wide
+        | Some (Item.Value(valRef)) when valRef.Range.StartColumn+1 = valRef.Range.EndColumn ->
```
Comment (auduchinok) [inline src/Compiler/Checking/CheckExpressions.fs:5590]: This check looks a bit error-prone to me. Can there be a better check like `IsCompilerGenerated` or a field indicating that the value is created from a unnamed/discard pattern?

**Comment by auduchinok** [comment]
I wonder what is the rationale to disallow these lambdas in some of these cases? For example, these cases are allowed (correct me if I'm wrong):
```fsharp
let getP = 
    let _ = () // this `_` is definitely in scope but is ignored
    [""] |> List.map _.Length
```
```fsharp
let getP x : (string -> int) = 
    match x with
    | null -> failwith ""
    | _ -> _.Length // this is allowed, despite the another `_` in the scope
```
```fsharp
type T() =
    member _.M() =
        [""] |> List.map _.Length
```

At the same time, this is not allowed (and significantly limits the possible usages of the language feature):
```fsharp
let f a b _ =

  // many lines of (nested) code

  let x =

    // many lines of code

    xs |> Seq.map _.P // not allowed because of `_` somewhere else above (i.e. in `f`)
```

I think it should be consistent: we should either allow it disallow it everywhere where `_` pattern is present, or allow it. Given how ubiquitous `_` is in F#, I think there's no reason to disallow it in _some_ of the common scenarios.

File: src/Compiler/Checking/CheckExpressions.fs (hunk 1 above)
Comment (T-Gro) [reply src/Compiler/Checking/CheckExpressions.fs:5590]: All of the use cases, both positive and negative, are marked as IsCompilerGenerated. I assume this is because when you type a `fun _`, the underscore gets translated to `_arg1`, and because of this translation it is also marked as being compiler generated.
I have spent quite some time trying to find attributes which differentiate the two uses, but did not find any what so ever.

There is no field I found that would separate the "hidden" discards and a user written discard, except for when looking at the source code (or transitively deriving that from the range).


Since this is only a warning, I do not believe this would justify adding a brand new field to all values...

**Comment by T-Gro** [comment]
> I wonder what is the rationale to disallow these lambdas in some of the cases? For example, these cases are allowed:

Important: This is just a warning hinting that readers of the code might think the code is doing something with "the other underscore".
The code still works and runs as a lambda.

It is not a hard error.

**Comment by auduchinok** [comment]
> Important: This is just a warning hinting that readers of the code might think the code is doing something with "the other underscore".

That's an important note, I agree. However, a lot of people use settings like `WarnAsError`, and a lot of people prefer having no warnings in their code. It's also important for analyzers and various editor features to not produce code that would have warnings where there were none prior to the changes. I think from the language design standpoint it would be better if all these cases were either disallowed or no warnings were produced.

**Comment by T-Gro** [comment]
TBH I have no problem with changing that warning into being an optional one.

@vzarytovskii : Can we change an existing warning into optional one after net8 has been released?

**Comment by vzarytovskii** [comment]
> TBH I have no problem with changing that warning into being an optional one.
> 
> @vzarytovskii : Can we change an existing warning into optional one after net8 has been released?

We can, since it shouldn't break any existing code.

**Review by auduchinok — APPROVED** [review]

**Review by 0101 — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]
