### PR TITLE
Fixes #10621

### LINKED ISSUE #10621: Inconsistency between nameof and normal method invocation when unused generic type parameter is concerned
Consider the following:

```fsharp
type A<'a>() =
    static member P = ()

// Succeeds; no warning, no error
A<_>.P

// Error
nameof A<_>.P |> ignore
```

I cannot take a name of `P` despite being able to call it without issue.

Note that if I remove the type argument, I get this warning:

> The instantiation of the generic type 'A' is missing and can't be inferred from the arguments or return type of this member. Consider providing a type instantiation when accessing this type, e.g. 'A<_>'.

Which is obviously incorrect.

Is the `nameof` behavior by design @dsyme?

### PR DESCRIPTION
**Pull request by ettud**
Looks like deleting this one line is fine. From history it is not clear to me why it was added. I was thinking about writing some more complicated checks (`| Item.Types _ when ... -> true`) but I could not think of cases when we have Item.Types and cannot use the nameof.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=13556) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=13556) before we can accept your contribution.<br/><br/>:x: ettud [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=13556)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=13556) it.</sub>

File: src/Compiler/Checking/CheckExpressions.fs [hunk 1]
```diff
@@ -8052,7 +8052,6 @@ and TcNameOfExpr cenv env tpenv (synArg: SynExpr) =
                 | Result (_, item, _, _, _ as res)
                     when
                          (match item with
-                          | Item.Types _
```
Comment (vzarytovskii) [inline src/Compiler/Checking/CheckExpressions.fs:8055]: Above, it says
> // However we don't commit for a type names - nameof allows 'naked' type names and thus all type name
>// resolutions are checked separately in the next step.

So, probably should be handled in `resolvedToTypeName ` instead?

**Review by KevinRansom — APPROVED** [review]
Thanks for this.

Kevin

**Review by dsyme — APPROVED** [review]
