### PR TITLE
Type subsumption cache: handle unsolved type vars

### LINKED ISSUE #19037: F# 10 - Class hierarchy employing CRGP now produces compile error FS0193
A certain code pattern utilizing CRGP (*[Curiously Recurring Generic Pattern](https://blog.stephencleary.com/2022/09/modern-csharp-techniques-1-curiously-recurring-generic-pattern.html)*) which successfully compiles under the F# 9 compiler no longer compiles under the F# 10 compiler.

In the real scenario, I encountered this with a type hierarchy implementing `IEquatable<'T>`.

**Repro steps**

1. Create an F# library project. Paste the following into `Library.fs`:

```fsharp
module MyModule

type IFoo<'T when 'T :> IFoo<'T>> =
    abstract member Bar: other:'T -> unit

[<AbstractClass>]
type FooBase() =
    
    interface IFoo<FooBase> with
        member this.Bar (other: FooBase) = ()

[<Sealed>]
type FooDerived<'T>() =
    inherit FooBase()
    
    interface IFoo<FooDerived<'T>> with
        member this.Bar other = ()

type IFooContainer<'T> =
    abstract member Foo: FooDerived<'T>

let inline bar<'a when 'a :> IFoo<'a>> (x: 'a) (y: 'a) = x.Bar y
let inline takeSame<'a> (x: 'a) (y: 'a) = ()

// Successfully compiles under .NET 9 + F# 9
// Error under .NET 10 + F# 10: Program.fs(26,13): Error FS0193 : The type 'FooDerived<'TId>' does not match the type 'FooBase'
let callBar_NewlyBroken (foo1: IFooContainer<'TId>) (foo2: IFooContainer<'TId>) =
    bar foo1.Foo foo2.Foo
    
// Successfully compiles under both versions
let callBar (foo1: IFooContainer<'TId>) (foo2: IFooContainer<'TId>) =
    let id1 = foo1.Foo
    let id2 = foo2.Foo
    bar id1 id2
```

2. Target .NET 9 in project and `global.json` (I tested under .NET SDK 9.0.111 + F# Compiler version 12.9.100.0 for F# 9.0)
3. Run `dotnet build`
4. Observe that the project builds successfully
5. Change target in project and `global.json` to latest .NET 10 preview (at the time of writing .NET SDK 10.0.100-rc.2.25502.107 + F# Compiler version 14.0.100.0 for F# 10.0)
6. Run `dotnet build`
7. Observe F# compile error: `Error FS0193 : The type 'FooDerived<'TId>' does not match the type 'FooBase'`

**Expected behavior**

Project should compile successfully

**Actual behavior**

The F# compiler produces an error: `Error FS0193 : The type 'FooDerived<'TId>' does not match the type 'FooBase'`

**Known workarounds**

Provide additional annotations, or introduce additional variable bindings to get type inference to succeed.

**Related information**

Provide any related information (optional):

* Operating system
* .NET SDK 10.0.100-rc.2.25502.107
* F# Compiler version 12.9.100.0 for F# 9.0
* Editing Tools (e.g. Visual Studio Version, Visual Studio)

### PR DESCRIPTION
**Pull request by majocha**
## Description

Fixes #19037

Added repro test case.

The problem was in memoization of `TType` -> `TypeStructure` generation.
`TType` is inherently mutable. One `TType` instance can result in different `TypeFeasiblySubsumesType` outcomes and different `TypeStructure` key fragments, as type arguments get solved.  For the purpose of type subsumption caching, we can treat as stable only fully solved types, with solved or rigid type vars. We still want the cache to use the unstable ones, but we must produce new `TypeStructures` from the `TTypes` as they evolve towards a solution.

Additionally, caching is now limited only to `TType_app` cases.

Note: 

Cache keys do not take into account constraints. This seems to work in practice, because `TypeFeasiblySubsumesType`, where the cache is applied, does not use them either.

If this turns out to be a problem, or we ever need to use `TypeStructures` also somewhere else, we should emit a structural fingerprint of `Typar.Constraints`, too.

### CODE REVIEW

**Comment by majocha** [comment]
Yet another bug. This needs a careful look.

I need to run some benchmarks again, too and compare standalone builds with the original Vlad's implementation.

**Comment by T-Gro** [comment]
@majocha:
If we separated the solved and unsolved form of a typar, why wouldn't we want to cache (type subsumption especially) for both?
.e.g. constraints might be already there and the cache would hold info on type subsumption of generic typars.

It would equally help if two typars are both unsolved, but strip down to the same form.


Wasn't the mistake more the fact that solved/unsolved form of the same TType_var had always the same key (based on Stamp) ?




This is definitely a safe fix, but I wonder if it doesn't too much limit the potential of the cache for typars.

**Comment by majocha** [comment]
> Wasn't the mistake more the fact that solved/unsolved form of the same TType_var had always the same key (based on Stamp) ?

Yes, that makes sense. It makes me wonder if we could also handle unsolved nullness better.

**Comment by T-Gro** [comment]
Nullness is not stamped, so in the case of unresolved/not yet resolved/ nullness, there is no identifier to hold onto.
The identity of the `NullnessVar` (possibly the leaf one if multiple are sequentially linked) object itself (via https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimehelpers.gethashcode?view=net-9.0 )

**Comment by majocha** [comment]
Yeah I need to rethink this seriously. I totally missed the actual cause of the bug. This fix works accidentally.
The problem seems to be here:
https://github.com/dotnet/fsharp/blob/9670f600f7aab99d4b4fe95c41ed83e3e008c489/src/Compiler/Utilities/TypeHashing.fs#L480

The optimization was supposed to speed up things by caching already constructed TypeStructures but it is causing problems that I need to pinpoint.

**Comment by majocha** [comment]
This fix is accidental, the real problem is here:
https://github.com/dotnet/fsharp/blob/9670f600f7aab99d4b4fe95c41ed83e3e008c489/src/Compiler/Utilities/TypeHashing.fs#L480
This was intended to speed up things by weakly attaching the computed `TypeStructures` to their respective `TTypes`. We cannot do it for not fully solved types, they still mutate and things get outdated.

**Comment by majocha** [comment]
> Wasn't the mistake more the fact that solved/unsolved form of the same TType_var had always the same key (based on Stamp) ?

Yes, in fact in case of typars we don't want the stamp as identity at all. We should use the structure of the solution (TType) if available or a common token for unsolved.

File: src/Compiler/Utilities/TypeHashing.fs [hunk 1]
```diff
@@ -441,40 +438,55 @@ module StructuralUtilities =
...
 
     // If the sequence got too long, just drop it, we could be dealing with an infinite type.
-    let private toTypeStructure tokens =
-        let tokens = tokens |> Seq.truncate 256 |> Array.ofSeq
+    let private toTypeStructure (tokens: TypeToken seq) =
+        let tokens = tokens |> Seq.truncate 256 |> Seq.toArray
 
-        if tokens.Length = 256 then
-            PossiblyInfinite NeverEqual.Singleton
+        if Seq.length tokens = 256 then
```
Comment (brianrourkeboll) [inline src/Compiler/Utilities/TypeHashing.fs]: Nit:
```suggestion
        if Array.length tokens = 256 then
```

**Comment by majocha** [comment]
I'm testing this in the IDE with the notorious OpenTK 5.0. It improved things significantly, there are way less cache entries now but much more hits, resulting in 99% ratio with little memory use and no constant churn during edits:
```
|             Cache name              | hit-ratio | adds | updates |  hits   | misses | 
|-------------------------------------|-----------|------|---------|---------|--------|
| typeSubsumptionCache                |    99.94% | 2752 |       0 | 4618992 |   2752 |
```

File: src/Compiler/Utilities/TypeHashing.fs [hunk 2]
```diff
@@ -441,40 +438,55 @@ module StructuralUtilities =
...
 
                 yield! accumulateTType tau
+
             | TType_fun(d, r, n) ->
                 yield! accumulateTType d
                 yield! accumulateTType r
                 toNullnessToken n
+
             | TType_var(r, n) ->
-                TypeToken.Stamp r.Stamp
```
Comment (T-Gro) [inline src/Compiler/Utilities/TypeHashing.fs:471]: Now that the stamp is gone, I feel we are missing something to differentiate constraints.

Most likely types where constraints matter will be unsolved, so this will bypass the cache (via `shouldCache`=false) anyway. Right now cannot come up with a specific example of solved types where also constraints would matter for subsumption.

File: src/Compiler/Utilities/TypeHashing.fs [hunk 3]
```diff
@@ -425,7 +415,14 @@ module StructuralUtilities =
                 TypeToken.MeasureRational(GetNumerator r, GetDenominator r)
         }
 
-    let rec private accumulateTType (ty: TType) =
+    let rec private accumulateTypar (typar: Typar) =
+        seq {
+            match typar.Solution with
+            | Some ty -> yield! accumulateTType ty
```
Comment (T-Gro) [inline src/Compiler/Utilities/TypeHashing.fs]: In general, the input going into the cache is already stripped, right?

i.e. we should not be getting long chains of solution pointers for something which is solved.

File: src/Compiler/Utilities/TypeHashing.fs (hunk 2 above)
Comment (majocha) [reply src/Compiler/Utilities/TypeHashing.fs:471]: `shouldCache` here only affects the memoization of `TType -> TypeStructure`, it will not prevent the caching of `checkSubsumes` result for unsolved.

Yeah this is missing constraints. I feel encoding them could cause this to explode in size.
What I completely missed also is the notion of rigidity. As I understand not all variables end up solved.

File: src/Compiler/Utilities/TypeHashing.fs (hunk 3 above)
Comment (majocha) [reply src/Compiler/Utilities/TypeHashing.fs]: Yeah since this is operating solely on stripped types, if we encounter a type var, it should never be a solved one. In theory.

**Comment by majocha** [comment]
The huge mistake that causes a lot of inefficiency was emitting typar stamps as part of the cache key. This causes a lot of equivalent but really unusable keys polluting the cache. The increased churn is especially heavy on the IDE. I cannot see a solution to this, that would guarantee soundness.

**Comment by T-Gro** [comment]
> The huge mistake that causes a lot of inefficiency was emitting typar stamps as part of the cache key. This causes a lot of equivalent but really unusable keys polluting the cache. The increased churn is especially heavy on the IDE. I cannot see a solution to this, that would guarantee soundness.


What about skipping cache for them?
For unsolved typars, the typefeasiblysubsubsumestypes is a quick decision in case of TType_var anyway.

Of course it somewhat limits the genericity of the cache, and is special-tailored to the place of application.

The typesubsumption was really needed for concrete types, with super types and interface hierarchies.
Maybe if Ttype_var is not part of it (after stripping), we can have both correctness and good cache contents?


I was thinking of content-based hashing, but you would need to hash all type constraints content-wise as they are mutable as well. Maybe the inherent mutation for solutions and constraints of a type var are good enough reasons to treat them differently?
(mutation is not well suited for cache keys)

**Comment by majocha** [comment]
So, basically, we care only about caching `TType_app _` pairs.
But most of them have type vars. Often still unsolved when they end up in the `checkSubsumes` call, just like in the test here.
I tried to not cache the types with unsolved vars but the results are abysmal, looking at OpenTK 5.0 project as baseline build times go from 10 sec to forever.

I wonder if the constraints are really a problem wrt to type subsumption cache. Because the current situation where we emit only a stamp as typar identity worked so far ( the bug this PR tries to fix is elsewhere). A given typar can very well have its constraints mutated while the stamp stays constant, so it is already not collision free in general. It just does not collide in practice for this usage. I think it was like this since the original Vlad's implementation.

Copilot when asked says:

**Q: which typar constraints can influence the result of TypeFeasiblySubsumesType? I wonder because I need to know what should take part in keying the TypeSubsumptionCache.**
> 
> A: Short answer: none of the typar constraints affect TypeFeasiblySubsumesType.
> Details:
> •	In TypeFeasiblySubsumesType, if either side is a type variable (TType_var), the function immediately returns true and does not consult the variable’s constraints.
> •	For nominal types (TType_app) with the same tycon, it delegates to TypesFeasiblyEquiv for each type argument. TypesFeasiblyEquiv also returns true when it encounters a TType_var (and ignores its constraints), and treats measure types as feasibly equivalent without comparing the actual measures.
> •	For tuples/anon/funs, it uses TypesFeasiblyEquiv similarly, so constraints are again ignored.
> •	The remaining branches follow nominal inheritance and interface chains of the concrete right-hand type. This depends on the type definitions/instantiations (and ultimately on metadata reachable via g/amap), not on typar constraint sets.
> Implications for the cache key:
> •	You do not need to include any typar constraint environment in the TypeSubsumptionCache key.
> •	The existing key of stripped nominal type structures (when both sides are TType_app) plus CanCoerce is correct. This aligns with how the algorithm makes decisions.
> •	The cache is already partitioned per TcGlobals via the weak map, so differences in loaded metadata are naturally isolated.


hmm.

File: src/Compiler/Utilities/TypeHashing.fs [hunk 4]
```diff
@@ -380,110 +377,154 @@ module HashTastMemberOrVals =
...
-                toNullnessToken n
-            | TType_measure m -> yield! accumulateMeasure m
+                emitNullness env n
+
+                let typarId =
+                    match env.typarMap.TryGetValue r.Stamp with
+                    | true, idx -> idx
+                    | _ ->
+                        let idx = env.typarMap.Count
+                        env.typarMap.[r.Stamp] <- idx
```
Comment (T-Gro) [inline src/Compiler/Utilities/TypeHashing.fs:491]: So you are sequentially remapping all encountered (within a single Ttype_app) stamps into a hole-free sequence 0..n.

Which should boost hash stability for type applications that are structurally the same (also with repetitions when it comes to depply nested applications), but are differently stamped?

Comment (majocha) [reply src/Compiler/Utilities/TypeHashing.fs:491]: Yeah, this gives huge performance boost. Copilot likes to use big words when it sees F# code, it says this is "alpha-normalization of type variables using de Bruijn-style indexing" 😄

File: src/Compiler/Utilities/TypeHashing.fs [hunk 5]
```diff
@@ -380,110 +377,154 @@ module HashTastMemberOrVals =
...
+
+        let env =
+            {
+                typarMap = System.Collections.Generic.Dictionary<Stamp, int>()
+                stable = true
+            }
+
+        let tokens =
+            emitTType env ty
+            |> Seq.filter (fun t -> t <> TypeToken.Nullness NullnessInfo.WithoutNull)
```
Comment (T-Gro) [inline src/Compiler/Utilities/TypeHashing.fs]: You might as well solve it at emission time (i.e. not emit a nullness token at all into the sequence), or?

File: src/Compiler/Utilities/TypeHashing.fs [hunk 6]
```diff
@@ -380,110 +377,154 @@ module HashTastMemberOrVals =
...
+                        idx
+
+                match r.Solution with
+                | Some ty -> yield! emitTType env ty
+                | None ->
+                    if r.Rigidity = TyparRigidity.Rigid then
+                        TypeToken.Rigid typarId
+                    else
+                        env.stable <- false
+                        TypeToken.Unsolved typarId
```
Comment (T-Gro) [inline src/Compiler/Utilities/TypeHashing.fs:503]: A basic checklist, please check each:

- [ ] Infinity chains of typars are handled (by laziness and truncation)
- [ ] Solve typar's hash is equal to its solution's hash (after nullness token filtering)
- [ ] Solved typar's hash is **not** equal to unsolved typar's hash with the same stamp
- [ ] Unsolved typar's are never weakly cached on the reference itself (solved by boolean flag to reference caching)
- [ ] This is never called in parallel for the same input ttype (since the context access it not thread-safe)
- [ ] The cache is kept small by caching only top-level Ttype_app and their contents are normalized and stamp-independent
- [ ] The weak cache still makes sense, it just is not used whenever an unsolved typar is encountered. But for all other scenarios, it can avoid the `getTypeStructureOfStrippedType` call.

File: src/Compiler/Utilities/TypeHashing.fs [hunk 7]
```diff
@@ -380,110 +377,154 @@ module HashTastMemberOrVals =
...
+    type private EmitContext =
+        {
+            typarMap: System.Collections.Generic.Dictionary<Stamp, int>
+            mutable stable: bool
+        }
 
-    let inline toNullnessToken (n: Nullness) =
+    let private emitNullness env (n: Nullness) =
         match n.TryEvaluate() with
         | ValueSome k -> TypeToken.Nullness k
```
Comment (T-Gro) [inline src/Compiler/Utilities/TypeHashing.fs]: The `trace` based mutation+rollback might be a problem for the weakcache, see e.g. here https://github.com/dotnet/fsharp/blob/3828c87efb134a8b541671361fd1411428da0b0c/src/Compiler/Checking/ConstraintSolver.fs#L1045-L1050 .

Or another one here:
https://github.com/dotnet/fsharp/blob/3828c87efb134a8b541671361fd1411428da0b0c/src/Compiler/Checking/ConstraintSolver.fs#L961 


The typestructure has this covered, but weakcache has not.
But fully clearing the weakcache when a trace's undo is called is way too defensive and would likely sacrifice a lot of perf potential :-(

File: src/Compiler/Utilities/TypeHashing.fs (hunk 6 above)
Comment (majocha) [reply src/Compiler/Utilities/TypeHashing.fs:503]: > A basic checklist, please check each:
> 
> * [x]  Infinity chains of typars are handled (by laziness and truncation)
> * [x]  Solved typar's hash is equal to its solution's hash (after nullness token filtering)
> * [x]  Solved typar's hash is **not** equal to unsolved typar's hash with the same stamp
> * [x]  Unsolved typar's are never weakly cached on the reference itself (solved by boolean flag to reference caching)
> * [x]  This is never called in parallel for the same input ttype (since the context access it not thread-safe)
> * [x]  The cache is kept small by caching only top-level Ttype_app and their contents are normalized and stamp-independent

> * [ ]  The weak cache still makes sense, it just is not used whenever an unsolved typar is encountered. But for all other scenarios, it can avoid the `getTypeStructureOfStrippedType` call.

This one I am not entirely sure. I'm trying to informally test by building FCS net10.0 and also OpenTK 5.0, both of which have quite different profiles of cache use, OpenTK now does not benefit from weak memoization. I left it in with the editor use in mind, but now that the cache works only on TType_apps, I wonder if it still helps.

File: src/Compiler/Utilities/TypeHashing.fs [hunk 8]
```diff
@@ -380,110 +377,154 @@ module HashTastMemberOrVals =
...
+            |> Seq.toArray
+
+        // If the sequence got too long, just drop it, we could be dealing with an infinite type.
+        if tokens.Length = 256 then PossiblyInfinite
+        elif not env.stable then Unstable tokens
+        else Stable tokens
+
+    let tryGetTypeStructureOfStrippedType ty =
+        // Speed up repeated calls by memoizing results for types that yield a stable structure.
+        let memoize =
```
Comment (majocha) [inline src/Compiler/Utilities/TypeHashing.fs]: Oops. Isn't this called every time now, creating a new table each time?

File: src/Compiler/Utilities/TypeHashing.fs (hunk 7 above)
Comment (majocha) [reply src/Compiler/Utilities/TypeHashing.fs]: I think the weakcache is not as crucial now, when we limit only to TType_app. Is nullness taken into account for `TypeFeasiblySubsumesType`? Maybe it's possible to not emit it at all.
(In the long run type structure generation could be made more configurable if needed, too.)

**Comment by majocha** [comment]
I quickly asked copilot:

**Q: Does TypeFeasiblySubsumesType take nullness into account ?** 

A:

Short answer: No. The predicate is intentionally nullness-agnostic.
Why:
•	In the core match it compares constructed types as TType_app (tc1, l1, _), TType_app (tc2, l2, _) and discards the third field (_), which is where the nullness marker lives. Only tycon equality and argument feasibility are checked via TypesFeasiblyEquiv, which likewise ignores nullness.
•	The special-case for object uses isObjTyAnyNullness g ty1, i.e., any nullness of obj is accepted as a supertype of any reference type, again ignoring nullness compatibility.
•	Supertype/interface traversal (GetSuperTypeOfType, GetImmediateInterfacesOfType) calls back into TypeFeasiblySubsumesType without reconciling nullness.
Related:
•	FindUniqueFeasibleSupertype preserves the nullness of ty2 in the result (addNullnessToTy n2 t), but the feasibility test itself still uses TypeFeasiblySubsumesType and thus ignores nullness.
•	ChooseTyparSolution may add nullness due to constraints, but that’s orthogonal to the subsumption check.
If you need a nullness-aware check, compare nullnessOfTy g ty1 and nullnessOfTy g ty2 explicitly alongside calling TypeFeasiblySubsumesType.

File: src/Compiler/Utilities/TypeHashing.fs (hunk 7 above)
Comment (majocha) [reply src/Compiler/Utilities/TypeHashing.fs]: Ah, this happens not just for nullness.

Comment (T-Gro) [reply src/Compiler/Utilities/TypeHashing.fs]: Yes, happens for typar solutions - e.g. method overloading, also in context of picking SRTP overloads.

If we are in a `Trace` environment within constraint solving, it would be safest to never add things to the WeakCache.

(alternatively add it there, but then remove at `Undo` - but there might be overhead in keeping track what to remove, I guess safer not to add...)

Comment (majocha) [reply src/Compiler/Utilities/TypeHashing.fs]: Yes, as first approximation we can just not memoize when any typars come into play, solved or not. Good thing the performance is still way better than before.

**Comment by majocha** [comment]
As usual I'm testing this in the IDE. I see way less cache churn now and good hit ratio. For example after some minutes of copilot work in this solution:

|                Cache name                | hit-ratio |  adds  | updates |  hits  | misses | evictions | eviction-fails |
|------------------------------------------|-----------|--------|---------|--------|--------|-----------|----------------|
| typeSubsumptionCache                     |    89.44% | 106412 |       0 | 900806 | 106412 |     66867 |              0 |

**Comment by T-Gro** [comment]
> As usual I'm testing this in the IDE. I see way less cache churn now and good hit ratio. For example after some minutes of copilot work in this solution:
> 
> Cache name	hit-ratio	adds	updates	hits	misses	evictions	eviction-fails
> typeSubsumptionCache	89.44%	106412	0	900806	106412	66867	0

Would it make sense to publish a built release .vsix for `marklam` from Discord?
Since he does have a private solution, which was however exercising the mechanism quite heavily.

**Comment by majocha** [comment]
Not sure if it goes through
[VisualFSharpFull.zip](https://github.com/user-attachments/files/23415578/VisualFSharpFull.zip)

**Comment by majocha** [comment]
Another potential problem to check, given that we operate on stripped types, can we really trust that a type that looks like it has no type vars at all wouldn't reverse into an unsolved one in the course of Trace.Undo? It looks to me more and more like the whole idea of memoizing TType -> TypeStructure is not great. We really cannot pretend this is a pure function.
Maybe we should instead optimize the shit out of generating type structures.

**Comment by T-Gro** [comment]
> Another potential problem to check, given that we operate on stripped types, can we really trust that a type that looks like it has no type vars at all wouldn't reverse into an unsolved one in the course of Trace.Undo? It looks to me more and more like the whole idea of memoizing TType -> TypeStructure is not great. We really cannot pretend this is a pure function. Maybe we should instead optimize the shit out of generating type structures.

Actually, the fact that the function strips first, and then looks into the weak cache, is of help here.
If ConstraintSolver sets a (possibly speculative) solution to a type var, stripping will then reduce it to the solution itself.
So in that first pass, you would actually get the solution, e.g. a TType_app, as the key.

When that solution is undone, stripping will not kick in (or stop at the last ttype_var) and you would get the TType_var as the key.



Stripping helps to ensure that when we have a solved Ttype_var, it will not go as cache key, but rather its solution will go.



The hypothetical problem is with speculative additions of constraints, since stripping does not change the reference there.
But for that purpose unsolved ttype_vars should not be used as cache entries inside the weak cache, which was done 👍

**Comment by T-Gro** [comment]
@majocha : I would want to merge this in and start dogfooding, WDYT ?

**Comment by majocha** [comment]
> @majocha : I would want to merge this in and start dogfooding, WDYT ?

Yes I think this is fine now, I'm using it and not seeing any anomalies.
