### PR TITLE
Mark attributes we codegen as CompilerGenerated

### LINKED ISSUE #16141: `assembly.GetTypes()` now includes System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes
### Describe the bug

Before .NET 7, `assembly.GetTypes()` returned only types that were defined in my assembly. Now, if the assembly in question is a library and not an executable, it additionally returns `System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes` and `System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute`.

This is true as of SDK 7.0.400; I have a vague recollection that it *wasn't* true of some earlier SDKs in the 7.0 series, but not sure about that.

I'm afraid I have absolutely no idea where this issue should go; `dotnet/sdk` is my best guess.

### To Reproduce

`Lib/Library1.fsproj`:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Thing.fs" />
    </ItemGroup>
</Project>
```

`Lib/Thing.fs`:
```fsharp
namespace Foo
type Foo = Foo
```

`App/Program.fs`:
```
namespace Foo

module Program =
    [<EntryPoint>]
    let main _ =
        typeof<Foo>.Assembly.GetTypes ()
        |> Array.iter (fun ty -> System.Console.WriteLine ty.FullName)
        0
```

`App/App.fsproj`:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
      <Compile Include="Program.fs"/>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Lib\Library1.fsproj" />
    </ItemGroup>
</Project>
```

Running the app gives the following output, demonstrating the problem by its final two lines:

```
Lib.ThisAssembly
Foo.Foo
<StartupCode$Lib>.$Thing
<StartupCode$Lib>.$Lib.Version
<StartupCode$Lib>.$Lib.AssemblyInfo
<StartupCode$Lib>.$.NETStandard\,Version=v2.0.AssemblyAttributes
System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes
System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute
```

### Further technical details

`dotnet --info`:

```
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /nix/store/27hjfsgvv7bklnid729j27kifig070lb-dotnet-sdk-7.0.400/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: arm64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [/nix/store/27hjfsgvv7bklnid729j27kifig070lb-dotnet-sdk-7.0.400/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/nix/store/27hjfsgvv7bklnid729j27kifig070lb-dotnet-sdk-7.0.400/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/nix/store/27hjfsgvv7bklnid729j27kifig070lb-dotnet-sdk-7.0.400/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download      
```

No IDE necessary.

### PR DESCRIPTION
**Pull request by vzarytovskii**
Fixes #16141

**Update:** actually, we might already generate compgen attribute
**Update 2:** we generate for some, and not for others:

image
image

### CODE REVIEW

**Review by T-Gro — APPROVED** [review]

**Comment by vzarytovskii** [comment]
@dotnet/fsharp-team-msft @dotnet/external-fsharp-contributors 

This is ready, need a sanity check here.

File: src/Compiler/CodeGen/IlxGenSupport.fs [hunk 1]
```diff
@@ -104,6 +106,8 @@ let mkLocalPrivateAttributeWithPropertyConstructors (g: TcGlobals, name: string,
             )
         )
 
+    let ilCustomAttrs = mkILCustomAttrsFromArray [| g.CompilerGeneratedAttribute |]
```
Comment (psfinaki) [inline src/Compiler/CodeGen/IlxGenSupport.fs:109]: Why define it twice in this module?

**Review by psfinaki — APPROVED** [review]

**Review by psfinaki — APPROVED** [review]

File: src/Compiler/CodeGen/IlxGenSupport.fs (hunk 1 above)
Comment (vzarytovskii) [reply src/Compiler/CodeGen/IlxGenSupport.fs:109]: Once per each function we use it in
