### PR TITLE
Bugfix :: Fix codegen runtime crashes: TypeLoadException, InvalidProgramException, stack corruption

### LINKED ISSUE #11132: Typeload Exception when function returns a delegate with voidptr parameter
Hi,

I am getting a strange `TypeLoadException` in my code when I trying to create a delegate that contains a `voidptr`, but only when I return it.

````
System.TypeLoadException: 'The generic type 'Microsoft.FSharp.Core.FSharpFunc`2' was used with an invalid instantiation in assembly 'FSharp.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'
````

I am not sure if it's bug report, as I am probably doing something wrong - I just really confused why the code compiles but blows up at runtime.

**Repro steps**

1. Declare or reference a delegate that takes a voidptr parameter
2. Create a function that returns that delegate

```fs
type MyDelegate = delegate of voidptr -> unit

let method ptr = ()

[<Fact>]
let test_runtime_kaboom () =
  let getDelegate method = MyDelegate(method)
  ()
```

I have also attached a sample.zip.

**Expected behavior**

I would expect that the call works without throwing an exception, because:

1. the code compiles without any error or warning
2. creating the delegate actually works, it's only when a function is declared that returns it, is when the problem occurs.
3. changing the signature of the delegate from voidptr to any other type works as well

**Actual behavior**

A typeload exception is thrown.

````
System.TypeLoadException: 'The generic type 'Microsoft.FSharp.Core.FSharpFunc`2' was used with an invalid instantiation in assembly 'FSharp.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'
````

**Known workarounds**

None, except for creating and using the delegate instantly.

**Related information**

* Operating system - Win 10 Version 20H2 OS Build 19042.804
* .NET Runtime kind + .NET Core
* Editing Tools - Visual Studio TestExplorer, nCrunch / JetBrains Rider / dotnet test

Take care,
Martin

### LINKED ISSUE #13447: Extra tail call corrupts stack?
**Repro steps**

Clone https://github.com/kerams/repro/tree/master/src/FableBinarySerializationBug.Server, open Program.fs, run.

**Expected behavior**

```
Byte - 53, in total 1
[|146uy; 1uy; 53uy|]
```

Printed 10 times.

**Actual behavior**

This is printed the first 2 times:

```
Byte - 53, in total 1
[|146uy; 1uy; 0uy|]

Byte - 53, in total 1
[|146uy; 1uy; 112uy|]
```

**Known workarounds**

Remove `[<Struct>]` from `MyResult`.

OR

Put `()` at the end of the `writeString` function. The before and after diff is [here](https://www.diffchecker.com/3qa12ylY). That extra tail call is a bit suspicious.

**Related information**

<details>
<summary>dotnet --info</summary>
.NET SDK:
 Version:   7.0.100-preview.5.22307.18
 Commit:    bd8b088037

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.5.22307.18\

global.json file:
  Not found

Host:
  Version:      7.0.0-preview.5.22301.12
  Architecture: x64
  Commit:       425fedc0fb

.NET SDKs installed:
  6.0.400-preview.22301.10 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.5.22307.18 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.5.22303.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.5.22301.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.5.22302.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</details>

### LINKED ISSUE #14492: F# 7.0 generate incorrect program in release config.
F# 7.0 compiled program failed to run .

**Repro steps**
```fsharp
// fail to run in release config
// runtime: .net framework 4.7
// F# version: 7.0 12.0.5.0 
// Visual Studio 2022
(*
error message: System.TypeLoadException: 
'Method 'Specialize' on type 'memoizeLatestRef@5-1' from 
assembly 'FSharpCompilerBugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' 
tried to implicitly override a method with weaker type parameter constraints.'
*)

let inline refEquals<'a when 'a : not struct> (a : 'a) (b : 'a) = obj.ReferenceEquals (a, b)

let inline tee f x = 
    f x
    x

let memoizeLatestRef (f: 'a -> 'b) =
    let cell = ref None
    let f' (x: 'a) =
        match !cell with
        | Some (x', value) when refEquals x' x -> value
        | _ -> f x |> tee (fun y -> cell := Some (x, y))
    f'

module BugInReleaseConfig = 

    let test f x = 
        printfn "%s" (f x)

    let f: string -> string = memoizeLatestRef id

    let run () = test f "ok"

[<EntryPoint>]
let main argv =
    let culture = System.Globalization.CultureInfo("en")
    System.Globalization.CultureInfo.CurrentCulture <- culture
    System.Globalization.CultureInfo.CurrentUICulture <- culture

    BugInReleaseConfig.run ()

    System.Console.ReadLine() |> ignore
    0
```

**Expected behavior**

It should print "ok".

**Actual behavior**

A System.TypeLoadException was throwed.

**Source code**
[FSharpCompilerBugs.zip](https://github.com/dotnet/fsharp/files/10256741/FSharpCompilerBugs.zip)

### LINKED ISSUE #14508: `nativeptr` in interfaces leads to runtime errors
Implementing a generic interface that contains a member returning `nativeptr<'T>` leads to a `TypeLoadException` with message

>Signature of the body and declaration in a method implementation do not match.

when using that type. Curiously, implementing the interface in a generic type works as expected. I'm not sure if I'm doing something completely unreasonable here, but I'd expect a compiler error at least.

This does not seem to be related to .NET 7.

**Repro steps**

[ConsoleApp1.zip](https://github.com/dotnet/fsharp/files/10286875/ConsoleApp1.zip)

```fsharp
type IFoo<'T when 'T : unmanaged> =
    abstract member Pointer : nativeptr<'T>

type Broken() =
    member x.Pointer : nativeptr<int> = Unchecked.defaultof<_>

    interface IFoo<int> with
        member x.Pointer = x.Pointer

type Working<'T when 'T : unmanaged>() =
    member x.Pointer : nativeptr<'T> = Unchecked.defaultof<_>

    interface IFoo<'T> with
        member x.Pointer = x.Pointer

[<EntryPoint>]
let main argv =
    // Works
    let a = Working<int>()

    // Throws System.TypeLoadException: 'Signature of the body and declaration in a method implementation do not match.
    let b = Broken()

    0
```

**Expected behavior**

Should run or produce a compile-time error if not valid.

**Actual behavior**

Throws an `TypeLoadException` at runtime.

**Related information**

* Windows 10
* .NET 6 (and 7 tested on a colleagues machine)

### LINKED ISSUE #18319: Using a non-null constant expression bound to a literal variable of a less-specific type generates invalid IL
It is possible to define literal values that are the result of upcasting a literal to a less specific type. Using such literals however produces invalid IL that is missing the upcast.

**Repro steps**

```fs
[<Literal>]
let badobj: System.ValueType = 1

System.Console.WriteLine(badobj)
```

**Expected behavior**

The code should either succeed and print "1", or it should fail to compile on the basis that `badobj` is not assigned a constant expression.

**Actual behavior**

The code compiles fine without any warnings, but generates invalid IL upon retrieving the literal value:
```cil
ldc.i4.1
call void [System.Console]System.Console::WriteLine(object)
```
The `box` instruction is missing, resulting in `System.InvalidProgramException` being thrown when the program is launched.

**Known workarounds**

Avoiding upcasts in constant expressions.

**Related information**

It seems such a .NET literal is technically valid (the runtime attaches no semantics to the value encoded in the metadata), but it is not CLS-compliant:
> **CLS Rule 13**: The value of a literal static is specified through the use of field initialization metadata (see Partition II Metadata). A CLS-compliant literal must have a value specified in field initialization metadata that is of exactly the same type as the literal (or of the underlying type, if that literal is an **enum**).

Based on my understanding of the F# specification, it likely should not be possible to define such `[<Literal>]` values, as upcasting is not mentioned in the list of allowed operations. However, such literals could still be found in imported assemblies compiled from languages that do support them, and thus may be re-referenced in F# code.

This broken literal can also be referenced as a default parameter value:
```fs
static member M([<Optional>][<DefaultParameterValue(badobj)>]param: ValueType)
```
This use seems valid, but also generates invalid IL upon calling the method.

Environment: https://sharplab.io/#v2:DYLgZgzgPg9gDgUwHYAIDKBPCAXBBbAWACh5l0tc8A6AJQFclsBLPBKgSUYQCd40eAbkwDGCCMWIBtADwAZJrm4BDYAD4AusWAJsKAEZKAJjD0ArECgBqKuggAqGRCgC8KAIwSiAYRhIIMbSoAdW4FBHkkBAAKA2MzAEpPbEcEFDsUOFCBJVwo+JdiFBQZADkYHzw4Jm1uTmAmJAaAcw1ClBwckRRWPD0eFABZKJkAeThmXxUNGQARBDAlOmBsAAUlZVZFa2BbGKMTU3iNOHWlPAtt2wdEfNcTjc8fPwC2ELCI6LsqIfj4oA

### LINKED ISSUE #18956: Decimal constant causes `System.InvalidProgramException` for debug builds
**Repro steps**

Compile and run this with `dotnet run`

```fsharp
module A =
  [<Literal>]
  let B = 42m

[<EntryPoint>]
let main args =
  0
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Test</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
```

results in
```
Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at <StartupCode$Test>.$Program..cctor()
   at Program.main(String[] args) in .../Program.fs:line 7
```

Note that it works in release mode with `dotnet run -c Release`.

Comparing the generated IR between debug and release of `$Program::.cctor` shows
Debug
```
.method private specialname rtspecialname static 
void .cctor () cil managed 
{
  // Method begins at RVA 0x2070
  // Header size: 12
  // Code size: 17 (0x11)
  .maxstack 2
  .locals init (
    [0] valuetype [System.Runtime]System.Decimal
  )
  ...
}
```
Release
```
.method private specialname rtspecialname static 
void .cctor () cil managed 
{
  // Method begins at RVA 0x2070
  // Header size: 1
  // Code size: 17 (0x11)
  .maxstack 8
  ...
}
```

**Expected behavior**

Should not throw exception.

**Actual behavior**

Throws exception.

**Known workarounds**

Remove `[<Literal>]` attribute or use release build.

**Related information**

Provide any related information (optional):

Reproduces on 9.0.200, 9.0.301, 9.0.303, 9.0.305, 10.0.100-rc.

### PR DESCRIPTION
**Pull request by T-Gro**
Fixes runtime exceptions caused by incorrect IL emitted for valid F# programs.

- Fixes #11132 — `voidptr` in delegate generic args replaced with `nativeint` in closure encoding
- Fixes #13447 — tail calls suppressed in methods using `NativePtr.stackalloc` / `localloc`
- Fixes #14492 — generic type parameter constraints stripped from `Specialize<>` closure methods
- Fixes #14508 — same `voidptr` fix also covers interface instantiations
- Fixes #18319 — `box` instruction emitted for literal upcasts (including default parameter values)
- Fixes #18956 — `box` instruction emitted for decimal literals in debug builds

### CODE REVIEW

File: src/Compiler/CodeGen/IlxGen.fs [hunk 1]
```diff
@@ -1425,7 +1447,34 @@ let GetMethodSpecForMemberVal cenv (memberInfo: ValMemberInfo) (vref: ValRef) =
...
     let ilActualRetTy =
         let ilRetTy = GenReturnType cenv m tyenvUnderTypars returnTy
-        if isCtor || cctor then ILType.Void else ilRetTy
+
+        if isCtor || cctor then
+            ILType.Void
+        // When implementing an interface slot with nativeptr<'T> where 'T is an interface
+        // type parameter and the interface type args are concrete, the interface method
+        // returns 'native int'. The method def must also return 'native int' to match.
+        elif memberInfo.MemberFlags.IsOverrideOrExplicitImpl then
```
Comment (abonie) [inline src/Compiler/CodeGen/IlxGen.fs]: It seems like `GetMethodSpecForMemberVal ` should also check and rewrite params, not only return types. Just like `GenActualSlotsig` does at lines 5996-6025.

Comment (abonie) [reply src/Compiler/CodeGen/IlxGen.fs]: Perhaps there could even be some code reuse between this code here and the code at ~5996?

**Review by abonie — APPROVED** [review]
