### PR TITLE
New code fix: change equals in record field definition to colon

### LINKED ISSUE #15421: Create a code fix to change equals in field type to colon
Change this

```
type Band = { Name = string }
```

to
```
type Band = { Name : string }
```

Maybe call it ChangeEqualsInFieldTypeToColon.

### PR DESCRIPTION
**Pull request by psfinaki**
fixes #15421

We started this code fix at the [recent Amplifying F# session](https://www.youtube.com/watch?v=Y0s_GsT9UUI).

Change
```
type Band = { Name = string }
```
to
```
type Band = { Name : string }
```

Inspired by FsAutoComplete. :)

### CODE REVIEW

File: src/Compiler/Service/FSharpParseFileResults.fs [hunk 1]
```diff
@@ -507,6 +507,22 @@ type FSharpParseFileResults(diagnostics: FSharpDiagnostic[], input: ParsedInput,
         let result = SyntaxTraversal.Traverse(pos, input, visitor)
         result.IsSome
 
+    member _.IsPositionWithinRecordDefinition pos =
+        let isWithin left right middle =
+            Position.posGt right left && Position.posLt middle right
+
+        let visitor =
+            { new SyntaxVisitorBase<_>() with
+                override _.VisitRecordDefn(_, _, range) =
```
Comment (T-Gro) [inline src/Compiler/Service/FSharpParseFileResults.fs:516]: Do not forget anonymous record definitions, which can exhibit exactly the same error.

Sample:
`let f (x:{|A=string|}) = x`

gives exactly the same error which this codefix targets.
(= is unexpected and should be replaced with : )

File: vsintegration/tests/FSharp.Editor.Tests/CodeFixes/ChangeEqualsInFieldTypeToColonTests.fs [hunk 2]
```diff
@@ -0,0 +1,64 @@
+﻿// Copyright (c) Microsoft Corporation.  All Rights Reserved.  See License.txt in the project root for license information.
+
+module FSharp.Editor.Tests.CodeFixes.ChangeEqualsInFieldTypeToColonTests
```
Comment (T-Gro) [inline vsintegration/tests/FSharp.Editor.Tests/CodeFixes/ChangeEqualsInFieldTypeToColonTests.fs:3]: TBH I am not sure if the visitor will work for anonymous records out of the box or not.
Better add a test case for anonymous records too, and adjust impl if needed.

`let f (x:{|A=string|}) = x`
should be codefixed to
`let f (x:{|A:string|}) = x`

**Review by T-Gro — CHANGES_REQUESTED** [review]
See comment at codefix impl - the allocation path should be zero in case the diagnostic FS0010 is for something else.
Error FS0010 comes very often when typing for all sorts of reasons.

**Comment by 0101** [comment]
Can we use the same code fix to also make the fix in the opposite direction? When `=` is expected but `:` is given.

File: src/Compiler/Service/FSharpParseFileResults.fs (hunk 1 above)
Comment (psfinaki) [reply src/Compiler/Service/FSharpParseFileResults.fs:516]: Great point, thanks, added and tested this

File: vsintegration/tests/FSharp.Editor.Tests/CodeFixes/ChangeEqualsInFieldTypeToColonTests.fs (hunk 2 above)
Comment (psfinaki) [reply vsintegration/tests/FSharp.Editor.Tests/CodeFixes/ChangeEqualsInFieldTypeToColonTests.fs:3]: Yep, it's a different thing apparently, VisitRecordDefn x VisitTypeAbbrev. 
Added.

File: vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+
+    override _.FixableDiagnosticIds = ImmutableArray.Create("FS0010")
+
+    override this.RegisterCodeFixesAsync context =
+        // This is a performance shortcut.
+        // Since FS0010 fires all too often, we're just stopping any handling of it
+        // in case when there is the message doesn't have a notion of symbols in question.
+        // The code fix logic itself still has this logic and implements it more reliably.
+        if
+            context.Diagnostics
```
Comment (T-Gro) [inline vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs:34]: These are still (IMO) unnecessary allocations for the seq enumerator and for string building.
Why not a direct exact string equality check for the full string? We know how FS0010 looks like (and can even cache the localized version of the .Diagnostics fields contains the localized one, not sure know).

Comment (T-Gro) [reply vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs:34]: You do not have to do Seq-based enumeration which needs a heap-allocated Enumerator.
The same for the internal allocations needed to do string interpolation, even though we know the strings.

The FS0010 strings to compare can be directly referenced within the  codebase and not repeated, to eliminate the fear of those texts changing. (and the right characters passed in as a parameters, and then the whole string statically cached for example)

File: vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+    let isInRecord (document: Document) (range: range) =
+        cancellableTask {
+            let! parseResults = document.GetFSharpParseResultsAsync(nameof ChangeEqualsInFieldTypeToColonCodeFixProvider)
+
+            return parseResults.IsPositionWithinRecordDefinition(range.Start)
+        }
+
+    override _.FixableDiagnosticIds = ImmutableArray.Create("FS0010")
+
+    override this.RegisterCodeFixesAsync context = context.RegisterFsharpFix(this)
```
[the remark this answers is not in the document]
Comment (auduchinok) [reply vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs]: We've been thinking about the same issue with localization in Rider for some time, and I think the best approach we could use is to [add the relevant data into the diagnostics](https://github.com/fsharp/fslang-suggestions/issues/1094), e.g. instances of `FSharpType` for type errors, tokens text/name for `FS0010` where possible and so on. Union cases holding info for specific diagnostic types seems to be the most accepted option from the previous discussions in Slack/Twitter/etc.

[the remark this answers is not in the document]
Comment (T-Gro) [reply vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs]: I think subtypes would be more binary-future-compatible compared to DUs, but otherwise yes, this could be a valid appraoch and also possible to roll incrementally (I think that is a must given the diagnostics existing in the codebase already).

[the remark this answers is not in the document]
Comment (T-Gro) [reply vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs]: Btw. the calls to FSComp.SR.  are going trough resources and take the CurrentUICulture.
This is no VS magic, is all in the compiler code.


Oh and an idea of at least quickly gaining accessed to structured data, even though unnamed ("named" would have to go via dedicated subtypes/cases as written above) - the arguments which now in as format specifiers might be easily&centrally extractable - FsComp.fs/createMessageString has access to it.

But personally, I am now more inclined to do diagnostics subtypes on a as-needed basis when a specific feature demands it.
(incl. my favourit subtype for a diagnostic that would already include a lazy TextChange proposal, since the error/warning emitting code is IMO the one best equipped to produce it)

[the remark this answers is not in the document]
Comment (auduchinok) [reply vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs]: > I think subtypes would be more binary-future-compatible compared to DUs

@T-Gro Could you please elaborate? If we start with more than one case in a DU, then I don't see how adding another case later would break binary compatibility. Each case with fields would be compiled into a nested subtype anyway.

Using DU seems a bit better for pattern matching over the fields in F#: it won't require type check pattern + `as` pattern to access the field later in expression. Checking particular cases might also be optimized by the compiler to just checking an `int` union case tag, compared to always required type checking with explicit subtypes.

File: vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+        // in case when there is the message doesn't have a notion of symbols in question.
+        // The code fix logic itself still has this logic and implements it more reliably.
+        if
+            context.Diagnostics
+            |> Seq.map (fun d -> $"{d.Descriptor.MessageFormat}")
+            |> Seq.exists (fun d -> d.Contains "=" && d.Contains ":")
+        then
+            context.RegisterFsharpFix(this)
+        else
+            task { return () }
```
Comment (vzarytovskii) [inline vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs:40]: No need to allocate the state machine, `Task.FromResult()` should be good enough.

Comment (psfinaki) [reply vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs]: Good point

File: vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs (hunk 4 above)
[the remark this answers is not in the document]
Comment (T-Gro) [reply vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs]: @auduchinok :

Firstly, the internal representation of a DU can change as the DU grows (e.g. from being a single-value wrapper to a choice later) or changes shape (nullary vs non-nullary cases as well).

The more important issue I see, with the lenses of "using a a newer version of F.C.S without having to recompile" is that you might start with exhaustive matching, but then F.C.S adds a new case -> you suddenly start getting runtime exceptions even though at coding time it was all considered safe.

I also see this as something which would have to play together with custom analyzers, where the "upgrade F.C.S without recompiling" is a likely scenario.

(I admit that in the tooling world it's probably a non-issue)

File: vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs (hunk 3 above)
Comment (psfinaki) [reply vsintegration/src/FSharp.Editor/CodeFixes/ChangeEqualsInFieldTypeToColon.fs]: @T-Gro so actually it's just occurred to me that we don't have to iterate through anything here. The way the code fixes work, this can will be triggered only for one fs0010 diagnostic. As in, the code fix context doesn't contain diagnostics that the code fix is not made for:
image

So we can access the message right away, counting with the fact it's very unlikely anybody adds another diagnostic here.

**Review by T-Gro — APPROVED** [review]

**Review by 0101 — APPROVED** [review]
