### PR TITLE
Tag items in tooltips consistenly with respect to document classification (such colors, much wow)

### LINKED ISSUE #5385: Interfaces colored as classes in tooltips
Interfaces are colored as classes instead of interfaces in different places in tooltips:

image
image
image

Visual Studio 15.7.5

### LINKED ISSUE #6160: What does the "Big O" mean in the tooltip of an error?
I just noticed the following in the tooltip of an error in VS 2017:

image

I doubt this is a bug, but it confused me a little. Does it mean it is waiting for tasks to complete? Or does it signify something otherwise sensible?

### Repro steps

The error can be seen, among others, with this code snippet (the actual error is sound, the bug report is about the mysterious "O"):

```f#
type ObjectWithPrivCtor private (x: string) =
    static member X = ()
    
module SomeModule =
    let Create x = ObjectWithPrivCtor(x)
```

### Expected behavior

Not sure, some text perhaps? On most objects, it would show the declaration, i.e. in this case, it should show this (but then the error underneath):

image

### Actual behavior

The Big O ;)

### Known workarounds

None

### Related information 

VS 2017, 15.9.5

### LINKED ISSUE #9561: 'new' mistakenly classified as function or method, not keyword
Latest master:

image

This should be a keyword

### PR DESCRIPTION
**Pull request by cartermp**
Fixes #5385 and various other inconsistencies. Also fixes #9561 and fixes #6160 

### WE GOT US SOME MORE COLORS FOLKS

Value types are now colored in tooltips (as they are in source). Parameters and properties (and record labels) are colored just like parameters in source:

image

image

Methods have the same coloring as methods in source:

image

Functions have the same coloring as functions in source:

image

Methods and constructors follow the `+ N overloads` paradigm and properties with get/set aren't shown twice anymore:

image

Generic type instantiations in tooltips show the correct color for their type kind:

image

.NET-defined types now also have the same fidelity as F#-defined types w.r.t colorization:

image

Another example:

image

### CODE REVIEW

**Comment by cartermp** [comment]
Ugh, aligning QuickInfo data with classification data is going to be challenging. But it would fix at least one additional bug in this repo.

**Comment by cartermp** [comment]
F# defined methods now colored consistently

image

F# defined values now colored consistently

image

**Comment by cartermp** [comment]
Checklist to look into:

* `string` function vs. `string` type - in some cases, `string` is colorized as an intrinsic function when it should not be
* .NET-declared interface members all have their types/return types for members and type arguments colored wrong unless it's an intrinsic type or keyword, like so:

image

* XML doc interface types are still colored wrong: 

image

* Functions are incorrectly not colored or are incorrectly colored as a local

image

image

I think these are all resolvable without fundamentally changing anything.

File: src/fsharp/NicePrint.fs [hunk 1]
```diff
@@ -64,7 +64,25 @@ module internal PrintUtilities =
         | (x :: rest) -> [ resultFunction x (layoutFunction x -- leftL (tagText (match rest.Length with 1 -> FSComp.SR.nicePrintOtherOverloads1() | n -> FSComp.SR.nicePrintOtherOverloadsN(n)))) ] 
         | _ -> []
     
-    let layoutTyconRefImpl isAttribute (denv: DisplayEnv) (tcref: TyconRef) = 
+    let layoutTyconRefImpl isAttribute (denv: DisplayEnv) (tcref: TyconRef) =
+        let tagEntityRefName (xref: EntityRef) name =
```
Comment (cartermp) [inline src/fsharp/NicePrint.fs:68]: necessary?

**Comment by cartermp** [comment]
More checklist:

- [ ] Clear out duplicates for constructors
- [ ] Figure out navigable ranges (something is missing)
- [ ] Get attributes done

File: src/fsharp/NicePrint.fs [hunk 2]
```diff
@@ -105,7 +123,7 @@ module private PrintIL =
     let fullySplitILTypeRef (tref: ILTypeRef) = 
         (List.collect IL.splitNamespace (tref.Enclosing @ [PrettyNaming.DemangleGenericTypeName tref.Name])) 
 
-    let layoutILTypeRefName denv path =
```
Comment (cartermp) [inline src/fsharp/NicePrint.fs:108]: this will likely go away, in addition to other unused routines

File: src/fsharp/NicePrint.fs [hunk 3]
```diff
@@ -1662,298 +1703,359 @@ module private TastDefinitionPrinting =
...
-#if SHOW_ERASURE
-            if tcref.IsProvidedErasedTycon then 
-                [ wordL ""; wordL (FSComp.SR.erasedTo()) ^^ PrintIL.layoutILTypeRef { denv with shortTypeNames = false } tcref.CompiledRepresentationForNamedType; wordL "" ] 
-            else 
-#endif
-                []
-        let decls = inherits @ iimplsLs @ ctorLs @ membLs @ nestedTypeLs @ erasedL
-        if isNil decls then
-            lhsL
+    let layoutProvidedTycon (denv: DisplayEnv) (infoReader: InfoReader) ad m lhsL ty (tycon: Tycon) simplified =
```
Comment (cartermp) [inline src/fsharp/NicePrint.fs:1706]: this will be renamed

**Comment by cartermp** [comment]
Further checklist:

- [ ] Do we do `with get` when it's only a getter, or leave that all off?
- [ ] `DontShowCompilerGenNames01` signature (`member z.M2 ((x, y) : int * string) = ignore`) doesn't show tupling when hovering over `T`
- [ ] Type layout is used by `--sig` and this code breaks all of that with the overload flattening for members
- [ ] Member accessibility is lost (`InternalAccessibility02`) - specifically, `private` is now missing

**Comment by cartermp** [comment]
https://github.com/dotnet/fsharp/issues/6160 is also fixed here

File: src/fsharp/NicePrint.fs [hunk 4]
```diff
@@ -1643,317 +1372,356 @@ module private TastDefinitionPrinting =
...
-            | true, true -> WordL.keywordWith ^^ WordL.keywordGet^^ SepL.comma ^^ WordL.keywordSet
-
-        staticL ^^ WordL.keywordMember ^^ nameL ^^ WordL.colon ^^ typL ^^ specGetSetL
-
-    /// Another re-implementation of type printing, this time based off provided info objects.
-    let layoutProvidedTycon (denv: DisplayEnv) (infoReader: InfoReader) ad m start lhsL ty =
-      let g = denv.g
-      let tcref = tcrefOfAppTy g ty
-
-      if isEnumTy g ty then
```
Comment (KevinRansom) [inline src/fsharp/NicePrint.fs:1669]: Are enum's now just taken care of by displaying fields?

Comment (cartermp) [reply src/fsharp/NicePrint.fs:1669]: Yep!

F#-defined:

image

.NET-defined:

image

**Comment by abelbraaksma** [comment]
I didn't test my bug report against a build with the changes of this PR, so it's possible it has already been tackled here. Be as it may, I think it's at least related: https://github.com/dotnet/fsharp/issues/9771 (in short: certain constraints like `enum`, `comparison`, `not struct` etc are not colored blue).

**Comment by cartermp** [comment]
Left a comment there; this PR doesn't do anything to help the situation. Name resolution lacks the ability to properly distinguish or at least emit data that distinguishes the cases you've noted there.

**Comment by cartermp** [comment]
Would appreciate a review at some point @KevinRansom @TIHan @dsyme

**Comment by cartermp** [comment]
I can't update baselines on my machine the "proper" way, since my machine will BSOD if I run tests in release.

pls halp

**Comment by dsyme** [comment]
Looking at #9511 and this I don't really agree with the number distinctions being made.  Some of them are OK.  

These are "just my opinions" but I'll try to explain them

Regarding methodology -  in the absence of user testing (very very hard), one methodology is to consider what distinctions matter in the mind of the F# user and when, and how intrusive the distinction is to the act of coding. Three principles seem to be

- Distinctions can be prioritised besed on the likelihood that the distinction is highly relevant to the typical (assumed) tasks being performed when writing and understanding F# code.

- Distinctions should be "appropriately intrusive"  for the likely signficance of the distinction being made (e.g. types are all colored greenish, because the difference between them is not that significant, but mutable values get a substantial difference, because the distinction matters)

- There is a cognitive cost to making distinctions (I spent quite a while wondering about why half my code has different colors) 

Now, there are literally zillions of distinctions we could make, e.g. struct v. reference, union v. record, big v. small, delegate v. function, disposable v. non-disposable, static v. non-static, public v. non-public, types  with a Count property and without, etc. etc. 

For F#, we shouldn't just suck up C#'s distinctions. However, the F# language design is rooted in the idea that you have values (let) and types (type).  Different types and values have different characteristics, but much is done to emphasise similarity between these, rather than distinction. For example, a union type is different to a record type but both can have members. Iin most code, most the time, the user doesn't care if something is implemented as a record or a union.  Because of this, emphasising the difference in implementation would be wrong.

At the extreme, in F# a signature file can just say "type X" and be essentially non-commital about what "X" is - it doesn't matter if its an interface, class, delegate or whatever (though for technical reasons its structness must be known).  Those are implementation details  - what matters in functional programming is the set of operations you can do with "X". That said, a type's representation can make some particular operations available (e.g. pattern matching)

Anyway, let's take some examples and I'll give my opinions.  These can be read as either arguing for an elimination of a distinction or the reducing of the "size" of the distinction.

1. Types - "delegate v. enum v. ..."

   Don's opinion: mild preference for no distinction (or at most a subtle distinction on types)

   Explainer: To me this is importing C# OO distinctions into F#.  I'm inclined not to do that in the colorizations but I know opinions will differ on this.  Further, we don't do union v. record, for example (and I don't think we should).

2. Types - value type v. reference type 

   Don's opinion: mild preference for no distinction (or at most a subtle distinction on types)

   Explainer: This is a little suspect to me -  In F#, putting "Struct" on something often doesn't change the semantics at all, just the operational properties.  What the F# programmer might care about is referential transparency (e.g. the thing is a value where deep-cloning it doesn't matter). But that's not something we have knowledge of.

   Caveat: That said I'm likely used to a subtle difference in highlighting of these and of all the type distinctions we could make it's not too bad.

3. Types - interface v. non-interface

   Don's opinion: mild preference for no distinction (or at most a subtle distinction on types)

   Explainer: Personally, I don't like this distinction.  The `I` prefix distinction in type name is already enough. But opinions vary on this. In F#, it often doesn't matter if something is an interface type (e.g. `seq` is an interface but who cares?), and the F# programmer rarely implements an interface.

   Caveat: This may matter more when doing outright OO programming in F#.


4. Types - abbreviation v. non-abbreviation

   Don's opinion: strong preference for no distinction

   Explainer: In F# the programmer thinks of the abbreviation as equivalent to the non-abbrviated type. They shouldn't be shown in different colors

5. Disposable v. non-DIsposable (types and values)

   Don's opinion: strong preference for no distinction (or at most a very subtle distinction on values)

   Explainer: The distinction *is* important to some extent, at particular phases, and particularly at the declaration of t disposable value when a "use" might be necessary.  But coloring every *use* of a disposable value looks very wrong.  I sent @cartermp some examples

   I definitely don't like coloring disposable types in a different color

6. Values - Direct mutability v. not

   Don's opinion: strong preference for fairly strong distinction (as we have today)

   Explainer: I think this is a good semantic distinction to highlight, it's been discussed and is effective in helping you get code correct

7. Values - function/method v. value

   Don's opinion: strong preference for fairly strong distinction (as we have today)

   Explainer: It seems this is based on the value's type (e.g. a parameter of function value is colored). OK, fair enough

8. Values - top level v. non-top-level (open-scope v. limited scope)

   Don's opinion: I can see the value for a subtle distinction - among other things it likely helps to orient the programmer when they are in a large module v. a large class/function body

   Explainer: Right now there is a fairly subtle distinction between Module/member and class/expression bindings.   I don't have strong feelings about this as the distinctions are very subtle.  But it's worth noticing that it's not distinguishing static. v. non-static, in the following I'm seeing `xxxxxxxxxxxxxxxx` and `yyyyyyyyyyyyyyyy` get different colors.  

       module M = 
           let xxxxxxxxxxxxxxxx = 1

       type C() =
           static let yyyyyyyyyyyyyyyy = M.xxxxxxxxxxxxxxxx

9. static v. non-static 

   This distinction is not currently being coloured.  

@cartermp Are there other distinctions planned I could give my 2c worth on?

**Comment by dsyme** [comment]
To summarise, 

* I likely don't mind the subtle distinctions on types being introduced here. But they are "only" in tooltips so that's ok

* The only thing that's really irking me in VS2019 current is that IDisposable types and values are getting a different color.  That doesn't feel right and is quite jarring

**Comment by auduchinok** [comment]
@dsyme What do you think about methods and function values highlighted the same way? Since they have different rules w.r.t implicit casting, optional arguments, and overloads, I think it might be not so good to highlight them identically.

**Comment by cartermp** [comment]
> The only thing that's really irking me in VS2019 current is that IDisposable types and values are getting a different color. That doesn't feel right and is quite jarring

This is definitely an easy fix, let me queue up a PR. I'll retain the custom classification definition for settings in case people want to tweak it, though

**Comment by dsyme** [comment]
> This is definitely an easy fix, let me queue up a PR. I'll retain the custom classification definition for settings in case people want to tweak it, though


Yup, thanks!

**Comment by dsyme** [comment]
> @dsyme What do you think about methods and function values highlighted the same way? Since they have different rules w.r.t implicit casting, optional arguments, and overloads, I think it might be not so good to highlight them identically. It's not about the tooltips, though, just a general question.

Yes it's an intersting onw.  At most, a very small distinction.  But equally you could argue static v. instance is more important, or overloaded v. non-overloaded.

This whole business of "small distinctions" in colorization is fairly new to me.

**Comment by cartermp** [comment]
Note that this is where things get wild:

> (e.g. `seq` is an interface but who cares?)

This depends entirely on the context of `seq` in source:

image

At the top, yes it is a type abbreviation for an interface, so it's shown as an interface.

At the bottom, it's actually two things:

1. A custom builder
2. A function

And we need to pick which we prefer for colorization.

If you hover over it, you will see the function.

So, what's the best choice for the user? Currently it will color as a custom build because that's what it used to do before, and that's what we do for `async` and other CEs as well. But the tooltip does now show info about a custom builder, it shows a function. So with this PR, the color of the name in the tooltip with match function colorization.

I don't think that the act of matching function colorization is wrong for the tooltip. It should just color whatever we decide to show in the tooltip. If the tooltip is a function, it should color as a function. If it is a custom builder, it should color as that.

The alternative of course would be to simply not color anything. But that sucks, and the fact that we got contributions, feedback on those contributions, and issues people have filed all around offering better colorization speaks to that.

**Comment by lfr** [comment]
Isn't green used for comments by default? Maybe it's just me but there's a lot of shades of green now and it looks a bit overwhelming especially with commented code.

**Comment by cartermp** [comment]
Yeah, that was changed in here: https://github.com/dotnet/fsharp/pull/10092

**Comment by cartermp** [comment]
This is ready for review @dsyme @TIHan @KevinRansom @auduchinok

**Review by KevinRansom — APPROVED** [review]

File: src/fsharp/TypedTreeOps.fs [hunk 5]
```diff
@@ -2844,7 +2853,7 @@ let tagEntityRefName (xref: EntityRef) name =
     elif xref.IsFSharpDelegateTycon then tagDelegate name
     elif xref.IsILEnumTycon || xref.IsFSharpEnumTycon then tagEnum name
     elif xref.IsStructOrEnumTycon then tagStruct name
-    elif xref.IsFSharpInterfaceTycon then tagInterface name
+    elif xref.IsFSharpInterfaceTycon || isInterfaceTyconRef xref then tagInterface name
```
Comment (cartermp) [inline src/fsharp/TypedTreeOps.fs:2856]:
```suggestion
    elif isInterfaceTyconRef xref then tagInterface name
```

File: src/fsharp/TypedTreeOps.fs [hunk 6]
```diff
@@ -1825,6 +1826,10 @@ let isRefTy g ty =
         (isAnonRecdTy g ty && not (isStructAnonRecdTy g ty))
     )
 
+let isFunctionTy g ty =
+    let _, tau = tryDestForallTy g ty
+    isFunTy g tau
```
Comment (cartermp) [inline src/fsharp/TypedTreeOps.fs:1831]: Consider renaming and seeing how this differs from `isFunTy`

Comment (cartermp) [reply src/fsharp/TypedTreeOps.fs:1831]: `isForallFunTy` perhaps?

File: src/fsharp/NicePrint.fs [hunk 7]
```diff
@@ -64,7 +64,25 @@ module internal PrintUtilities =
...
+                let ty = xref.TypeAbbrev.Value
+                match stripTyEqns denv.g ty with
+                | TType_app(tcref, _) when tcref.IsStructOrEnumTycon ->
+                    tagStruct name
+                | _ ->
+                    tagAlias name
+            elif xref.IsFSharpDelegateTycon then tagDelegate name
+            elif xref.IsILEnumTycon || xref.IsFSharpEnumTycon then tagEnum name
+            elif xref.IsStructOrEnumTycon then tagStruct name
+            elif xref.IsFSharpInterfaceTycon || isInterfaceTyconRef xref then tagInterface name
```
Comment (cartermp) [inline src/fsharp/NicePrint.fs:81]: double check if simplify is possible

File: src/fsharp/NicePrint.fs [hunk 8]
```diff
@@ -177,7 +179,7 @@ module private PrintIL =
         match ty with
         | ILType.Void -> WordL.structUnit // These are type-theoretically totally different type-theoretically `void` is Fin 0 and `unit` is Fin (S 0) ... but, this looks like as close as we can get.
         | ILType.Array (sh, t) -> layoutILType denv ilTyparSubst t ^^ layoutILArrayShape sh
-        | ILType.Value t
+        | ILType.Value t -> layoutILTypeRef denv t.TypeRef ^^ (t.GenericArgs |> List.map (layoutILType denv ilTyparSubst) |> paramsL)
```
Comment (cartermp) [inline src/fsharp/NicePrint.fs:182]: double check if necessary

File: src/fsharp/NicePrint.fs [hunk 9]
```diff
@@ -1670,317 +1399,356 @@ module private TastDefinitionPrinting =
...
+                else
+                    WordL.keywordMember
+        
+            let propTag =
+                let tag =
+                    p.PropertyName
+                    |> adjustILName
+                    |> tagProperty
+
+                match p.ArbitraryValRef with
```
Comment (cartermp) [inline src/fsharp/NicePrint.fs:1436]: May not be necessary, double-check?

File: src/fsharp/NicePrint.fs [hunk 10]
```diff
@@ -1670,317 +1399,356 @@ module private TastDefinitionPrinting =
...
-        let props = 
-            GetIntrinsicPropInfosOfType infoReader None ad AllowMultiIntfInstantiations.Yes PreferOverrides m ty
+        let props =
+            GetImmediateIntrinsicPropInfosOfType (None, ad) g amap m ty
             |> List.filter (fun v -> shouldShow v.ArbitraryValRef)
 
         let events = 
             infoReader.GetEventInfosOfType(None, ad, m, ty)
-            |> List.filter (fun v -> shouldShow v.ArbitraryValRef)
+            |> List.filter (fun v -> shouldShow v.ArbitraryValRef && typeEquiv g ty v.ApparentEnclosingType)
```
Comment (cartermp) [inline src/fsharp/NicePrint.fs:1517]: double check why this is

File: src/fsharp/NicePrint.fs [hunk 11]
```diff
@@ -1670,317 +1399,356 @@ module private TastDefinitionPrinting =
...
+
+        let fieldLs =
+            infoReader.GetILFieldInfosOfType (None, ad, m, ty)
+            |> List.filter (fun fld -> not (isDiscard fld.FieldName))
             |> List.map (fun x -> (true, x.IsStatic, x.FieldName, 0, 0), layoutILFieldInfo denv amap m x)
+            |> List.sortBy fst
+            |> List.map snd
+
+        let staticValsLs =
+            if isRecdTy g ty then
```
Comment (cartermp) [inline src/fsharp/NicePrint.fs:1567]: Maybe not required, double check

**Review by TIHan — APPROVED** [review]
Looks great! Looking forward to seeing the consistency.

Only thing is the `isFunctionTy` should be a different name so we don't get confused by `isFunTy`.

**Comment by lfr** [comment]
Is this a known bug?

image

**Comment by lfr** [comment]
Please disregard my previous comment, it's fine in 5.0
