### PR TITLE
Fix for 12184 - correct pre-processing of type information from overloads involving SRTP constraints

### LINKED ISSUE #12184: The type 'Async<'a>' does not support the operator 'GetAwaiter' error after updating Fsharp.Core to 6 version
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

I've tried updating pulsar library to Fsharp.Core and removed TaskBuilder.fs dependency, then tried to build project.
[Link to commit](https://github.com/fsharplang-ru/pulsar-client-dotnet/commit/06f77713552ab8f7754c6410facf8431a0d245b1)
Branch **fsharpsix**
[Link to failed github action](https://github.com/fsharplang-ru/pulsar-client-dotnet/runs/3704772222?check_suite_focus=true)

**Expected behavior**

_dotnet build_ works fine on Pulsar.Client project (\src\Pulsar.Client)

**Actual behavior**

I'm getting errors [on this file](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/06f77713552ab8f7754c6410facf8431a0d245b1/src/Pulsar.Client/Internal/BinaryLookupService.fs)

  BinaryLookupService.fs(100, 9): [FS0001] The type 'Async<'a>' does not support the operator 'GetAwaiter'
  BinaryLookupService.fs(129, 9): [FS0001] The type 'Async<'a>' does not support the operator 'GetAwaiter'

**Known workarounds**

- Specify the returning type directly
- Reorder methods

**Related information**

Provide any related information (optional):

* Windows 10
* Microsoft (R) Build Engine version 17.0.0-preview-21378-03+d592862ed for .NET
* Jetbrains Rider

### PR DESCRIPTION
**Pull request by dsyme**
This fixes #12184 

The problem is with resolution of this kind of amiguous code:
```fsharp
    let TaskMethod t =
        task {
            let! result = t
            return result
        }
```
Here `let!` uses overload resolution on `task.Bind`.  This has multiple overloads:
```
member Bind: Task<'T> * ('T -> TaskCode<...>)
member Bind: Async<'T> * ('T -> TaskCode<...>)
member Bind: ^TaskLike * ('T -> TaskCode<...>) when ... 
```
The intention of the RFC is that the overloads are used in the above priority order - that is, if no type information is available then `Task<'T>` is assumed. The actual RFC uses extension methods as the basis to ensure this priority order. With this design, overloads are resolved eagerly, and the highest priority one will be chosen based on available type annotations, so if you don't specify a type, `Task<_>` will be assumed.  For example

```fsharp
let TaskMethod t =
    task {
        let! result = t
        return result
    }
```
will compile and infer type
```fsharp
val TaskMethod: t: Task<'a> -> Task<'a>
```

This differs from TaskBuilder.fs but is the intended design (among other things it prevents SRTP constraints floating everywhere throughout resolution, with their accompanying difficult error messages, and prevents default solutions for SRTP constraints causing strange errors).

However, the priority order was not applying.  The reason is subtle: a rule in overload resolution called "eager constraint application" meant the SRTP overload is being given absolute priority in the absence of other type information - the details are explained below.  This is established behaviour and even useful in some situations, and thus can't be changed universally (that is, some existing code will depend on it).  

As a result, this PR adopts a conservative approach to fixing this, allowing an overload to declare that "eager constraint application" doesn't apply.   This attribute is not expected to be used by anyone except the most advanced F# programmers and is really designed to correct what was effectively a mistake (or at best inadvertent behaviour that has since proved useful to some users) and allow for the design of overload sets with more normal properties.

I will add this to the "task" RFC

### Detailed background

As background, one of the phases of F# overload resolution is to propagate "known type information" into lambda expression arguments, e.g. for the overloads

```fsharp
    type Overloads() =
        static member SomeMethod(x: 'T array, f: 'T -> int, n: int) = ()
        static member SomeMethod(x: 'T array, f: 'T -> int, s: string) = ()

    Overloads.SomeMethod([| "a" |], (fun a -> a.Length), 1)
    Overloads.SomeMethod([| "a" |], (fun a -> a.Length), "a")
```

Here the type `string` is applied to `'T` based on processing the first argument, then, prior to processing the second argument, the type of "a" is known to be string because both overloads have a lambda of the same shape in the same position.  This process is called "LambdaPropagationInfo" and uses the constraint solver in "MatchingOnly" mode which works out values for type variables in the overload matrix, without affecting the types on the callsite (we can't affect these as the overload has not been committed yet).

Now, when some overloads use SRTP the "MatchingOnly" mode was incorrectly pushing an SRTP constraint into the types on the callsite.  For example
```fsharp
    type OverloadsWithSrtp() =
        static member inline SomeMethod< ^T when ^T : (member Foo: int) > (x: ^T, f: ^T -> int) = 1
        static member inline SomeMethod(x: 'T list, f: 'T list -> int) = 2

    let inline f x = 
        OverloadsWithSrtp.SomeMethod (x, (fun a -> 1)) 
```
Here the call contains no specific information, and there is no grounds to prefer the SRTP overload.  So the overload should not resolve.  However, because one of the methods is an SRTP method, the constraint is eagerly applied to the argument type for "x".  This means that the second method becomes non-applicable, and thus the overload does resolve.  This happens regardless of other overload resolution rules.

### CODE REVIEW

**Comment by dsyme** [comment]
This improves error messages when sufficient type annotations are missing and allows the code
```fsharp
    let TaskMethod t =
        task {
            let! result = t
            return result
        }
```
Previously this was giving a cryptic error because the SRTP constraints were being partially applied during the process of overload resolution. 

Note that the intended behaviour [according to the RFC](https://github.com/fsharp/fslang-design/blob/main/preview/FS-1097-task-builder.md#bind-returnfrom-support) is that the overloads have the following priority:

* Highest: `Task<'T>`
* Medium: `Async<'T>`
* Lowest: ` ^TaskLike `

With this design, overloads are resolved eagerly, and the highest priority one will be chosen based on available type annotations. So if you don't specify a type, `Task<_>` will be assumed.  For example

```fsharp
let TaskMethod t =
    task {
        let! result = t
        return result
    }
```
will compile and infer type
```fsharp
val TaskMethod: t: Task<'a> -> Task<'a>
```

This differs from TaskBuilder.fs but is the intended design - among other things it prevents SRTP constrains floating everywhere throughout resolution (with their accompanying difficult error messages).

File: src/fsharp/ConstraintSolver.fs [hunk 1]
```diff
@@ -2061,7 +2092,10 @@ and AddConstraint (csenv: ConstraintSolverEnv) ndeep m2 trace tp newConstraint
               | (TyparRigidity.Rigid | TyparRigidity.WillBeRigid), TyparConstraint.DefaultsTo _ -> true
               | _ -> false) then 
             ()
-        elif tp.Rigidity = TyparRigidity.Rigid then
+        elif tp.Rigidity = TyparRigidity.Rigid || 
+             // The 'task' feature requires this fix to SRTP resolution.
+             (g.langVersion.SupportsFeature LanguageFeature.ResumableStateMachines &&
```
Comment (TIHan) [inline src/fsharp/ConstraintSolver.fs:2097]: Normally we try not to put fixes behind language feature flags. The goal of having a lang version is to prevent users from using newer features; not necessarily for having different behavior in, such as SRTP resolution, for different lang versions. The behavior should really be unified across all versions as a fix; otherwise, I fear we will enter a trap.

Do we have any other behavior that is different for existing features based on a feature flag?

Comment (dsyme) [reply src/fsharp/ConstraintSolver.fs]: This is now done

File: src/fsharp/CheckExpressions.fs [hunk 2]
```diff
@@ -9133,10 +9133,13 @@ and TcMethodApplication
             let lambdaPropagationInfo =
                 if preArgumentTypeCheckingCalledMethGroup.Length > 1 then
                     [| for meth in preArgumentTypeCheckingCalledMethGroup do
-                        match ExamineMethodForLambdaPropagation meth ad with
+                        match ExamineMethodForLambdaPropagation cenv.g mMethExpr meth ad with
                         | Some (unnamedInfo, namedInfo) ->
                             let calledObjArgTys = meth.CalledObjArgTys mMethExpr
-                            if (calledObjArgTys, callerObjArgTys) ||> Seq.forall2 (fun calledTy callerTy -> AddCxTypeMustSubsumeTypeMatchingOnlyUndoIfFailed denv cenv.css mMethExpr calledTy callerTy) then
+                            if (calledObjArgTys, callerObjArgTys) ||> Seq.forall2 (fun calledTy callerTy -> 
+                                let noEagerConstraintApplication = MethInfoHasAttribute cenv.g mMethExpr cenv.g.attrib_NoEagerConstraintApplicationAttribute meth.Method
```
Comment (TIHan) [inline src/fsharp/CheckExpressions.fs:9140]: This is now a new attribute that has semantic meaning - we should probably error if the lang version is less than F# 6.0? Otherwise a lang version of 4.7 could use this attribute, is that intended?

**Review by TIHan — APPROVED** [review]

File: src/fsharp/CheckExpressions.fs (hunk 2 above)
Comment (dsyme) [reply src/fsharp/CheckExpressions.fs:9140]: Fixed this, thanks!
