### PR TITLE
(Eventually) fix #17501

### LINKED ISSUE #17501: F# compiler is really slow when trying to compile .net8.0 project with SDK 8.0.303
**Repro steps**

Provide the steps required to reproduce the problem:

1. Clone this specific commit: https://github.com/BoyBaykiller/opentk/tree/5c9dc6e6f0ec4c911fe05357dbfccc7e81d1842f
2. Try to compile this test project using `dotnet build -v:n .\tests\OpenTK.Tests\OpenTK.Tests.fsproj`

**Expected behavior**

The compiler should compile the project (this particular commit has a runtime error, but that shouldn't matter).

**Actual behavior**

The compiler never finishes compiling the project.

**Known workarounds**

Switching to `.net6.0` fixes the issue.

**Related information**

I also tried targeting and compiling the project with SDK Version: 9.0.100-preview.6.24328.19 and I still get the hang.

Provide any related information (optional):

* Operating system: Windows 10
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET Core 8.0.303
* Editing Tools (e.g. Visual Studio Version, Visual Studio): Visual Studio 2022 Version 17.10.5

### PR DESCRIPTION
**Pull request by vzarytovskii**
The approach I want to take is to cache the results of type subsuming for two given types (in `TypeFeasiblySubsumesType` & co).

For now just make code a bit more readable, trying to figure out how should we approach the caching itself, since `TType` itself is not have and equality for it (by design), since we can have non-nominal generic types, where TType_var's solution can be (and is) mutable, and can change with time.

**Update, perf:**
With cache (PR): **5.8s**
Without cache (main): **130.9s**
On a real project with issue (OpenTK, which uses NET 8 BCL and its types extensively), compiled successfully.

One concern is that there can be a hash collision eventually, which will trip this logic. But I will play with additional value comparisons if we hit the cache.

### CODE REVIEW

File: src/Compiler/Checking/TypeHierarchy.fs [hunk 1]
```diff
@@ -139,6 +139,8 @@ let GetImmediateInterfacesOfMetadataType g amap m skipUnref ty (tcref: TyconRef)
 // IComparable<T> or IEquatable<T>. This is because whether they support these interfaces depend on their
 // constituent types, which may not yet be known in type inference.
 let rec GetImmediateInterfacesOfType skipUnref g amap m ty =
+    // TODO(vlza): Cache? Do we already do that via the importmap?
```
Comment (vzarytovskii) [inline src/Compiler/Checking/TypeHierarchy.fs:142]: That'd probably be a "no" - we don't want to cache immediate interfaces, they're quite cheap to get.

**Comment by vzarytovskii** [comment]
It helps compilation a lot.

A bunch of issues I'm not yet sure how to address:

1. If in interactive session, we use shared amap, thus there will potentially be a lot of false-positive cache hits.
2. In tooling scenario, we potentially have a lot of false-positive cache hits:
   > type `A` implements interface `IA`, we cache it.
   > interface `IA` is removed from the type `A`, it's still in the cache.
   > Any check will pass for "is `A` an `IA`".

For 1st, we can technically clean the cache on each FSI submission.

For 2nd - I am not sure what to do, since we fill in the cache on-demand. Pre-filling it will be costly and will slowdown every single compilation and check. Checking interfaces on any cache hit will neglect this optimization.

**Comment by vzarytovskii** [comment]
So, doing smarter caching now, as well as enabled it only one-off compilation, until we have proper caches in compiler.

**Comment by vzarytovskii** [comment]
@T-Gro @0101 @psfinaki @abonie @KevinRansom please, give it a glance

I don't think there's a good way of testing it automatically and deterministically.

**Review by 0101 — APPROVED** [review]

File: src/Compiler/Checking/Expressions/CheckExpressions.fs [hunk 2]
```diff
@@ -43,6 +43,7 @@ open FSharp.Compiler.TypedTreeBasics
 open FSharp.Compiler.TypedTreeOps
 open FSharp.Compiler.TypeHierarchy
 open FSharp.Compiler.TypeRelations
+open Import
```
[the remark this answers is not in the document]
Comment (vzarytovskii) [reply src/Compiler/Checking/Expressions/CheckExpressions.fs:46]: Yeah, some things have moved to imports.fs, and now it needs to be open in order to bring things into scope here.

**Comment by psfinaki** [comment]
My impression is that this change is too big to go without additional testing and the potential benefits are not worth the introduced risk. Moreover, the PR might not be easily reversible.

Especially in the light of the recent regressions in this area, I'd rather propose to take a breath here and hold a discussion on how we can actually test this. I think we would also benefit from a coming up with a list of performance testing scenarios to ensure that speeding one thing doesn't slow down something else.

This is a non-blocking opinion :shrug:

**Comment by auduchinok** [comment]
> My impression is that this change is too big to go without additional testing and the potential benefits are not worth the risk being introduced. Moreover, the PR might not be easily reversible.

Maybe we could also split the code moving into a separate PR, so it'd be easier to check/revert the actual changes?

**Comment by vzarytovskii** [comment]
> > My impression is that this change is too big to go without additional testing and the potential benefits are not worth the risk being introduced. Moreover, the PR might not be easily reversible.
> 
> 
> 
> Maybe we could also split the code moving into a separate PR, so it'd be easier to check/revert the actual changes?

It is part of change. If it to be reverted, it will need to be reverted together.

**Comment by vzarytovskii** [comment]
> My impression is that this change is too big to go without additional testing and the potential benefits are not worth the risk being introduced. Moreover, the PR might not be easily reversible.
> 
>

Huh? How is adding a cache (under a language flag) a big change? It's literary only thing it does.

> 
> Especially in the light of the recent regressions in this area, I'd rather propose to take a breath here and hold a discussion on how we can actually test this. I think we would also benefit from coming up with a list of performance testing scenarios here to ensure that speeding one thing doesn't slow down something else.
> 
> 
> 
> This is a non-blocking opinion :shrug:

Ok, feel free to propose a plan and reopen it when there's a good understanding of testing and perf scenarios.

**Comment by majocha** [comment]
I agree this is not a large change.
I think performance is one of most important elements of user experience. Every improvement here is incredibly valuable.

As for testing this, one idea is to enable this for all compilation scenarios, not just one off. More chance to spot regressions if the whole existing test suite uses this code, not just a subset.

**Comment by vzarytovskii** [comment]
> I agree this is not a large change.
> 
> I think performance is one of most important elements of user experience. Every improvement here is incredibly valuable.
> 
> 
> 
> As for testing this, one idea is to enable this for all compilation scenarios, not just one off. More chance to spot regressions if the whole existing test suite uses this code, not just a subset. 

Can't enable for one reason - we don't have a good solution for the caching in compiler, which has eviction and statistics built in. In the service scenarios, dictionary will just grow forever, since (almost) any change to the type will introduce a new instance of TType and will cache it.

File: src/Compiler/Utilities/TypeHashing.fs [hunk 3]
```diff
@@ -0,0 +1,345 @@
...
+            | PublicOnly -> true
+        | _ -> true
+
+module rec HashTypes =
+    open Microsoft.FSharp.Core.LanguagePrimitives
+
+    let stampEquals g ty1 ty2 =
+        match (stripTyEqns g ty1), (stripTyEqns g ty2) with
+        | TType_app(tcref1, _, _), TType_app(tcref2, _, _) -> tcref1.Stamp.Equals(tcref2.Stamp)
+        | TType_var(r1, _), TType_var(r2, _) -> r1.Stamp.Equals(r2.Stamp)
```
Comment (T-Gro) [inline src/Compiler/Utilities/TypeHashing.fs:132]: Reminder: Check this uses inlined equality.

File: src/Compiler/Checking/import.fs [hunk 4]
```diff
@@ -43,48 +45,101 @@ type AssemblyLoader =
...
+
+    override this.Equals other =
+        match other with
+        | :? TTypeCacheKey as p -> (this :> System.IEquatable<TTypeCacheKey>).Equals p
+        | _ -> false
+
+    override this.GetHashCode() : int =
+        let g = this.tcGlobals
+
+        let ty1 = stripTyEqns g this.ty1
```
Comment (T-Gro) [inline src/Compiler/Checking/import.fs:88]: Reminder: Deal with repetitive stripping.

File: src/Compiler/Checking/import.fs [hunk 5]
```diff
@@ -43,48 +45,101 @@ type AssemblyLoader =
...
 /// There is normally only one ImportMap for any assembly compilation, though additional instances can be created
-/// using tcImports.GetImportMap() if needed, and it is not harmful if multiple instances are used. The object 
-/// serves as an interface through to the tables stored in the primary TcImports structures defined in CompileOps.fs. 
+/// using tcImports.GetImportMap() if needed, and it is not harmful if multiple instances are used. The object
+/// serves as an interface through to the tables stored in the primary TcImports structures defined in CompileOps.fs.
 [<Sealed>]
 type ImportMap(g: TcGlobals, assemblyLoader: AssemblyLoader) =
     let typeRefToTyconRefCache = ConcurrentDictionary<ILTypeRef, TyconRef>()
 
+    let typeSubsumptionCache = ConcurrentDictionary<TTypeCacheKey, bool>()
```
Comment (T-Gro) [inline src/Compiler/Checking/import.fs:114]: Reminder - default (larger) initial size?

File: src/Compiler/TypedTree/TcGlobals.fs [hunk 6]
```diff
@@ -175,6 +175,13 @@ let tname_IsByRefLikeAttribute = "System.Runtime.CompilerServices.IsByRefLikeAtt
 // Table of all these "globals"
 //-------------------------------------------------------------------------
 
+[<RequireQualifiedAccess>]
+type CompilationMode =
+    | Unset
+    | OneOff
+    | Service
```
Comment (T-Gro) [inline src/Compiler/TypedTree/TcGlobals.fs:182]: Reminder: The Service and FSI values need to ensure their value is set, I think this is not yet being done.

File: src/Compiler/Checking/TypeRelations.fs [hunk 7]
```diff
@@ -54,80 +60,111 @@ let stripAll stripMeasures g ty =
...
+            | _ ->
+                // F# reference types are subtypes of type 'obj'
+                    if isObjTy g ty1 && (canCoerce = CanCoerce || isRefTy g ty2) then
+                        true
+                    elif isAppTy g ty2 && (canCoerce = CanCoerce || isRefTy g ty2) && TypeFeasiblySubsumesTypeWithSupertypeCheck g amap m ndeep ty1 ty2 then
+                        true
+                    else
+                        let interfaces = GetImmediateInterfacesOfType SkipUnrefInterfaces.Yes g amap m ty2
+                        // See if any interface in type hierarchy of ty2 is a supertype of ty1
+                        Seq.exists (TypeFeasiblySubsumesType (ndeep + 1) g amap m ty1 NoCoerce) interfaces
```
Comment (T-Gro) [inline src/Compiler/Checking/TypeRelations.fs:157]: List.exists stops evaluation after first `true` hit as well, so this can stay being a list (and therefore allow further consumers to used inlined List module functions on it)

File: src/Compiler/Checking/import.fs [hunk 8]
```diff
@@ -43,48 +45,101 @@ type AssemblyLoader =
...
+    val tcGlobals: TcGlobals
+
+    new (ty1, ty2, canCoerce, tcGlobals) =
+        { ty1 = ty1; ty2 = ty2; canCoerce = canCoerce; tcGlobals = tcGlobals }
+
+    interface System.IEquatable<TTypeCacheKey> with
+        member this.Equals other =
+            let ty1 = this.ty1
+            let ty2 = this.ty2
+            let otherTy1 = stripTyEqns this.tcGlobals other.ty1
```
[the remark this answers is not in the document]
Comment (vzarytovskii) [reply src/Compiler/Checking/import.fs:68]: I'm not 100% sure we need to be adding separate type here, unless we do it systematically everywhere across the whole codebase, otherwise its existence will be confusing for people. We can strip when we do type cosntruction, and don't strip it only on equality.

File: src/Compiler/Checking/import.fs [hunk 9]
```diff
@@ -43,48 +45,101 @@ type AssemblyLoader =
...
+            let otherTy2 = stripTyEqns this.tcGlobals other.ty2
+
+            if stampEquals this.tcGlobals ty1 otherTy1 && stampEquals this.tcGlobals ty2 otherTy2 && this.canCoerce = other.canCoerce then
+                true
+            else
+                (
+                    LanguagePrimitives.PhysicalEquality ty1 otherTy1
```
[the remark this answers is not in the document]
Comment (vzarytovskii) [reply src/Compiler/Checking/import.fs:75]: You mean if stamps check fails, physical equality can never be true? Not sure about it.

File: src/Compiler/Checking/import.fs (hunk 4 above)
Comment (vzarytovskii) [reply src/Compiler/Checking/import.fs:88]: Refer to previous comment about stripping.

File: src/Compiler/Checking/import.fs (hunk 5 above)
Comment (vzarytovskii) [reply src/Compiler/Checking/import.fs:114]: Yes, we probably should, it is expected to have at least `all types we use in overloads` size (I think), since we will probably check that type subsumed by `obj` at least once?

File: src/Compiler/Checking/import.fs (hunk 8 above)
[the remark this answers is not in the document]
Comment (T-Gro) [reply src/Compiler/Checking/import.fs:68]: The callsite (typeFeasibleSubsumes..) already does stripping, so even type constructor would do double work.
But I can do with a dual constructor - one that will strip, and an explicit named static method `TTypeCacheKey.FromStrippedTypes(sty1,sty2,..)` that will not do a repetitive strip.

File: src/Compiler/TypedTree/TcGlobals.fs (hunk 6 above)
Comment (vzarytovskii) [reply src/Compiler/TypedTree/TcGlobals.fs:182]: It isn't and I've done it consciously, since we specifically don't use `Service` or `Interactive` cases anywhere, hence `Unset` represents the case of "like it was before"

File: src/Compiler/Utilities/TypeHashing.fs [hunk 10]
```diff
@@ -0,0 +1,345 @@
...
+            // The 'access' means internal, but our observer can see it (e.g. because of IVT attribute)
+            | PublicAndInternal -> false
+            | PublicOnly -> true
+        | _ -> true
+
+module rec HashTypes =
+    open Microsoft.FSharp.Core.LanguagePrimitives
+
+    let stampEquals g ty1 ty2 =
+        match (stripTyEqns g ty1), (stripTyEqns g ty2) with
```
[the remark this answers is not in the document]
Comment (vzarytovskii) [reply src/Compiler/Utilities/TypeHashing.fs:130]: Refer to previous comment about stripping.

File: src/Compiler/Utilities/TypeHashing.fs (hunk 3 above)
Comment (vzarytovskii) [reply src/Compiler/Utilities/TypeHashing.fs:132]: It will use `int64` equality if I'm not mistaken.

File: src/Compiler/Checking/TypeRelations.fs (hunk 7 above)
Comment (vzarytovskii) [reply src/Compiler/Checking/TypeRelations.fs:157]: I have rewritten `GetImmediateInterfacesOfType` to return `seq` so we do not allocate the whole list and the throw it away immediately after, but removed the change to minimize the PR. Forgot to revert this place.

File: src/Compiler/Checking/import.fs (hunk 8 above)
[the remark this answers is not in the document]
Comment (vzarytovskii) [reply src/Compiler/Checking/import.fs:68]: I suppose, this is minuscule though, I doubt this will affect anything, especially in this scenario.

File: src/Compiler/Utilities/TypeHashing.fs (hunk 10 above)
[the remark this answers is not in the document]
Comment (vzarytovskii) [reply src/Compiler/Utilities/TypeHashing.fs:130]: I think it's fine here since it's a "utility" function. We don't usually assume in those if types were stripped or not. If we were to add new type, it should be done systematically across whole compiler.

**Comment by vzarytovskii** [comment]
I addressed a couple of them. I still think that it's tested enough (as good as we can), plus is hidden under flags (language and tooling), and think that we can merged it as is. But then again, if there's any pushback, happy to hear a better plan/solution to it.

File: src/Compiler/Checking/import.fs (hunk 5 above)
Comment (vzarytovskii) [reply src/Compiler/Checking/import.fs]: Put 1024 by default with processor counts

File: src/Compiler/Checking/import.fs [hunk 11]
```diff
@@ -43,48 +45,96 @@ type AssemblyLoader =
...
+    interface System.IEquatable<TTypeCacheKey> with
+        member this.Equals other =
+            if stampEquals this.tcGlobals this.ty1 other.ty1 && stampEquals this.tcGlobals this.ty2 other.ty2 && this.canCoerce = other.canCoerce then
+                true
+            else
+                (
+                    LanguagePrimitives.PhysicalEquality this.ty1 other.ty1
+                    && LanguagePrimitives.PhysicalEquality this.ty2 other.ty2
+                    && this.canCoerce = other.canCoerce
+                )
```
Comment (T-Gro) [inline src/Compiler/Checking/import.fs:76]:
```suggestion
            if this.canCoerce <> other.canCoerce then
                false
            elif this.ty1 === other.ty1 && this.ty2 === other.ty2  then
                true 
            else 
                stampEquals this.tcGlobals this.ty1 other.ty1 && stampEquals this.tcGlobals this.ty2 other.ty2                
```


Might need an open for === (physical equality). I wrote that in plain text.
Physical equality of instances is the easiest case and covers also stamp equals, so should come first (if instances are equal, their stamp would be equal too).

Putting canCoerce first (will be branch predicted) so that other conditions can be shorted and do not have to repeat it.

File: src/Compiler/Checking/import.fs [hunk 12]
```diff
@@ -43,48 +45,96 @@ type AssemblyLoader =
...
+    override this.Equals other =
+        match other with
+        | :? TTypeCacheKey as p -> (this :> System.IEquatable<TTypeCacheKey>).Equals p
+        | _ -> false
+
+    override this.GetHashCode() : int =
+        let g = this.tcGlobals
+
+        let ty1Hash = combineHash (hashStamp g this.ty1) (hashTType g this.ty1)
+        let ty2Hash = combineHash (hashStamp g this.ty1) (hashTType g this.ty2)
```
Comment (T-Gro) [inline src/Compiler/Checking/import.fs:87]:
```suggestion
        let ty2Hash = combineHash (hashStamp g this.ty2) (hashTType g this.ty2)
```

**Comment by vzarytovskii** [comment]
This is ready @dotnet/fsharp-team-msft

**Review by T-Gro — APPROVED** [review]

**Comment by gusty** [comment]
It would be interesting to see if there's any perf gain when comparing to .net6/.net7 ?
Or does the optimized code not even exists there?

**Comment by vzarytovskii** [comment]
> It would be interesting to see if there's any perf gain when comparing to .net6/.net7 ?
> 
> Or does the optimized code not even exists there?

Will generally be minimal, because bcl there didn't have such large type hierarchies.

**Comment by vzarytovskii** [comment]
An important note: this will only be in `preview` language version and only in compilation (not tooling), to enable it in tooling, there needs to be a good caching solution in the compiler (as opposed to just concurrent dictionary), otherwise, in tooling scenarios, it will grow indefinitely.
