### PR TITLE
Fix missing message with type error (FS0001)

### LINKED ISSUE #17373: Missing message with type error (FS0001)
Building (`dotnet build`) the attached project prints at the console an error FS0001 with a location in Program.fs, but does not print an message informative message. I would expect a message along the lines of 

foo expects a `seq<'a * 'b * 'c>`, but is called with a `seq<'a * 'b>`

I'm using compiler version 12.8.300.0 for F# 8.0. The product version of fsc.exe is "12.8.300-beta.24228.1+dd749058c91585e9b5dae62b0f8df892429ee28f"
[errmsg.zip](https://github.com/user-attachments/files/16045758/errmsg.zip)

### PR DESCRIPTION
**Pull request by edgarfgp**
## Description

```fsharp
let foo items =
    for (a,b,c) in items do
        printfn "%A" (a, c)

[<EntryPoint>]
let main args =
    foo ({1..10} |> Seq.pairwise) // Failed miserably  with error number FS0001 but not actual error message 
    0
```

### Before
 - (Error 1, Line 8, Col 21, Line 8, Col 33, "") 

### After
- (Error 1, Line 8, Col 21, Line 8, Col 33, "The tuples have differing lengths of 3 and 2")

Fixes #17373

## Checklist

- [x] Test cases added
- [x] Release notes entry updated

### CODE REVIEW

**Comment by majocha** [comment]
Would be nice to indicate which length is expected.

**Review by vzarytovskii — APPROVED** [review]

File: src/Compiler/Driver/CompilerDiagnostics.fs [hunk 1]
```diff
@@ -826,6 +826,11 @@ type Exception with
                     else
                         os.AppendString(FSComp.SR.listElementHasWrongTypeTuple messageArgs)
                 | _ -> os.AppendString(ErrorFromAddingTypeEquationTuplesE().Format tl1.Length ty1 tl2.Length ty2 tpcs)
+            else
+                os.AppendString(ConstraintSolverTupleDiffLengthsE().Format tl1.Length tl2.Length)
+
+                if m1.StartLine <> m2.StartLine then
+                    os.AppendString(SeeAlsoE().Format(stringOfRange m1))
```
Comment (auduchinok) [inline src/Compiler/Driver/CompilerDiagnostics.fs:833]: @edgarfgp Could you add some cases covering this check, please?
