### PR TITLE
Fix #17903

### LINKED ISSUE #17903: Inline functions in a referenced project optimized incorrectly
In the attached example, we create three types; 
- ID, in ClassLibrary1
- ID2, in ClassLibrary1, which relies on ID
- ID3 in ConsoleApp1, which relies on ID2.

In each of these we override equality and comparison operators, using inline functions to improve performance for ID3. (Note that this repro is a minimal example from more complicated code where this makes more sense!)

We create instances of each in the console app. and check that two unequal values of each type are reported as unequal by the compiler.
In Release mode only, the third assertion, that two obviously different instances of ID3 are unequal fails.

To repro, please run the attached program.
[repro.zip](https://github.com/user-attachments/files/17460199/repro.zip)

**Expected behavior**

I expect the program to exit with code 0.

**Actual behavior**

An exception is thrown in the last equality check, for `aBarBar` versus `bBarBar`

**Known workarounds**

Running this in debug mode fixes the issue.
Putting the definitions of ID and ID2 in the same project as ID3 fixes the issue. Because of this, I suspect this issue is something to do with incorrect optimisations around inlining functions from other projects.
Changing ID from a struct into a class by removing all the attributes associated with it fixes the issue.

**Related information**

Tested in .NET 8, SDKs 8.0.100 and 8.0.403
Windows 10.
VS 2022 for editing.

### PR DESCRIPTION
**Pull request by vzarytovskii**
Fixes #17903. Test is missing, checking the waters.

The idea of the fix is pretty dumb. The `copyOfStruct` address is leaking outside the scope which trips the locals reuse algorithm. After looking more into it, and chatting with Don, I decided to mark `copyOfStruct` as no-reuse, but keeping it in cgbuf cache.

### CODE REVIEW

File: src/Compiler/CodeGen/IlxGen.fs [hunk 1]
```diff
@@ -2651,18 +2651,18 @@ type CodeGenBuffer(m: range, mgbuf: AssemblyBuilder, methodName, alreadyUsedArgs
 
     member _.PreallocatedArgCount = alreadyUsedArgs
 
-    member _.AllocLocal(ranges, ty, isFixed) =
+    member _.AllocLocal(ranges, ty, isFixed, canBeReallocd) =
```
Comment (0101) [inline src/Compiler/CodeGen/IlxGen.fs:2654]: Could be an optional parameter with default `true`.

File: src/Compiler/CodeGen/IlxGen.fs [hunk 2]
```diff
@@ -2651,18 +2651,18 @@ type CodeGenBuffer(m: range, mgbuf: AssemblyBuilder, methodName, alreadyUsedArgs
...
+        locals.Add((ranges, ty, isFixed, canBeReallocd))
         j
 
-    member cgbuf.ReallocLocal(cond, ranges, ty, isFixed) =
+    member cgbuf.ReallocLocal(cond, ranges, ty, isFixed, canBeReallocd) =
         match ResizeArray.tryFindIndexi cond locals with
         | Some j ->
-            let prevRanges, _, isFixed = locals[j]
-            locals[j] <- ((ranges @ prevRanges), ty, isFixed)
+            let prevRanges, _, isFixed, canBeReallocd = locals[j]
```
Comment (0101) [inline src/Compiler/CodeGen/IlxGen.fs:2662]: Do we really want to shadow `canBeReallocd` here? Shouldn't the one that came as function argument be stored? Presumably the one already in `locals` is `true`, since we're reallocating it, but the incoming one could be `false`?

```suggestion
            let prevRanges, _, isFixed, _ = locals[j]
```

**Review by 0101 — COMMENTED** [review]
A test would be nice.

**Comment by vzarytovskii** [comment]
@0101 @T-Gro added a test, ready now.

**Comment by vzarytovskii** [comment]
It's hitting some awkward ILVerify error, which I don't yet understand. Gonna dig more into it.

**Comment by vzarytovskii** [comment]
Alright, so the failing baseline was due to the offset of the instruction (by 2 bytes), which can signal for the local realloc. I would like to run it here a bunch of times to see if it's some kind of "parallel ilxgen" issue with realloc caches.

**Review by T-Gro — APPROVED** [review]
