### PR TITLE
don't auto-resolve types from System.Runtime.WindowsRuntime

### LINKED ISSUE #9206: F# interactive regression on autocomplete suggestion
Autocompletion on fsi fails on certain types with dotnet sdk 3.1.202. This doesn't appear to appear on 3.1.102 however

**Repro steps**

Provide the steps required to reproduce the problem:

1. open `dotnet fsi` in a terminal.
2. type the following
```fsharp
open System;;
let time = TimeSpan.FromHours(1.0);;
```
3. Now type `time.` and try to autocomplete with `TAB` key. And observe the following error:
```
stdin(0,1): error FS1108: The type 'IAsyncOperationWithProgress`2' is required here and is unavailable. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'.
```

**Expected behavior**

Should now throw the FS1108 error and should autocomplete the `TimeSpan` object.

**Actual behavior**

```
stdin(0,1): error FS1108: The type 'IAsyncOperationWithProgress`2' is required here and is unavailable. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'.
```

**Known workarounds**

Use dotnet sdk 3.1.102

**Related information**

Provide any related information (optional):

* Operating system: Windows, Linux
* .NET Runtime kind: .NET Core
* Editing Tools: Terminal, (I got the bug in Jetbrains Rider as well, working with fsx files )
image

### PR DESCRIPTION
**Pull request by brettfo**
When `fsi` is started it crawls the runtime directories and creates a map of short assembly names to file paths, e.g., `System.Drawing` => `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.5\System.Drawing.dll`.  The assembly `System.Runtime.WindowsRuntime` includes some extension methods to make WinRT async operations behave like a regular C# `Task` (see [here](https://docs.microsoft.com/en-us/dotnet/api/system.windowsruntimesystemextensions.astask?view=dotnet-plat-ext-3.1#System_WindowsRuntimeSystemExtensions_AsTask__2_Windows_Foundation_IAsyncOperationWithProgress___0___1__System_Threading_CancellationToken_System_IProgress___1__)).

By delving into that assembly to find its types the `fsi` runtime inadvertently takes a dependency on the Windows SDK via `Windows.md`, but since that file isn't in the probed directories, and isn't necessarily even on the machine, any attempt to resolve types from the Windows SDK will fail.  Mix this behavior with the fact that the offending `Task`-like extension methods are brought into scope simply via `open System`, it's best to avoid loading that assembly all together.

Future versions of the .NET SDK will remove implicit WinRT support (dotnet/runtime#36715) so it makes sense to remove it from the main branch since this is only auto-flowing into branches that will ship with .NET 5 anyway.

Fixes #9206.

### CODE REVIEW

File: src/fsharp/DotNetFrameworkDependencies.fs [hunk 1]
```diff
@@ -259,10 +259,22 @@ module internal FSharp.Compiler.DotNetFrameworkDependencies
             if not (assemblies.ContainsKey(referenceName)) then
                 try
                     if File.Exists(path) then
-                        // System.Private.CoreLib doesn't load with reflection
-                        if referenceName = "System.Private.CoreLib" then
+                        match referenceName with
```
Comment (KevinRansom) [inline src/fsharp/DotNetFrameworkDependencies.fs:262]: Probably: System.Runtime.WindowsRuntime.UI.Xaml.dll

Comment (brettfo) [reply src/fsharp/DotNetFrameworkDependencies.fs:262]: Done.

**Comment by Thorium** [comment]
Has there been name changes on these recently? "Windows.dll" ? "Microsoft.Windows.SDK.NET.dll" ?
