### PR TITLE
Bugfix :: Nullness :: Bug selection

### LINKED ISSUE #17539: Nullness issue - ToString on an integer with UoM takes nullness information from ValueType
### Issue description

image

Similarly with UMX when the underlying type is a reference type, nullness is inherited from `Object.ToString`, rather than the underlying type, whose overriden `ToString` is not null.

### Choose one or more from the following categories of impact

- [X] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [ ] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [ ] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [ ] C#/F# interop issue related to nullness metadata.
- [ ] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### .NET Runtime/SDK version

9.0.0-preview.7.24405.7

### Reproducible code snippet and actual behavior

```fsharp
> (1).ToString();;
val it: string = "1"

> [<Measure>] type id;;
[<Measure>]
type id

> 1<id>.ToString ();;
val it: string | null = "1"
```

### Possible workarounds

_No response_

### LINKED ISSUE #18013: Nullness issue - Error shows on incorrect symbol when using |>
### Issue description

When using the |> operator on a partially applied function, the compiler will show a red squiggle on the RHS rather than the LHS.

### Choose one or more from the following categories of impact

- [ ] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [ ] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [ ] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [ ] C#/F# interop issue related to nullness metadata.
- [x] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### .NET Runtime/SDK version

_No response_

### Reproducible code snippet and actual behavior

Wrong (current behaviour):

```fsharp
let foo a b = "hello" + a + b
let bar : string | null = "test"
let result = bar |> foo "mr" // red squiggly shows incorrectly on 'foo mr'
```

### Possible workarounds

Don't use `|>`

```fsharp
let foo a b = "hello" + a + b
let bar : string | null = "test"
let result = foo "mr" bar // red squiggly shows correctly on 'bar`
```

### LINKED ISSUE #18021: Nullness issue - No way to silence warning in e.g. ServiceCollection.AddSingleton if type allows null
### Issue description

Consider this code as a placeholder for a type defined in an external library:

```f#
[<AllowNullLiteral>]
type IInterfaceFromExternalPackage = interface end

[<AllowNullLiteral>]
type ImplementorFromExternalPackage() =
    interface IInterfaceFromExternalPackage
```

Now consider the following:

```f#
open Microsoft.Extensions.DependencyInjection

ServiceCollection().AddSingleton<IInterfaceFromExternalPackage>(ImplementorFromExternalPackage())
```

This causes a compiler warning:

> FS3261 : Nullness warning: The type 'IInterfaceFromExternalPackage' supports 'null' but a non-null type is expected.

Of course, there is no actual nullness issue here since I pass a non-null (singleton) instance of the type. However, I can find no way of silencing this warning apart from disabling it entirely for the file.

### Choose one or more from the following categories of impact

- [x] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [ ] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [ ] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [x] C#/F# interop issue related to nullness metadata.
- [ ] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### .NET Runtime/SDK version

.NET SDK 9.0.100

### Reproducible code snippet and actual behavior

_No response_

### Possible workarounds

_No response_

### LINKED ISSUE #18334: Nullness issue – invalid type constraint resolution on `ILookup`
``` F#
open System
open System.Collections.Generic
open System.Linq

module Extensions =

    type ILookup<'Key, 'Value when 'Key : not null> with

        static member Empty = Seq.empty<KeyValuePair<'Key, 'Value>>.ToLookup(_.Key, _.Value)

        member lookup.RemoveKey (key : 'Key) =
            lookup
            |> Seq.where (fun g -> 'Key.Equals(g.Key, key))
            |> Seq.collect (fun g -> g |> Seq.map (fun v -> KeyValuePair(g.Key, v)))
            |> _.ToLookup(_.Key, _.Value)
```
displays:
* `error FS0957: One or more of the declared type parameters for this type extension have a missing or wrong type constraint not matching the original type constraints on 'ILookup<_,_>'`
* `error FS0340: The signature and implementation are not compatible because the declaration of the type parameter 'Key' requires a constraint of the form 'Key: not null`
while the required type constraint is present

**Repro steps**

use the uploaded class library project
[WrongNonNullConditionRepro.zip](https://github.com/user-attachments/files/18925391/WrongNonNullConditionRepro.zip)

**Expected behavior**

No error

**Actual behavior**

* `error FS0957: One or more of the declared type parameters for this type extension have a missing or wrong type constraint not matching the original type constraints on 'ILookup<_,_>'`
* `error FS0340: The signature and implementation are not compatible because the declaration of the type parameter 'Key' requires a constraint of the form 'Key: not null`

**Known workarounds**

No

**Related information**

Provide any related information (optional):

* .NET 8
* Visual Studio 2022 17.13.1

### LINKED ISSUE #19042: Nullness issue - type check in multi-match expressions doesn't eliminate null
### Issue description

I expect that type check in multi-match expressions eliminates nulls after check just like in simple match cases.

### Choose one or more from the following categories of impact

- [x] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [ ] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [x] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [ ] C#/F# interop issue related to nullness metadata.
- [ ] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### .NET Runtime/SDK version

.NET SDK 10.0.100-rc.2.25502.107

### Reproducible code snippet and actual behavior

```fsharp
let test (s: string) =
    ()

[<EntryPoint>]
let main argv =
    let x = true
    let y: string | null = ""
    match x, y with
    | true, _ -> ()
    | false, null -> ()
    | false, s -> test s

    0
```
`s` type is mistakenly resolved as `string | null`

### Possible workarounds
```fsharp
let test (s: string) =
    ()

[<EntryPoint>]
let main argv =
    let x = true
    let y: string | null = ""
    match x with
    | true -> ()
    | false, Null -> ()
    | false, NonNull s -> test s
    0
```

### PR DESCRIPTION
**Pull request by T-Gro**
## Description

Five nullness-related bug fixes and two regression tests for the F# compiler's nullable reference type checking.

### Bug Fixes

1. **UoM ToString returns `string` for value types** (fixes #17539)
   - `int<kg>.ToString()` now returns `string` instead of `string | null`
   - Added `isMeasureableValueType` helper in `TypedTreeOps.fs`
   - Extended the ToString return-type override in `MethodCalls.fs` to cover measureable value types

2. **Pipe operator nullness warning location** (fixes #18013)
   - Nullness warnings from piped expressions (e.g. `bar |> foo "mr"`) now point at the nullable argument (`bar`) instead of the pipe operator
   - Added `NullnessCheckOfCapturedArg` context to `ConstraintSolver`, propagated through `CheckExpressions.fs`

3. **AllowNullLiteral false positive on non-null instances** (fixes #18021)
   - `MyClass()` where `MyClass` has `[<AllowNullLiteral>]` no longer triggers a false nullness warning
   - Rewrote `TypeNullIsExtraValueNew` to check explicit nullness annotation first, only falling back to `AllowNullLiteral` when nullness is ambivalent

4. **`not null` constraint on type extensions** (fixes #18334)
   - `type ILookup<'Key, 'Value when 'Key : not null> with ...` no longer errors
   - Added `typarsAEquivWithAddedNotNullConstraintsAllowed` for extension checks
   - Fixed letrec binding fixup to strip/restore extra not-null constraints during `CheckTypars`

5. **Tuple null elimination over-inference** (fixes #19042)
   - `match x, y with | null, _ -> ... | s, 5 -> test s` no longer over-infers non-null when non-wild patterns restrict non-nullable elements
   - Simplified the tuple null elimination condition

### Regression Tests (no code changes, tests only)
- **#17727**: `Option.toObj` inference - ensures input is inferred as `string option`, not `string | null option`
- **#18034**: FSharpPlus-style SRTP `Delay` in monad CE - ensures no crash with or without nullness

### Changed Files (13 total)

**Source (10 files):**
- `src/Compiler/Checking/CheckDeclarations.fs`
- `src/Compiler/Checking/ConstraintSolver.fs` + `.fsi`
- `src/Compiler/Checking/Expressions/CheckExpressions.fs`
- `src/Compiler/Checking/MethodCalls.fs`
- `src/Compiler/Driver/CompilerDiagnostics.fs`
- `src/Compiler/Symbols/FSharpDiagnostic.fs`
- `src/Compiler/TypedTree/TypedTreeOps.fs` + `.fsi`

**Tests (3 files):**
- `tests/FSharp.Compiler.ComponentTests/Language/Nullness/NullableReferenceTypesTests.fs` (704 lines added)
- 3 BSL files updated for changed error locations/baselines

**Release notes:**
- `docs/release-notes/.FSharp.Compiler.Service/10.0.300.md`

### CODE REVIEW

File: src/Compiler/Checking/Expressions/CheckExpressions.fs [hunk 1]
```diff
@@ -470,6 +470,12 @@ type CheckedBindingInfo =
 
 type cenv = TcFileState
 
+/// Extract nullness-specific context, filtering out all other context kinds to avoid side effects on non-nullness diagnostics.
```
Comment (abonie) [inline src/Compiler/Checking/Expressions/CheckExpressions.fs]:
```suggestion
// Extract nullness-specific context, filtering out all other context kinds to avoid side effects on non-nullness diagnostics.
```
