### PR TITLE
Recognize IsByRefLikeAttribute from user code.

### LINKED ISSUE #8564: The compiler does not recognize a user-provided IsByRefLike attribute as special.
Let's take a look at the following code snippet:

``` fsharp
namespace System.Runtime.CompilerServices

open System

[<AttributeUsage(AttributeTargets.All, AllowMultiple = false)>]
[<Sealed>]
type IsReadOnlyAttribute() =
    inherit System.Attribute()

[<AttributeUsage(AttributeTargets.All, AllowMultiple = false)>]
[<Sealed>]
type IsByRefLikeAttribute() =
    inherit System.Attribute()

namespace global

open System
open System.Runtime.CompilerServices

[<IsByRefLike; Struct>]
[<NoEquality; NoComparison>] // Not setting these attributes in .NET Core crashes with a different error.
type MyRefStruct(data: int) =
    member x.Data = data

module Program =
    [<EntryPoint>]
    let main _ =
        let x = MyRefStruct(521)
        Console.WriteLine(box x)
        0
```

We define our own `System.Runtime.CompilerServices.IsByRefLikeAttribute` type (as frameworks that do not bundle it do), and defined a simple ref struct containing an integer. In our entry point, we create such a ref struct on the stack, box it, and print it on the console.

Clearly, this is forbidden. However the compiler gladly allows it without shedding a tear.

If we run the program, the results vary depending on the framework.

* On .NET Framework, the program successfully runs, printing `MyRefStruct`. It looks like that ref structs are a compiler's construct, and their embargo from the heap is not enforced, supposedly for compatibility reasons.

* On .NET Core (at least in versions 2.1 and 3.1), the program crashes with an explanatory message:

```
Unhandled Exception: System.InvalidProgramException: Cannot create boxed ByRef-like values.
   at Program.main(String[] _arg1)
```

`MyRefStruct` is considered a ref struct by decompilers and .NET Core's runtime. The compiler however is not aware of that, and does not fail when a ref struct gets boxed.

It gets even worse. Let's change `MyRefStruct` into this:

```
[<IsByRefLike; Struct>]
[<NoEquality; NoComparison>]
type MyRefStruct(data: Span<int>) =
    member x.Data = data

// We can even remove the entry point
```

That was a ref struct holding another ref struct. Totally fine for the runtime. The compiler however, because she does not know that `MyRefStruct` is a ref struct, does not allow it to hold a `Span` saying that `A type would store a byref typed value. This is not permitted by Common IL.`.

---

All these problems are caused because we used our own `IsByRefLikeAttribute`. If we remove the attribute definitions and use those provided by the framework, everything runs fine.

The problem is for those who target frameworks that are not bundling that attribute, like .NET Framework versions before 4.7.1, or worse, the widely used .NET Standard 2.0.

What is more, the fact that .NET Framework is _not_ enforcing those rules in runtime can lead to nasty and hard-to-diagnose bugs.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
Fixes #8564.

This PR adds support to define ref structs on assemblies targeting frameworks that do not have the `System.Runtime.CompilerServices.IsByRefLikeAttribute` defined, namely .NET Standard 2.0 and .NET Framework versions earlier than 4.7.1, by recognizing the attribute defined by the users themselves.

The logic of `isByrefLikeTyconRef` is updated to find the attribute _by name_, instead of finding a specific attribute type on a system assembly. Consequently, the `TcGlobals.attrib_IsByRefLikeAttribute` property was removed and replaced by a `tname_IsByRefLikeAttribute` constant containing the attribute's full name, and code trying to find that specific attribute was updated to call `isByrefLikeTyconRef`, benefiting from caching the result of the lookup.

~~A check that the attribute is applied on non-struct types was moved from the post-inference checks to the `isByrefLikeTyconRef` function to consolidate the attribute's existence check.~~ Reverted

---

I was going to do the same with the `IsReadOnlyAttribute` but it was more complicated since it might get emitted (not just checked), and such deficiency has almost zero impact.

---

I will also need some help on testing this change.

### CODE REVIEW

**Comment by TIHan** [comment]
It does make sense to check for the name. C# compiler will emit its own `IsByRefLikeAttribute` if it can't find it in the referenced assemblies when trying to declare a ref-struct. 

For F#, since it doesn't use a keyword, adding the attribute ourselves and trying to use it makes sense.

**Comment by teo-tsirpanis** [comment]
@cartermp it now (almost) works, could you review it?

[There is a test](https://github.com/dotnet/fsharp/blob/a70f3beacfe46bcd653cc6d525bd79497e6dd58e/tests/fsharp/Compiler/Language/SpanOptimizationTests.fs#L116) that defines a ref struct with a custom attribute and assumes the compiler will not treat it specially. What to do with that?

And I would appreciate some help on what kinds of tests to add and how.

**Comment by teo-tsirpanis** [comment]
@dsyme (I don't know who to tag) could you please take a look?

**Comment by dsyme** [comment]
@teo-tsirpanis 

Your code looks fine, just adjust the tests to get it green

> There is a test that defines a ref struct with a custom attribute and assumes the compiler will not treat it specially. What to do with that? 

I guess change the thing the test checks for so that the new behaviour is noted

> Another test that assumes the previous behavior is affected as well.

Delete this test I guess or at least remove the part of it that's relevant

**Comment by teo-tsirpanis** [comment]
@dsyme, phew, the tests are now finally green. 😌 Thanks for looking at it.

File: src/fsharp/TypedTreeOps.fs [hunk 1]
```diff
@@ -3200,7 +3222,12 @@ let isByrefLikeTyconRef (g: TcGlobals) m (tcref: TyconRef) =
     | _ -> 
        let res = 
            isByrefTyconRef g tcref ||
-           (isStructTyconRef tcref && TyconRefHasAttribute g m g.attrib_IsByRefLikeAttribute tcref)
+           (match isStructTyconRef tcref, TyconRefHasAttributeByName m tname_IsByRefLikeAttribute tcref with
+            | true, hasAttr -> hasAttr
+            | false, hasAttr ->
+                if hasAttr then
+                    errorR(Error(FSComp.SR.tcByRefLikeNotStruct(), tcref.Deref.Range))
```
Comment (TIHan) [inline src/fsharp/TypedTreeOps.fs:3229]: Usually we do not raise errors in functions like this - the check should go back in PostInferenceChecks.

File: src/fsharp/TcGlobals.fs [hunk 2]
```diff
@@ -1190,7 +1192,6 @@ type public TcGlobals(compilingFslib: bool, ilg:ILGlobals, fslibCcu: CcuThunk, d
 
   // We use 'findSysAttrib' here because lookup on attribute is done by name comparison, and can proceed
   // even if the type is not found in a system assembly.
-  member val attrib_IsByRefLikeAttribute  = findSysAttrib "System.Runtime.CompilerServices.IsByRefLikeAttribute"
```
Comment (TIHan) [inline src/fsharp/TcGlobals.fs:1193]: I guess it does make sense to not have the instance of the attribute here as it's only for IL types; we wanted to expand the checks to cover IL and F# versions of the IsByRefLikeAttribute.

File: src/fsharp/TypedTreeOps.fs [hunk 3]
```diff
@@ -3183,6 +3183,28 @@ let TyconRefHasAttribute g m attribSpec tcref =
                     (fun _ -> Some ())
         |> Option.isSome
 
+/// Check if a type definition has an attribute with a specific full name
+let TyconRefHasAttributeByName (m: range) attrFullName (tcref: TyconRef) =
```
Comment (TIHan) [inline src/fsharp/TypedTreeOps.fs:3187]: At first I thought this would be expensive every time `isByRefLikeTyconRef` is called, but we cache the result once the type has been checked the first time via: `tcref.SetIsByRefLike`

File: src/fsharp/AugmentWithHashCompare.fs [hunk 4]
```diff
@@ -823,7 +823,7 @@ let TyconIsCandidateForAugmentationWithCompare (g: TcGlobals) (tycon: Tycon) =
     // This type gets defined in prim-types, before we can add attributes to F# type definitions
     let isUnit = g.compilingFslib && tycon.DisplayName = "Unit"
     not isUnit && 
-    not (TyconRefHasAttribute g tycon.Range g.attrib_IsByRefLikeAttribute (mkLocalTyconRef tycon)) &&
+    not (isByrefLikeTyconRef g tycon.Range (mkLocalTyconRef tycon)) &&
```
[the remark this answers is not in the document]
Comment (teo-tsirpanis) [reply src/fsharp/AugmentWithHashCompare.fs:826]: And efficient; it was ignoring the cached result.

File: src/fsharp/TypedTreeOps.fs (hunk 1 above)
Comment (teo-tsirpanis) [reply src/fsharp/TypedTreeOps.fs]: Done @TIHan.

**Comment by baronfel** [comment]
@dsyme clarifying question here: 'next release after' means the `6.1.2xx` train?

**Comment by dsyme** [comment]
> @dsyme clarifying question here: 'next release after' means the 6.1.2xx train?

I'd imagine so though I don't specifically know - F# bits ship in both .NET SDK and VS and @brettfo might be able to say

**Comment by brettfo** [comment]
@baronfel @dsyme "next release after" should be 6.0.2xx.

**Comment by TIHan** [comment]
> We need to decide if it goes under a language feature flag

ByRefLike types were introduced early on, before F# 4.7. We already recognize ByRefLikeAttributes, just not a user-defined version of it. I think this was an oversight on our part and we should consider this a bug fix related to that feature.

File: tests/fsharp/Compiler/Language/SpanTests.fs [hunk 5]
```diff
@@ -160,4 +160,19 @@ let f (x: TA) = ()
             [|
                 FSharpDiagnosticSeverity.Error, 3300, (6, 8, 6, 9), "The parameter 'x' has an invalid type 'TA'. This is not permitted by the rules of Common IL."
             |]
+
+    [<Test>]
+    let ``A custom IsByRefLikeAttribute can define a ref struct``() =
```
[the remark this answers is not in the document]
Comment (teo-tsirpanis) [reply tests/fsharp/Compiler/Language/SpanTests.fs:165]: How to do that? Can you help me?

**Comment by teo-tsirpanis** [comment]
OK @TIHan, I added the test. Can you please take a look?

File: tests/FSharp.Core.UnitTests/FSharp.Core.UnitTests.fsproj [hunk 6]
```diff
@@ -38,6 +38,7 @@
     <Compile Include="FSharp.Core\ComparersRegression.fs" />
     <Compile Include="FSharp.Core\DiscriminatedUnionType.fs" />
     <Compile Include="FSharp.Core\RecordTypes.fs" />
+    <Compile Include="FSharp.Core\RefStructs.fs" Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'" />
```
Comment (vzarytovskii) [inline tests/FSharp.Core.UnitTests/FSharp.Core.UnitTests.fsproj:41]: It's rather a nitpick, but I would rather put the test as a whole into `#if NETCOREAPP`, than specifying it in the project file, it's bit more visible when you're looking at it. Other than that - looks good to me.

**Review by vzarytovskii — APPROVED** [review]

File: tests/FSharp.Core.UnitTests/FSharp.Core.UnitTests.fsproj (hunk 6 above)
Comment (teo-tsirpanis) [reply tests/FSharp.Core.UnitTests/FSharp.Core.UnitTests.fsproj]: Fixed.

**Comment by teo-tsirpanis** [comment]
All tests are now green.

**Comment by vzarytovskii** [comment]
Thanks, that looks good!
