### PR TITLE
Emit compact IL code for unsigned 64-bit constants

### LINKED ISSUE #8683: uint64 literals generate suboptimal IL code
**Repro steps**

Consider this function:

``` fsharp
let inc x = x + 1UL
```

Now look at the generated IL code:

**Expected behavior**

```
IL_0000: ldarg.0
IL_0001: ldc.i4.1
IL_0002: conv.u8
IL_0003: add
IL_0004: ret
```

This is what C# generates. Generally, it should emit `ldc.i4.#`/`ldc.i4.s`/`ldc.i4` with a `conv`, and only if the number is even bigger should it emit `ldc.i8`.

**Actual behavior**

```
IL_0000: ldarg.0
IL_0001: ldc.i8 1
IL_000a: add
IL_000b: ret
```

The function's IL code takes 12 bytes, instead of 5, as expected. This might interfere with the JIT's decision to inline small functions.

**Known workarounds**

``` fsharp
let inc x = x + (uint64 1)
```

**Related information**

This happens only with `uint64` literals. Literals of all other integral types (including signed `int64`) emit optimal code.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
This PR essentially applies the fixes of #3620 to all 64-bit integers and thus closes #8683.

### CODE REVIEW

File: src/fsharp/IlxGen.fs [hunk 1]
```diff
@@ -2440,24 +2440,27 @@ and GenConstant cenv cgbuf eenv (c, m, ty) sequel =
...
           GenExpr cenv cgbuf eenv SPSuppress e Continue
       | None ->
-          match c with
-          | Const.Bool b -> CG.EmitInstr cgbuf (pop 0) (Push [g.ilg.typ_Bool]) (mkLdcInt32 (if b then 1 else 0))
-          | Const.SByte i -> CG.EmitInstr cgbuf (pop 0) (Push [ilTy]) (mkLdcInt32 (int32 i))
-          | Const.Int16 i -> CG.EmitInstr cgbuf (pop 0) (Push [ilTy]) (mkLdcInt32 (int32 i))
-          | Const.Int32 i -> CG.EmitInstr cgbuf (pop 0) (Push [ilTy]) (mkLdcInt32 i)
-          | Const.Int64 i ->
-            // see https://github.com/Microsoft/visualfsharp/pull/3620
+          let emitLongConstant i =
```
Comment (TIHan) [inline src/fsharp/IlxGen.fs]: nit: We normally don't use the name `Long` to represent a 64-bit int. I suggest re-name this to `emitInt64Constant`.

Comment (teo-tsirpanis) [reply src/fsharp/IlxGen.fs]: I had been inspired by Roslyn and gave it that name. It sounded a but uncanny to me as well, but it's now fixed.
