### PR TITLE
Fix issue with tests, see #9617

### LINKED ISSUE #9617: Help wanted: how to run ExprTests in CompilerService, keep getting The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: Exception of type 'FSharp.Compiler.ErrorLogger+UnresolvedPathReferenceNoRange' was thrown.)
Blocks: https://github.com/dotnet/fsharp/pull/9549

I've tried several ways to run these tests. From the commandline, I believe they're part of the `FSharpQA` tests, and they crash, plus the failing tests just say "failed". When running them from the Tests window in VS, I found that they all fail in `GetOptimizedAssemblyContents()` with the error:

> The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: Exception of type 'FSharp.Compiler.ErrorLogger+UnresolvedPathReferenceNoRange' was thrown.)

I don't understand this error...

**Repro steps**

Use this PR: https://github.com/dotnet/fsharp/pull/9549. Then:

Rebuild All -> Run test "Test Operator Declarations for Byte" (or any other test in that file).

The error does not occur if I use a master branch, I assume that's because the generated IL is different. But instead of getting an error on the expected output, I get the error shown above. 

**Expected behavior**

That there's at least **one way** of running these tests properly, and seeing output on what fails and why. CI raises the same exception, see for instance this log dump: https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/715859/logs/117 (search for `FSharp.Compiler.ErrorLogger+ReportedError`).

**Actual behavior**

The following line (bottom) always seems to balk at me:

https://github.com/dotnet/fsharp/blob/b17ecf25acb37af1bb68d09456c7685ca5139e7a/tests/service/ExprTests.fs#L941-L951

**Known workarounds**

Not yet...

**Related information**

I also notice that more often than not, Visual Studio keeps a lock on `DummyProviderForLanguageServiceTesting.dll`, which makes debug-fix-rebuild impossible (closing VS doesn't always help here...). This sounds like there needs to be a `try-finally` added somewhere.

Running the tests through <kbd>Ctrl+F5</kbd> in a new VS 2019 instance leads to the same error.

I think this function and tests were introduced here: https://github.com/dotnet/fsharp/pull/3784, @forki, do you know why I keep getting the `UnresolvedPathReferenceNoRange` and what to do about it? It sounds like some reference is not what is expected.

### PR DESCRIPTION
**Pull request by abelbraaksma**
Fixes #9617

This is an attempt to create better output on failing tests in ExprTests.fs, and this method may be useful for other tests in the CompilerService area:

* Instead of printing a big blob, now shows the exact line where a difference exists if test fails
* Re-enables and fixes two smoke-tests that seem to work now (may need disable for Mono)
* All temp files go in one location now, and are cleaned afterwards (function is in util location, easy to disable while debugging)
* This file used global state and module-level file-create inside global values. This is now delayed to allow proper cleanup and introspection
* Dump of referenced assemblies to help solve assembly-reference issues (like I suffered in #9617), and any reference-related errors now print the actual missing reference.

Just hoping to make it easier to see the woods for the trees with these tests, as they've blocked my progress a bunch of times and possibly others.

I realize that some of these tests may be removed, as @cartermp pointed out in #9617, but while that isn't the case yet, I hope this will make life a little easier ;).

Related PR: https://github.com/fsharp/FSharp.Compiler.Service/pull/766

Before, any differences were utterly senseless in the output, because it didn't point to the actual difference. After, it shows up like this (and I think there'll be other places that can benefit of this change):

image

And they now run handily and correctly in VS IDE Test Runner:

image

Referenced assemblies are now dumped, which can help locate issues when those in-process compilations fail due to missing references:

image

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
Checking those differences in test results, and adjusting the expected values in code + recompile is a reason I generally prefer test using baseline files, easier to diff and faster to run test after adjustments.

Even if the nunit string comparison now shows better, it still only shows the first difference and only few characters, merging the change to fix the test remains a lot of trial and errors.

**Comment by abelbraaksma** [comment]
> is a reason I generally prefer test using baseline files, easier to diff and faster to run test after adjustments.

I totally agree, but I didn't want to introduce a complete new testing method. Besides, testing is being refactored largely, and your idea of baseline files sounds a good way forward (while still maintaining the point-to-exact-error-location, preferably).

> it still only shows the first difference and only few characters, merging the change to fix the test remains a lot of trial and errors.

Correct. But before this I was utterly in the dark and had no idea what to fix. Since all these compare-strings are inline in the source file, it is next to impossible to fix such tests (it literally blocks me from moving forward for this: #9549).

I was looking for a quick way to make this at least a little more manageable. Considering that these tests may get a complete overhaul and/or are dropped, I didn't want to spend too much time with them.

**Comment by KevinRansom** [comment]
@abelbraaksma 

Failing test:   

image

https://dev.azure.com/dnceng/public/_build/results?buildId=716583&view=logs&j=c3b5cd2e-ddad-540a-7ae1-df25e52fdba0&t=d4985d65-7d01-5e76-2879-f1b5d6535baa&l=13051

**Comment by abelbraaksma** [comment]
I really wish there was a way to run a test locally "like in the CI". This happens quite a lot that things are different, and it would be nice to catch them before submitting.

**Comment by abelbraaksma** [comment]
All things considering, and in particular @smoothdeveloper's comments, one alternative way is to have these tests work on a `TestSource`, which should then be these "expected strings" that are being tested against. The advantage being that then there would be one test per line. If 10 lines fail, 10 tests fail and it is easier to fix. 

The current way of having literally over a hundred subtests in a single test is not very maintainable.

**Comment by cartermp** [comment]
Tests like this are horrible to maintain, in part because they're not testing a single thing, but many things. for this specific kind of test, comparing output against some test data (we can call them baselines) could be a little better, but the issue isn't that but the fact that these mondo-tests are asserting _so many things_.

**Comment by abelbraaksma** [comment]
@cartermp, I couldn't agree more. And if only the generated strings (from reflection?) were the same on every system, then at least we'd have "fixed locally & fixed CI". But since it isn't (see my last three commits), it's a lot of "fixed locally, failed CI".

**Comment by abelbraaksma** [comment]
@KevinRansom, @cartermp, yippee! Finally green :)))))))

File: tests/service/ExprTests.fs [hunk 1]
```diff
@@ -22,6 +23,60 @@ let internal exprChecker = FSharpChecker.Create(keepAssemblyContents=true)
...
+
+    /// If it doesn't exists, create a folder 'ExprTests' in local user's %TEMP% folder
+    let createTempDir() = 
+        let tempPath = getTempPath()
+        do 
+            if Directory.Exists tempPath then ()
+            else Directory.CreateDirectory tempPath |> ignore
+
+    /// Returns the filename part of a temp file name created with Path.GetTempFileName().
+    let getTempFileName() =
```
Comment (KevinRansom) [inline tests/service/ExprTests.fs:37]: If you delete the file created with CreateTemp file, then the next time getTempFileName is called you will get the exact same filename, which means if the tests are run multi threaded, there is a fair chance that you will get filename collisions.

So .. a simpler approach would be to just compute a guid.ToString(), or combine  the file name with process id and thread id.

File: tests/service/ExprTests.fs [hunk 2]
```diff
@@ -918,43 +959,72 @@ let ``Test Optimized Declarations Project1`` () =
...
+    try
+        createTempDir()
+        let source = System.String.Format(Project1.operatorTests, dnName, fsName)
+        let replace (s:string) r = s.Replace("let " + r, "// let " + r)
+        let fileSource = excludedTests |> List.fold replace source
+        File.WriteAllText(filePath, fileSource)
+
+        let args = [|
+            yield! mkProjectCommandLineArgsSilent (dllPath, [filePath])
+            yield @"-r:System.Numerics.dll"         // needed for some tests
```
Comment (KevinRansom) [inline tests/service/ExprTests.fs:997]: This is a desktop framework .dll, does this test only build desktop ?

File: tests/service/ExprTests.fs (hunk 1 above)
Comment (abelbraaksma) [reply tests/service/ExprTests.fs:37]: @KevinRansom Interesting, I wasn't sure of that, as when testing, it appeared to be a different name each time (assuming it calls this, which is based on system time: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettempfilenamea). But that still leaves the multi threading issue. 

But that guarantees is not given here: https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettempfilename?view=netcore-3.1. Which, btw, also suggests that cleaning up is a good thing, as after 64k files it'll raise an error.

So that function is not as useful as one might think. I'll fix it.

File: tests/service/ExprTests.fs (hunk 2 above)
Comment (abelbraaksma) [reply tests/service/ExprTests.fs:997]: No, though it took me a week to find out, but it is run both by framework and dotnet. And with old FSharp.Core.dll, but that's something I found out in the string PR.

It doesn't complain about it, though. @kevinransom Should I only add it when framework is run?

**Comment by KevinRansom** [comment]
Cleaning up is a good thing, but the name reuse is a problem.


What I often do Is a bit belt and braces:  https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSharp.DependencyManager.Nuget/FSharp.DependencyManager.fs#L128

````
    let key = "nuget"
    let name = "MsBuild Nuget DependencyManager"
    let scriptsPath =
        let path = Path.Combine(Path.GetTempPath(), key, Process.GetCurrentProcess().Id.ToString() + "--"+ Guid.NewGuid().ToString())
        match outputDir with
        | None -> path
        | Some v -> Path.Combine(path, v)

    let generatedScripts = new ConcurrentDictionary<string,string>()

    let deleteScripts () =
        try
#if !Debug
            if Directory.Exists(scriptsPath) then
                Directory.Delete(scriptsPath, true)
#else
            ()
#endif
        with | _ -> ()

    let deleteAtExit =
        try
            if not (File.Exists(scriptsPath)) then
                Directory.CreateDirectory(scriptsPath) |> ignore
            true
        with | _ -> false
````

File: tests/service/ExprTests.fs (hunk 2 above)
Comment (KevinRansom) [reply tests/service/ExprTests.fs:997]: Here would probably be best:  https://github.com/dotnet/fsharp/blob/master/tests/service/Common.fs#L90

````
let mkStandardProjectReferences () = 
#if NETCOREAPP
            let file = "Sample_NETCoreSDK_FSharp_Library_netstandard2_0.fsproj"
            let projDir = Path.Combine(__SOURCE_DIRECTORY__, "../projects/Sample_NETCoreSDK_FSharp_Library_netstandard2_0")
            readRefs projDir file
#else
            [ yield sysLib "mscorlib"
              yield sysLib "System"
              yield sysLib "System.Core"
              yield sysLib "System.Numerics"
              yield fsCoreDefaultReference() ]
#endif   
````

File: tests/service/ExprTests.fs (hunk 1 above)
Comment (abelbraaksma) [reply tests/service/ExprTests.fs:38]: I've fixed it (better safe than sorry, and best practices and whatnot), but I don't think the risk was so big, as when you delete it, the same name is _not_ chosen again:

```f#
> Path.GetTempFileName();;
val it : string = "C:\Users\Me\AppData\Local\Temp\tmpB0EB.tmp"

> File.Delete it;;
val it : unit = ()

> Path.GetTempFileName();;
val it : string = "C:\Users\Me\AppData\Local\Temp\tmpDFD8.tmp"

> File.Delete it;;
val it : unit = ()

> Path.GetTempFileName();;
val it : string = "C:\Users\Me\AppData\Local\Temp\tmpB051.tmp"

> File.Delete it;;
val it : unit = ()
```

File: tests/service/ExprTests.fs (hunk 2 above)
Comment (abelbraaksma) [reply tests/service/ExprTests.fs]: Done, makes sense indeed (I didn't like my hacky attempt anyway ;). Let's see if it passes the tests still.

**Comment by abelbraaksma** [comment]
> System.Numerics reference.

Done, it is in a more sensible place now, as you suggested.

**Comment by abelbraaksma** [comment]
@vzarytovskii, since you're working with the tests, this may be of interest to you too. If these tests aren't removed but stay in place, the approach here may help make it less painful to work with these by showing more precise errors in the log, and the actual line that went wrong.

Ideally, however, as pointed out by @smoothdeveloper, the textual in-file contents of these tests is troublesome and placing them in some `*.bsl` style files, or with `TestSourceAttribute` would probably go a long way to improve the experience with this set.

Either way, these changes have now only been applied to `ExprTests.fs`, but are applicable to the rest in this directory. Feel free to ping me once you get to these tests to see how we can further improve on them.

**Comment by vzarytovskii** [comment]
> @vzarytovskii, since you're working with the tests, this may be of interest to you too. If these tests aren't removed but stay in place, the approach here may help make it less painful to work with these by showing more precise errors in the log, and the actual line that went wrong.
> 
> 
> 
> Ideally, however, as pointed out by @smoothdeveloper, the textual in-file contents of these tests is troublesome and placing them in some `*.bsl` style files, or with `TestSourceAttribute` would probably go a long way to improve the experience with this set.
> 
> 
> 
> Either way, these changes have now only been applied to `ExprTests.fs`, but are applicable to the rest in this directory. Feel free to ping me once you get to these tests to see how we can further improve on them.

Yeah, right now I'm working on a simplified, easier to use and more composable compiler api for tests. 

So far I've touched only simpler apis, such as compilation, type checking, baseline testing.

I will ping you once I will get to those tests and we can discuss it in details.

**Comment by abelbraaksma** [comment]
> So far I've touched only simpler apis, such as compilation, type checking, baseline testing.

Inasmuch you can call that simple :laughing:

> I will ping you once I will get to those tests and we can discuss the improvements in details.

Gotcha :+1:

**Comment by abelbraaksma** [comment]
```text
2020-07-11T16:20:48.8627471Z   X Test ManyProjectsStressTest whole project errors [2s 743ms]
2020-07-11T16:20:48.8629146Z   Error Message:
2020-07-11T16:20:48.8630983Z      Expected: 104
2020-07-11T16:20:48.8631784Z Actual: 105
2020-07-11T16:20:48.8632187Z   Expected: 104
2020-07-11T16:20:48.8632837Z   But was:  105
```

and

```text
2020-07-11T16:20:50.3758640Z   X Test multi project 1 whole project errors [5ms]
2020-07-11T16:20:50.3760196Z   Error Message:
2020-07-11T16:20:50.3761321Z      Expected: 6
2020-07-11T16:20:50.3761601Z Actual: 7
2020-07-11T16:20:50.3761956Z   Expected: 6
2020-07-11T16:20:50.3762167Z   But was:  7
```

Another gotcha: these tests are **not in the VisualFSharp.sln**, but can be found in projects with almost identical structure in `FSharp.Compiler.Service.sln`. There may be a reason the file `MuiltProjectAnalysisTests.fs` is not included in the main application, so I'm hesitant to make that change.

Anyway, new commit should fix these "hidden" tests.

**Comment by abelbraaksma** [comment]
All green, @KevinRansom, this is ready for rereview.

**Comment by abelbraaksma** [comment]
ping @KevinRansom ;)

**Comment by cartermp** [comment]
@vzarytovskii can you take a look at this while @KevinRansom is out on vacation?

**Comment by abelbraaksma** [comment]
@vzarytovskii, thanks. Can you, or @cartermp, clear the status of the requested changes from @kevinransom, so that this can be merged while he's on holiday?
