### PR TITLE
Fix false negative [<TailCall>] warning

### LINKED ISSUE #18365: False negative with TailCall attribute
**Repro steps**

Consider the following code (the simplest example I could craft, don't expect anything sane):
```fsharp
type Value =
    { Code: string }

[<TailCall>]
let rec fooArray (values: Value[], code: string) =
    match values with
    | [||] -> seq { code }
    | values ->
        let replicatedValues =
            values
            |> Array.map (fun value -> fooArray (values, value.Code))
        replicatedValues |> Seq.concat
```
 `fooArray` isn't called in tail recursive manner, however compiler does not issue a warning.

Curiously, after rewrite to Seq functions compiler does issue `Warning FS3569 : The member or function 'fooSeq' has the 'TailCallAttribute' attribute, but is not being used in a tail recursive way.`
```fsharp
[<TailCall>]
let rec fooSeq (values: Value[], code: string) =
    match values with
    | [||] -> seq { code }
    | values ->
        let replicatedValues =
            values
            |> Seq.map (fun value -> fooSeq (values, value.Code))
            |> Seq.toArray
        replicatedValues |> Seq.concat
```
Looking at decompiled code of assembly I would guess that compiler tries to optimise Array.map and TailCall analyser mistakes the result for tail-recursive function.

**Expected behavior**

Warning is issued for first code example.

**Actual behavior**

No warning.

**Known workarounds**

.

**Related information**

Provide any related information (optional):
.NET SDK 9.0.200

### PR DESCRIPTION
**Pull request by dawedawe**
## Description

Fix missing analysis for `[<TailCall>]` violations in `TOp.IntegerForLoop` expressions appearing as `expr1` in `Sequential` expressions.
As a side effect, this improves the order of warnings, see adjusted test.

Fixes #18365 

## Checklist

- [x] Test cases added
- [ ] Performance benchmarks added in case of performance changes
- [x] Release notes entry updated:

### CODE REVIEW

**Comment by vzarytovskii** [comment]
Sweet, thanks!

**Review by vzarytovskii — APPROVED** [review]

File: src/Compiler/Checking/TailCallChecks.fs [hunk 1]
```diff
@@ -792,7 +792,12 @@ let CheckModuleBinding cenv (isRec: bool) (TBind _ as bind) =
                     // warn for recursive calls in TryWith/TryFinally operations
                     exprs |> Seq.iter (checkTailCall true)
                 | Expr.Op(args = exprs) -> exprs |> Seq.iter (checkTailCall insideSubBindingOrTry)
-                | Expr.Sequential(expr2 = expr2) -> checkTailCall insideSubBindingOrTry expr2
+                | Expr.Sequential(expr1 = expr1; expr2 = expr2) ->
+                    match expr1 with
+                    | Expr.Op(args = exprs; op = TOp.IntegerForLoop _) -> checkTailCall insideSubBindingOrTry expr1
+                    | _ -> ()
+
+                    checkTailCall insideSubBindingOrTry expr2
```
Comment (brianrourkeboll) [inline src/Compiler/Checking/TailCallChecks.fs:800]: Why do we only need to check `expr1` if it's a for-loop?

Comment (dawedawe) [reply src/Compiler/Checking/TailCallChecks.fs:800]: Hey Brian, thanks for the review.

Doing it unconditionally led to duplicated warnings in other test scenarios ( ``Warn for calls in for and iter``) and in general I like to keep changes as small as possible in this code at this stage.

**Review by T-Gro — APPROVED** [review]
