### PR TITLE
Bugfix :: Fix closure capture and let-rec initialization codegen

### LINKED ISSUE #17692: Runtime have a mutrec codegeneration issue.  --- est failure: JIT/Directed/tailcall/mutual_recursion/mutual_recursion.cmd
The original issue is:  https://github.com/dotnet/runtime/issues/106601#issuecomment-2339729628

**Failed in:** [runtime-coreclr ilasm 20240817.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779266&view=ms.vss-test-web.build-test-results-tab&runId=19969056&resultId=108027&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked ilasmroundtrip @ (Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - JIT/Directed/tailcall/mutual_recursion/mutual_recursion.cmd
coreclr osx x64 Checked ilasmroundtrip @ OSX.1200.Amd64.Open
    - JIT/Directed/tailcall/mutual_recursion/mutual_recursion.cmd
coreclr linux arm64 Checked ilasmroundtrip @ (Ubuntu.2004.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-20.04-helix-arm64v8
    - JIT/Directed/tailcall/mutual_recursion/mutual_recursion.cmd
coreclr osx arm64 Checked ilasmroundtrip @ OSX.1200.ARM64.Open
    - JIT/Directed/tailcall/mutual_recursion/mutual_recursion.cmd
coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open
    - JIT/Directed/tailcall/mutual_recursion/mutual_recursion.cmd
coreclr windows x64 Checked ilasmroundtrip @ Windows.10.Amd64.Open
    - JIT/Directed/tailcall/mutual_recursion/mutual_recursion.cmd
coreclr linux x64 Checked ilasmroundtrip @ Ubuntu.2204.Amd64.Open
    - JIT/Directed/tailcall/mutual_recursion/mutual_recursion.cmd
coreclr windows arm64 Checked ilasmroundtrip @ Windows.11.Arm64.Open
    - JIT/Directed/tailcall/mutual_recursion/mutual_recursion.cmd
```

**Error message:**
```
 IL-RT/mutual_recursion.il(2418) : warning : Duplicate param name 'self@' in method '.ctor'
IL-RT/mutual_recursion.il(2935) : warning : Duplicate param name 'self@' in method '.ctor'
IL-RT/mutual_recursion.il(3399) : warning : Duplicate param name 'self@' in method '.ctor'
IL-RT/mutual_recursion.il(3863) : warning : Duplicate param name 'self@' in method '.ctor'
IL-RT/mutual_recursion.il(4327) : warning : Duplicate param name 'self@' in method '.ctor'
Unhandled exception. System.Exception: Incorrect method passed
   at Mutual_recursion.Driver.runMethodWithTiming@511.Invoke(String methodName, Boolean worksOnlyOnNetCore5, Int32 iterationCount, FSharpFunc`2 cb)
   at Mutual_recursion.Driver.Start()
   at Mutual_recursion.main(String[] argv)
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/root/helix/work/workitem/e/JIT/Directed/Directed_3/../tailcall/mutual_recursion/mutual_recursion.sh: line 453:  5935 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/tailcall/mutual_recursion/output.txt
Raw output:
BEGIN EXECUTION

.NET IL Assembler.  Version 9.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'IL-RT/mutual_recursion.il'  to EXE --> 'mutual_recursion.dll'
Source file is UNICODE

Assembled method Mutual_recursion�Point2D::CompareTo
Assembled method Mutual_recursion�Point2D::CompareTo
Assembled method Mutual_recursion�Point2D::CompareTo
Assembled method Mutual_recursion�Point2D::GetHashCode
Assembled method Mutual_recursion�Point2D::GetHashCode
Assembled method Mutual_recursion�Point2D::Equals
Assembled method Mutual_recursion�Point2D::Equals
Assembled method Mutual_recursion�Point2D::.ctor
Assembled method Mutual_recursion�Point2D::get_X
Assembled method Mutual_recursion�Point2D::get_Y
Assembled method Mutual_recursion�Point2D::Equals
Assembled method Mutual_recursion�Point2D::Equals
Assembled method Mutual_recursion�callee@30::.ctor
Assembled method Mutual_recursion�callee@30::Invoke
Assembled method Mutual_recursion�callee@30::.cctor
Assembled method Mutual_recursion�secondCallee@44::.ctor
Assembled method Mutual_recursion�secondCallee@44::Invoke
Assembled method Mutual_recursion�secondCallee@44::.cctor
Assembled method Mutual_recursion�thirdCallee@66::.ctor
Assembled method Mutual_recursion�thirdCallee@66::Invoke
Assembled method Mutual_recursion�thirdCallee@66::.cctor
Assembled method Mutual_recursion�thirdCallee@66D::.ctor
Assembled method Mutual_recursion�thirdCallee@66D::Invoke
Assembled method Mutual_recursion�fourthMethodFirstCallee@101::.ctor
Assembled method Mutual_recursion�fourthMethodFirstCallee@101::Invoke
Assembled method Mutual_recursion�fourthMethodSecondCallee@117::.ctor
Assembled method Mutual_recursion�fourthMethodSecondCallee@117::Invoke
Assembled method Mutual_recursion�fifthMethodFirstCallee@147::.ctor
Assembled method Mutual_recursion�fifthMethodFirstCallee@147::Invoke
Assembled method Mutual_recursion�fifthMethodFirstCallee@147D::.ctor
Assembled method Mutual_recursion�fifthMethodFirstCallee@147D::Invoke
Assembled method Mutual_recursion�fifthMethodSecondCallee@165::.ctor
Assembled method Mutual_recursion�fifthMethodSecondCallee@165::Invoke
Assembled method Mutual_recursion�fifthMethodSecondCallee@165D::.ctor
Assembled method Mutual_recursion�fifthMethodSecondCallee@165D::Invoke
Assembled method Mutual_recursion�sixthMethodFirstCallee@198::.ctor
Assembled method Mutual_recursion�sixthMethodFirstCallee@198::Invoke
Assembled method Mutual_recursion�sixthMethodFirstCallee@198D::.ctor
Assembled method Mutual_recursion�sixthMethodFirstCallee@198D::Invoke
Assembled method Mutual_recursion�sixthMethodSecondCallee@216::.ctor
Assembled method Mutual_recursion�sixthMethodSecondCallee@216::Invoke
Assembled method Mutual_recursion�seventhMethodFirstCallee@247::.ctor
Assembled method Mutual_recursion�seventhMethodFirstCallee@247::Invoke
Assembled 
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor241|0_242(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0& A_2)
```

### LINKED ISSUE #19068: Object expression in struct generates byref field in a class
Using an object expression in a struct that depends on `this` or primary constructor parameters in the arguments to the object's constructor results in a `class` being emitted with a _byref_ field.

**Repro steps**

```fs
type Class(test : obj) = class end

[<Struct>]
type Struct(test : obj) =
  member _.Test() = {
    new Class(test) with
    member _.ToString() = ""
  }
```

**Expected behavior**

`Struct` should be compiled into a valid type that does what the code expresses.

**Actual behavior**

The type of the anonymous class created in `Test` has a `byref<Struct>`, resulting in a `TypeLoadException` at runtime.

It seems that when the "closure" type that is generated here depends on the containing type, it is always generated with a byref `_` field that stores a reference to the original struct, even if that reference is never used.

Normally, situations like this result in FS0406 (The byref-typed variable '_' is used in an invalid way.), however here the instance is not referenced in any of the members of the anonymous class.

Even the constructor itself is kinda strange:
```cs
public Test@5(ref Struct _)
{
    Unsafe.As<Struct, ref Struct>(ref this._) = ref _;
    base..ctor(((Struct)Unsafe.As<Struct, ref Struct>(ref this._)).test);
}
```
No idea what the intention here was, but calling `base(_.test)` instead would have worked quite fine.

**Known workarounds**

If the constructor's arguments are first bound to variables, everything is fine.

**Related information**

Environment: .NET 9.0.303, [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwBcBPABxgAIBhDAQ11wApCZdCKQKJgArASgoBeCmDoMKMAHYATALAAoBQG0APAGVCUAK5hCAPgC6CkuQobtu5q3adu/IQooUAtjGfAYUCgH0AdABVrRgFhAG9HJwpJGAB3ajEmFjYBGIBLQgALCKdXd08fAIhzVMkAc2ChCgAiKoiAXwUgA==)

### PR DESCRIPTION
**Pull request by T-Gro**
Fixes invalid IL generated for closures and recursive bindings.

- Fixes #19068 — struct object expressions no longer generate invalid IL with byref fields
- Fixes #17692 — closure constructor parameter names deduplicated to avoid `VerificationException`

Also reorders let-rec bindings so lambda closures are allocated before non-lambda values that reference them, avoiding null dereferences at runtime.

---

**Note:** These changes were pushed directly to `main` (not through this PR's merge flow). The code is already in `main`. This PR is being closed for tracking and issue-linking purposes.

**Review the actual diffs here:**
- Primary fix: https://github.com/dotnet/fsharp/commit/e2ddcabc55aa52989b80db2da208d5d5c2bb5e0a (18 files, +443/−134)
- Follow-up: https://github.com/dotnet/fsharp/commit/f29ffbb91bd82b6d1299ba727e6e1bf5f43e5d4e (1 file, +2/−2)

### CODE REVIEW

File: src/Compiler/CodeGen/EraseClosures.fs [hunk 1]
```diff
@@ -392,6 +392,21 @@ let mkILFreeVarForParam (p: ILParameter) =
 
 let mkILLocalForFreeVar (p: IlxClosureFreeVar) = mkILLocal p.fvType None
 
+// Note: This is similar to ChooseFreeVarNames in IlxGen.fs but operates on
+// IlxClosureFreeVar[] instead of string lists. Kept separate to avoid cross-file dependency.
```
Comment (auduchinok) [inline src/Compiler/CodeGen/EraseClosures.fs]: Can this be extracted and unified somehow instead? If the logic is the same, we probably want to update it together in future, so producing duplicate code doesn't sound good?
