### PR TITLE
Fix finding references to CtorGroup

### LINKED ISSUE #15721: Renaming works weirdly for disposable types
Probably two bugs here:
1) Renaming doesn't work when there is a warning (it should though)
2) Renaming doesn't work immediately

https://github.com/dotnet/fsharp/assets/5451366/2c049e8b-4bc4-4859-a55f-8a6ae6d4b0b0

Note I am not explicitly saving the document on-the-go.

### PR DESCRIPTION
**Pull request by 0101**
Fixes #15721

There are two issues
1. writing to `itemKeyStore` where without the `new` it's an `ILMeth` instead of `FSMeth` for some reason and that's written differently. 
2. with "fast find references" because `DisplayNameCore` for it is `".ctor"` instead of the type name.

I tried to fix those, let's see if something else depended on the original behavior...

I couldn't reproduce the "You cannot rename this element" dialogue or the first rename failure after adding `new`.

### CODE REVIEW

File: tests/service/ProjectAnalysisTests.fs [hunk 1]
```diff
@@ -3070,7 +3070,7 @@ let ``Test Project21 all symbols`` () =
             ("unit", "unit", "file1", ((12, 43), (12, 47)), ["type"], ["abbrev"]);
             ("val raise", "raise", "file1", ((13, 18), (13, 23)), [], ["val"]);
             ("System", "System", "file1", ((13, 25), (13, 31)), [], ["namespace"]);
-            ("member .ctor", "``.ctor``", "file1", ((13, 25), (13, 55)), [], ["member"]);
+            ("member .ctor", "NotImplementedException", "file1", ((13, 25), (13, 55)), [], ["member"]);
```
Comment (0101) [inline tests/service/ProjectAnalysisTests.fs:3073]: Can we change this behavior? Seems more useful to me like this, but maybe I just don't know the use cases...

Comment (T-Gro) [reply tests/service/ProjectAnalysisTests.fs:3073]: Why should `su.Symbol.DisplayName` be a NotImplementedException here?

Comment (0101) [reply tests/service/ProjectAnalysisTests.fs:3073]: Because that's what's actually displayed. It's a constructor for `NotImplementedException`.

Comment (psfinaki) [reply tests/service/ProjectAnalysisTests.fs:3073]: Sounds like the root cause is somewhere down the drain...

Comment (0101) [reply tests/service/ProjectAnalysisTests.fs:3073]: Root cause is described in the PR description. Question is if we should fix it in `DisplayNameCore` or keep that as is and just add the extra logic to finding references. 

Second option is safer so maybe I just do that and we can merge it without worrying...

Comment (psfinaki) [reply tests/service/ProjectAnalysisTests.fs:3073]: Well to me the first option seems a more correct way to go since this outcome is weird and the problem in DisplayNameCore might have some other weird consequences therefore.

That being said, I would be fine with having this as is and creating a ticket to fix the DisplayNameCore.

**Review by psfinaki — APPROVED** [review]

**Review by T-Gro — APPROVED** [review]

File: tests/service/ProjectAnalysisTests.fs (hunk 1 above)
Comment (0101) [reply tests/service/ProjectAnalysisTests.fs:3073]: Ok, let's merge this and see what happens...
