### PR TITLE
use path separator instead of hardcoded semicolon

### LINKED ISSUE #11729: FSI nuget reference (#r) breaks the process' PATH environment variable on Linux
When using `#r "nuget: ....."`, FSI appends a string to the PATH environment variable:
`PATH=/usr/local/sbin:/xxxxxxx;/homepath/.nuget/packages/package/x.x.x/;`

It uses the `;` character as a separator, however in Linux `:` is the PATH env var separator.
Surprisingly, some distributions are tolerant of this (Ubuntu), others however are not (Alpine).

This has all sort of weird side effects in the FSI process/script that is running, especially if you try launch a sub process.

**Repro steps**

```
#r "nuget: Newtonsoft.Json"

System.Environment.GetEnvironmentVariables()
|> Seq.cast<System.Collections.DictionaryEntry>
|> Seq.filter (fun x -> x.Key |> string = "PATH")
|> Seq.iter (fun x -> printfn "%s:%s" (string x.Key) (string x.Value))
```

**Expected behavior**

FSI appends to PATH with the platform specific separator.

**Actual behavior**

PATH gets butchered.

**Known workarounds**

```
#r "nuget: Newtonsoft.Json"

// 😥
let fixedPathEnv = System.Environment.GetEnvironmentVariable("PATH").Replace(';', ':').TrimEnd(':')
System.Environment.SetEnvironmentVariable("PATH", fixedPathEnv)

System.Environment.GetEnvironmentVariables()
|> Seq.cast<System.Collections.DictionaryEntry>
|> Seq.filter (fun x -> x.Key |> string = "PATH")
|> Seq.iter (fun x -> printfn "%s:%s" (string x.Key) (string x.Value))
```

### PR DESCRIPTION
**Pull request by baronfel**
This should fix #11729, but we'll see what CI has to say about it.

### CODE REVIEW

File: src/fsharp/DependencyManager/NativeDllResolveHandler.fs [hunk 1]
```diff
@@ -111,25 +111,31 @@ type NativeDllResolveHandler (nativeProbingRoots: NativeResolutionProbe) =
...
-            p + ";"
+    let pathSeparator =
+        if RuntimeInformation.IsOSPlatform(OSPlatform.Windows) then
+            ";"
+        else
+            ":"
+
+    let appendPathSeparator (p: string) =
+        if not(p.EndsWith(pathSeparator, StringComparison.OrdinalIgnoreCase)) then
+            p + pathSeparator
```
Comment (brettfo) [inline src/fsharp/DependencyManager/NativeDllResolveHandler.fs:122]: Use `System.IO.Path.PathSeparator` and drop the `pathSeparator` value, otherwise this is great, thank you.

**Review by brettfo — CHANGES_REQUESTED** [review]

File: src/fsharp/DependencyManager/NativeDllResolveHandler.fs (hunk 1 above)
Comment (baronfel) [reply src/fsharp/DependencyManager/NativeDllResolveHandler.fs:122]: wow, I even said to do that in my comment in the original issue 🤦

**Review by brettfo — APPROVED** [review]

**Comment by baronfel** [comment]
`System.IO.Path.PathSeparator` is a `char`, pushed up a stringification of it to fix that. The joys of editorless-changes.

File: src/fsharp/DependencyManager/NativeDllResolveHandler.fs [hunk 2]
```diff
@@ -111,25 +111,26 @@ type NativeDllResolveHandler (nativeProbingRoots: NativeResolutionProbe) =
         else
             None
 
-    let appendSemiColon (p: string) =
-        if not(p.EndsWith(";", StringComparison.OrdinalIgnoreCase)) then
-            p + ";"
+    let appendPathSeparator (p: string) =
+        let separator = string string System.IO.Path.PathSeparator
```
Comment (vzarytovskii) [inline src/fsharp/DependencyManager/NativeDllResolveHandler.fs:115]:
```suggestion
        let separator = string System.IO.Path.PathSeparator
```
Double string, just to make sure? :)

**Review by vzarytovskii — APPROVED** [review]

File: src/fsharp/DependencyManager/NativeDllResolveHandler.fs (hunk 2 above)
Comment (baronfel) [reply src/fsharp/DependencyManager/NativeDllResolveHandler.fs]: I have no words.  I'm a professional, everybody!

**Comment by dsyme** [comment]
Thank you, I didn't know about `System.IO.Path.PathSeparator`
