### PR TITLE
Print empty namespace or module.

### LINKED ISSUE #13757: Signature file generation does not handle empty assembly info input
When generating a signature file from an assembly info file, the generated code is empty.

**Repro steps**

```fsharp
namespace System

open System.Runtime.CompilerServices

[<assembly: InternalsVisibleTo("Fantomas.Core.Tests")>]

do ()
```

leads to

```fsharp

```

**Expected behaviour**

The generated signature should be considered equivalent to the backing source file.

**Actual behaviour**

The generated code isn't valid:

image

I guess it should at the very least have `namespace System` here in order for it to compile.
This is admittedly quite an edge case.

**Known workarounds**

Edit signature file by hand.

### PR DESCRIPTION
**Pull request by nojaf**
Fixes #13757

### CODE REVIEW

**Comment by nojaf** [comment]
@vzarytovskii @dsyme ready for review.

File: src/Compiler/TypedTree/TypedTreeOps.fs [hunk 1]
```diff
@@ -10360,3 +10360,24 @@ let isFSharpExceptionTy g ty =
...
+let (|EmptyModuleOrNamespace|_|) (moduleOrNamespaceContents: ModuleOrNamespaceContents) =
+    match moduleOrNamespaceContents with
+    | TMDefs(defs = defs) ->
+        let singleModuleOrNamespace =
+            defs
+            |> List.choose (function
+                | ModuleOrNamespaceContents.TMDefRec _ as defRec
+                | ModuleOrNamespaceContents.TMDefs(defs = [ ModuleOrNamespaceContents.TMDefRec _ as defRec ]) -> Some defRec
+                | _ -> None)
+            |> List.tryHead
```
Comment (0101) [inline src/Compiler/TypedTree/TypedTreeOps.fs:10372]: What if there are multiple items in this list?

Comment (nojaf) [reply src/Compiler/TypedTree/TypedTreeOps.fs]: That is a very unlikely scenario I believe.
You can only have this with two namespaces.
Fair enough, I've added a test.

File: src/Compiler/TypedTree/TypedTreeOps.fs [hunk 2]
```diff
@@ -10360,3 +10360,34 @@ let isFSharpExceptionTy g ty =
...
+                            | _ -> false)
+                        |> fun isEmpty -> if isEmpty then Some mspec else None
+                    | _ -> None
+                | _ -> None)
+
+        if mdDefsLength = emptyModuleOrNamespaces.Length then
+            Some emptyModuleOrNamespaces
+        else
+            None
+    | _ -> None
```
Comment (0101) [inline src/Compiler/TypedTree/TypedTreeOps.fs:10393]: Should we also check for `TMDefRec` here? Consider these (and maybe add to tests):

```fsharp
module rec Foobar

do ()
```


```fsharp
namespace rec Foobar

do () 
```

File: src/Compiler/TypedTree/TypedTreeOps.fsi [hunk 3]
```diff
@@ -2676,3 +2676,6 @@ type TraitConstraintInfo with
 
     /// Get the key associated with the member constraint.
     member GetWitnessInfo: unit -> TraitWitnessInfo
+
+val (|EmptyModuleOrNamespaces|_|):
```
Comment (0101) [inline src/Compiler/TypedTree/TypedTreeOps.fsi:2680]: Can we get a docstring for this? Since it considers a module/namespace with a `TMDefDo` as empty, which it is from point of view of a signature, but maybe not in some other context.

File: src/Compiler/TypedTree/TypedTreeOps.fs [hunk 4]
```diff
@@ -10360,3 +10360,34 @@ let isFSharpExceptionTy g ty =
...
+                        defs
+                        |> List.forall (function
+                            | ModuleOrNamespaceContents.TMDefOpens _
+                            | ModuleOrNamespaceContents.TMDefDo _ -> true
+                            | _ -> false)
+                        |> fun isEmpty -> if isEmpty then Some mspec else None
+                    | _ -> None
+                | _ -> None)
+
+        if mdDefsLength = emptyModuleOrNamespaces.Length then
```
Comment (0101) [inline src/Compiler/TypedTree/TypedTreeOps.fs:10389]: There seems to be another edge case which could theoretically happen:

```fsharp
namespace Foo

do ()

namespace Bar

   module Baz =  

       do ()
```

In this case it won't be matched and `namespace Foo` won't be in the signatures.

File: src/Compiler/TypedTree/TypedTreeOps.fs (hunk 2 above)
Comment (nojaf) [reply src/Compiler/TypedTree/TypedTreeOps.fs:10393]:
```fsharp
module rec Foobar

do ()
```

currently produces

```fsharp
module Foobar

val ``doval@3`` : unit
```

This probably isn't correct but is outside my scope here.

File: src/Compiler/TypedTree/TypedTreeOps.fs (hunk 4 above)
Comment (nojaf) [reply src/Compiler/TypedTree/TypedTreeOps.fs:10389]: I can live with that, the goal is to avoid purely empty file generation.
This will give a result because of the nested module and that is good enough for my use case.

**Comment by 0101** [comment]
@nojaf we can have a separate issue to track the remaining inconsistencies if they're too difficult to fix right now. If you can add a docstring to `(|EmptyModuleOrNamespaces|_|)` then I think we can merge this.

**Comment by nojaf** [comment]
Thanks 👍, I see that I've added the docstring to the implementation file instead. I'll address that this afternoon.
