### PR TITLE
Replace throw with EDI throw in CE catch handlers, fixes #8529

### LINKED ISSUE #8529: CE try catch with exception filters should use EDI instead of throw ex
CE try catch with exception filters should use EDI instead of throw ex.
Came across this while improving exception handling in Ply.

```fs
open System

let foo() = async {
    try
        invalidOp "ex"
    with
    // This isn't catching InvalidOperationException, so the stacktrace should stay the same
    | :? ArgumentException -> return ()
}
```

Catch lambda is compiled to 
```cs
  [CompilerGenerated]
    internal static FSharpAsync<Unit> catchHandler@1(Exception _arg1)
    {
        ArgumentException ex = _arg1 as ArgumentException;
        if (ex != null)
        {
            return AsyncPrimitives.MakeAsync(new foo@8-2());
        }
        throw _arg1; 
    }
```

A rethrow isn't possible there but `ExceptionDispatchInfo.Throw` is.

Doing a throw causes cut off stacktraces

### PR DESCRIPTION
**Pull request by NinoFloris**
Fixes #8529

### CODE REVIEW

File: src/fsharp/PatternMatchCompilation.fs [hunk 1]
```diff
@@ -793,11 +796,37 @@ let CompilePatternBasic
...
+                        // EDI.Throw: exn -> unit
+                        let name, sigTys = "Throw", [ g.exn_ty; g.unit_ty ]
+
+                        g.system_ExceptionDispatchInfo_ty
+                        |> Option.bind (fun ty ->
+                            TryFindIntrinsicMethInfo infoReader matchm (AccessorDomain.AccessibleFromEverywhere) name ty
+                            |> List.tryFind (fun methInfo ->
+                                not methInfo.IsInstance &&
+                                (
+                                    match methInfo.GetParamTypes(amap, matchm, []) with
```
Comment (NinoFloris) [inline src/fsharp/PatternMatchCompilation.fs:812]: Code for filtering MethInfo is modified from `TryFindFSharpSignatureInstanceGetterProperty`, I could extract it but I'm not sure to what file.

File: src/fsharp/PatternMatchCompilation.fsi [hunk 2]
```diff
@@ -50,7 +51,10 @@ val ilFieldToTastConst: ILFieldInit -> Const
 val internal CompilePattern: 
     TcGlobals ->
     DisplayEnv ->
-    Import.ImportMap -> 
+    Import.ImportMap ->
+    // tcVal
+    (ValRef -> ValUseFlag -> TTypes -> range -> Expr * TType) ->
```
Comment (NinoFloris) [inline src/fsharp/PatternMatchCompilation.fsi:56]: Not super happy with pushing tcval like this into here but ordering issues forced my hand.

File: tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+  IL_0006:  stloc.0
+  IL_0007:  ldloc.0
+  IL_0008:  brfalse.s  IL_000c
+
+  IL_000a:  ldnull
+  IL_000b:  ret
+
+  IL_000c:  ldarg.1
+  IL_000d:  call       void [runtime]System.Runtime.ExceptionServices.ExceptionDispatchInfo::Throw(class [runtime]System.Exception)
+  IL_0012:  ldnull
```
Comment (NinoFloris) [inline tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs:49]: This ok? It'll never be reached but the emitted cast will be unsound (in this case the CE is returning unit, for other types `IL_000a` will be correct while IL_0012 will stay `ldnull`)

File: src/fsharp/PatternMatchCompilation.fsi (hunk 2 above)
Comment (cartermp) [reply src/fsharp/PatternMatchCompilation.fsi:56]: This is generally fine, since it's all internal. We add parameters all the time to provide additional context for things like this. Might be good to just give it an explicit name in the annotation as well.

File: src/fsharp/PatternMatchCompilation.fs (hunk 1 above)
Comment (cartermp) [reply src/fsharp/PatternMatchCompilation.fs:812]: @dsyme and @TIHan can answer this effectively

File: src/fsharp/PatternMatchCompilation.fs [hunk 4]
```diff
@@ -793,11 +796,37 @@ let CompilePatternBasic
...
+                                    | [] -> false
+                                    | argTysList ->
+                                        let argTys = (argTysList |> List.reduce (@)) @ [ methInfo.GetFSharpReturnTy (amap, matchm, []) ] in
```
Comment (cartermp) [inline src/fsharp/PatternMatchCompilation.fs:815]: Stylistically we try to avoid OCAML-style `let..in..` bindings in the compiler, though some older ones certainly remain

File: src/fsharp/TcGlobals.fs [hunk 5]
```diff
@@ -1058,6 +1058,9 @@ type public TcGlobals(compilingFslib: bool, ilg:ILGlobals, fslibCcu: CcuThunk, d
   member val system_MarshalByRefObject_tcref =  tryFindSysTyconRef sys "MarshalByRefObject"
   member val system_MarshalByRefObject_ty = tryMkSysNonGenericTy sys "MarshalByRefObject"
 
+  member val system_ExceptionDispatchInfo_ty =
```
Comment (cartermp) [inline src/fsharp/TcGlobals.fs:1061]: I realize none of the surrounding ones here have a `///` comment, but it would be nice to have it added for the sake of tooling if this needs to get used again elsewhere. These members should all have these kinds of comments, perhaps I can snipe @dsyme into doing that one day 🙂

File: tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs [hunk 6]
```diff
@@ -0,0 +1,54 @@
+// Copyright (c) Microsoft Corporation.  All Rights Reserved.  See License.txt in the project root for license information.
+namespace FSharp.Compiler.UnitTests.CodeGen.EmittedIL
+
+open FSharp.Compiler.UnitTests
+open NUnit.Framework
+
+#if NETCOREAPP
```
Comment (cartermp) [inline tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs:7]: Is the reason for guarding this test with the ifdef related to the IL that gets emitted being different on .NET Framework?

File: tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs (hunk 3 above)
Comment (0x53A) [reply tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs:49]: does it pass PEVerify?

I did a similar test, and it failed:
image

> il-test.exe : il_test.Program::M][offset 0x00000001][found Nullobjref 'NullReference'][expected Int32] Unexpected type on the stack.

Comment (NinoFloris) [reply tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs:49]: @0x53A thanks, that's helpful, it won't be truly on the stack though, EDI.Throw never returns. I guess PEVerify isn't available in unix flavor is it?

File: tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs (hunk 6 above)
Comment (NinoFloris) [reply tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs:7]: Right, no not directly I just thought it was an easy way to exclude netfx versions that don't ship the type, which would cause throw to be emitted instead. But I should have asked, which versions do you run these tests on :)

Comment (cartermp) [reply tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs:7]: All build and test is don against `net472`, since that's the base framework version that VS depends on. So this should be fine.

Comment (NinoFloris) [reply tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs:7]: I'll remove the ifdef!

File: tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs (hunk 3 above)
Comment (cartermp) [reply tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs:49]: Not related to this issue per say, but it's worth noting that PEVerify and recent C#/.NET constructs don't always get along. Example: https://github.com/dotnet/roslyn/issues/27382

File: src/fsharp/PatternMatchCompilation.fs [hunk 7]
```diff
@@ -793,11 +796,37 @@ let CompilePatternBasic
...
+                                            (argTys, sigTys)
+                                            ||> List.forall2 (typeEquiv g)
+                                )
+                            ))
+
+                    match ediThrowMethInfo with
+                    | None ->
+                        mkThrow matchm resultTy (exprForVal matchm origInputVal)
+                    | Some ediThrowMethInfo ->
+                        fst <| BuildMethodCall tcVal g amap NeverMutates matchm false
```
Comment (dsyme) [inline src/fsharp/PatternMatchCompilation.fs:828]: no `<|` in compiler please, except specific idioms  :-))

Comment (dsyme) [reply src/fsharp/PatternMatchCompilation.fs:828]: Yes might need to place this in a `mkSequential` with the previous thing generated, just to get the return type right

File: src/fsharp/PatternMatchCompilation.fsi (hunk 2 above)
Comment (dsyme) [reply src/fsharp/PatternMatchCompilation.fsi:56]: This is ok, it's annoying but needed for late codegen of TAST fragments

File: src/fsharp/TcGlobals.fs (hunk 5 above)
Comment (dsyme) [reply src/fsharp/TcGlobals.fs:1061]: Snipe away!

File: tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs (hunk 3 above)
Comment (dsyme) [reply tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs:49]: See comment above about adding a `mkSequential`

File: tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs (hunk 6 above)
Comment (NinoFloris) [reply tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs]: So apparently EDI.Throw(exn) doesn't exist on netfx after all. I thought I had checked fairly carefully, so I did it again and the link does say the docs apply to netfx too, so I'm not sure what's broken there.

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.exceptiondispatchinfo.throw?view=netcore-3.1#System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw_System_Exception_

Anyway the workaround is to move to `EDI.Capture(exn).Throw()` instead, which I have done.

File: src/fsharp/PatternMatchCompilation.fs (hunk 4 above)
Comment (NinoFloris) [reply src/fsharp/PatternMatchCompilation.fs]: Removed

File: tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs (hunk 3 above)
Comment (NinoFloris) [reply tests/fsharp/Compiler/CodeGen/EmittedIL/CeEdiThrow.fs]: Fixed, emitting default now

**Comment by cartermp** [comment]
@dsyme could you take another look here? @NinoFloris did show how it can be improved in the issue it resolves

**Comment by NinoFloris** [comment]
@dsyme could you take a look. 

I'd like to get this merged before the test suite refactor lands
