### PR TITLE
Disallow calling abstract methods directly on interfaces

### LINKED ISSUE #14012: Bad image when calling op_Addition on interface
Calling `op_Addition` on interface results in a Bad Image error.

**Repro steps**

1. `open System.Numerics;;`

2. `IAdditionOperators.op_Addition (3, 6) ;;`

**Expected behavior**

Compiles with `val it: int = 9`

**Actual behavior**

Fails compilation with:

```
> IAdditionOperators.op_Addition (3, 6) ;;
System.BadImageFormatException: Bad IL format.
   at <StartupCode$FSI_0012>.$FSI_0012.main@()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Stopped due to error
```

**Known workarounds**

Don't call directly on the interface.

**Related information**

Other operations, like `op_CheckedAddition` work fine:

```
> IAdditionOperators.op_CheckedAddition (3, 6) ;;
val it: int = 9
```

Test on:

Microsoft (R) F# Interactive version 12.0.5.0 for F# 7.0

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.4.0 Preview 2.1

### PR DESCRIPTION
**Pull request by edgarfgp**
## Description

Fixes #14012
Fixes https://github.com/dotnet/fsharp/issues/16299

- Check introduced to ensure we can call on virtual members, can't call abstracts.
```fsharp
open System.Numerics
IAdditionOperators.op_Addition (3, 6) // System.BadImageFormatException: Bad IL format.

IAdditionOperators.op_CheckedAddition (3, 6) // Compiles and run as this a static virtual
```
See: 
https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Numerics/IAdditionOperators.cs,5b77e6b404819054

## Before
`System.BadImageFormatException: Bad IL format.`

## After

`(Error 3866, Line 15, Col 82, Line 15, Col 129, "A static abstract interface member can be accessed only on a type parameter.")`

## Rationale:
- Added an specific error message  to make it clear that is not allowed calling static abstract members on an interface.

## Checklist

- [x] Test cases added
- [x] Release notes entry updated:

### CODE REVIEW

File: src/Compiler/Checking/ConstraintSolver.fs [hunk 1]
```diff
@@ -2942,10 +2942,16 @@ and ResolveOverloading
...
-
         match calledMethGroup, candidates with 
-        | _, [calledMeth] when not isOpConversion -> 
-            Some calledMeth, CompleteD, NoTrace
+        | _, [calledMeth] when not isOpConversion ->
+            // See what candidates we have based on static/virtual/abstract
+            // OK: static virtual TResult operator checked i.e. IAdditionOperators.op_CheckedAddition
+            // Error: static abstract TResult operator i.e. IAdditionOperators.op_Addition
+            match calledMeth.Method with
+            | ILMeth(ilMethInfo= ilMethInfo) when ilMethInfo.IsStatic && ilMethInfo.IsVirtual && methodName.Contains("op_") && ilMethInfo.IsAbstract ->
```
Comment (T-Gro) [inline src/Compiler/Checking/ConstraintSolver.fs:2951]:
```suggestion
            | ILMeth(ilMethInfo= ilMethInfo) when ilMethInfo.IsStatic && ilMethInfo.IsVirtual && ilMethInfo.IsAbstract ->
```

Why special-case for `op_` members only, should this not apply to all methods generally the same?

Comment (edgarfgp) [reply src/Compiler/Checking/ConstraintSolver.fs:2951]: Screenshot 2024-04-11 at 13 40 38

@T-Gro 'T.Parse should work through multiple levels of inheritance, since it will know specific implementation at runtime. ISpanParsable<'T>.Parse, if it's non-virtual, shouldn't on other hand.

Comment (edgarfgp) [reply src/Compiler/Checking/ConstraintSolver.fs:2951]: cc @vzarytovskii  Pointed out this in a previous PR

Comment (brianrourkeboll) [reply src/Compiler/Checking/ConstraintSolver.fs:2951]: > 'T.Parse should work through multiple levels of inheritance, since it will know specific implementation at runtime

Doesn't that apply to `'T.op_Addition` (or `'T.(+)`) as well, though?

As far as I can tell, the behavior depends on abstractness, not on operatorness:

```fsharp
open System
open System.Numerics

module ConstrainedCall =
    let ``'T.op_Addition``<'T & #IAdditionOperators<'T, 'T, 'T>>        x y    = 'T.op_Addition        (x, y)
    let ``'T.(+)``<'T & #IAdditionOperators<'T, 'T, 'T>>                x y    = 'T.(+)                (x, y)
    let ``'T.op_CheckedAddition``<'T & #IAdditionOperators<'T, 'T, 'T>> x y    = 'T.op_CheckedAddition (x, y)
    let ``'T.Parse``<'T & #IParsable<'T>>                               x      = 'T.Parse              (x, null)

module InterfaceCall =
    let ``IAdditionOperators.op_Addition``                              x y    = IAdditionOperators.op_Addition        (x, y)
    let ``IAdditionOperators.(+)``                                      x y    = IAdditionOperators.(+)                (x, y)
    let ``IAdditionOperators.op_CheckedAddition``                       x y    = IAdditionOperators.op_CheckedAddition (x, y)
    let ``IParsable.Parse``<'T & #IParsable<'T>>                        x : 'T = IParsable.Parse                       (x, null)

open ConstrainedCall

printfn $"{``'T.op_Addition`` 1 2}"                         // Prints 3.
printfn $"{``'T.(+)`` 1 2}"                                 // Prints 3.
printfn $"{``'T.op_CheckedAddition`` 1 2}"                  // Prints 3.
printfn $"""{``'T.Parse``<int> "3"}"""                      // Prints 3.

open InterfaceCall

printfn $"{``IAdditionOperators.op_Addition`` 1 2}"         // System.BadImageFormatException: Bad IL format.
printfn $"{``IAdditionOperators.(+)`` 1 2}"                 // System.BadImageFormatException: Bad IL format.
printfn $"{``IAdditionOperators.op_CheckedAddition`` 1 2}"  // Prints 3.
printfn $"""{``IParsable.Parse``<int> "3"}"""               // System.BadImageFormatException: Bad IL format.
```

Am I missing something?

Comment (edgarfgp) [reply src/Compiler/Checking/ConstraintSolver.fs:2951]: > Doesn't that apply to 'T.op_Addition (or 'T.(+)) as well, though?

@brianrourkeboll That is what I thought but I was told that `T.Parse` (constrained call) should allowed so that is why had to check for `op_`.  so only `static virtual` would be allowed.

Read the https://github.com/fsharp/fslang-design/blob/main/FSharp-7.0/FS-1124-interfaces-with-static-abstract-members.md and It does not clarify this scenario.

Comment (brianrourkeboll) [reply src/Compiler/Checking/ConstraintSolver.fs:2951]: > That is what I thought but I was told that `T.Parse` (constrained call) should be allowed so that is why had to check for `op_`. so only `static virtual` would be allowed.

Hmm, I still don't think I understand — unless you're talking about the bug being addressed in #17013?

If you look at my snippet above, the current behavior is that the constrained calls (like `'T.Parse`) all compile and run — and _should_ both compile and run — regardless of whether the static method guaranteed by the constraint is `abstract`, `virtual`, or an operator.

The direct calls on the interfaces also all currently compile regardless of whether the method guaranteed by the constraint is `abstract`, `virtual`, or an operator.

The only kind of invocation that fails at runtime with a bad image format is static `abstract` methods invoked directly on interfaces — but this is the case regardless of whether they are operators.

```fsharp
open System
open System.Numerics

// Is an operator, is abstract, fails at runtime, should not compile.
let ``IAdditionOperators.op_Addition`` x y = IAdditionOperators.op_Addition (x, y)
// Is an operator, is abstract, fails at runtime, should not compile.
let ``IAdditionOperators.(+)`` x y = IAdditionOperators.(+) (x, y)
// Is an operator, is virtual, currently runs fine.
let ``IAdditionOperators.op_CheckedAddition`` x y = IAdditionOperators.op_CheckedAddition (x, y)
// Is not an operator, is abstract, fails at runtime, should not compile.
let ``IParsable.Parse``<'T & #IParsable<'T>> x : 'T = IParsable.Parse (x, null)

printfn $"{``IAdditionOperators.op_Addition`` 1 2}"         // System.BadImageFormatException: Bad IL format.
printfn $"{``IAdditionOperators.(+)`` 1 2}"                 // System.BadImageFormatException: Bad IL format.
printfn $"{``IAdditionOperators.op_CheckedAddition`` 1 2}"  // Prints 3.
printfn $"""{``IParsable.Parse``<int> "3"}"""               // System.BadImageFormatException: Bad IL format.
```

C# does not allow calling static `abstract` or `virtual` methods on interfaces at all:

```csx
> IParsable<int>.Parse("3", null)
(1,1): error CS8926: A static virtual or abstract interface member can be accessed only on a type parameter.
```

```csx
> ISpanParsable<int>.Parse("3", null)
(1,1): error CS8926: A static virtual or abstract interface member can be accessed only on a type parameter.
```

It also just does not allow directly invoking operators in general, regardless of whether they are on interfaces:

```csx
> IAdditionOperators<int, int, int>.op_Addition(1, 2)
(1,35): error CS0571: 'IAdditionOperators<int, int, int>.operator +(int, int)': cannot explicitly call operator or accessor
```

```csx
> IAdditionOperators<int, int, int>.op_CheckedAddition(1, 2)
(1,35): error CS0571: 'IAdditionOperators<int, int, int>.operator checked +(int, int)': cannot explicitly call operator or accessor
```

```csx
> public class C { public static int operator +(C x, C y) => 3; }
. C.op_Addition(new(), new())
(2,3): error CS0571: 'C.operator +(C, C)': cannot explicitly call operator or accessor
```

F# of course _does_ allow this in general, both with `(…)` syntax and explicitly uttering the compiled `op_…` name. The only reason operators seem to stand out here is because operators are always static, and operators are one of the main reasons for static methods in interfaces in the first place.

It's too late for F# to follow C# and disallow direct invocations of `virtual` methods on interfaces altogether, since that _does_ currently compile and (sometimes) run — regardless of whether the method is an operator.

But I think the compile-time error that we're adding here, for when a static `abstract` method is called directly on an interface, needs to apply regardless of whether the `abstract` method is an operator.

Comment (T-Gro) [reply src/Compiler/Checking/ConstraintSolver.fs]: Exactly, would apply it generally without the `op_` limitation.

Comment (edgarfgp) [reply src/Compiler/Checking/ConstraintSolver.fs]: Thanks for the detailed reply @brianrourkeboll. I think I got it now. 

Just need to find a way to check for the `'T` constrained call and the explicit  interface call `IParsable.Parse`, does not to seems obvious.

@T-Gro any suggestion for the check ?

File: src/Compiler/Checking/ConstraintSolver.fs [hunk 2]
```diff
@@ -2942,10 +2942,16 @@ and ResolveOverloading
     let candidates = calledMethGroup |> List.filter (fun cmeth -> cmeth.IsCandidate(m, ad))
 
     let calledMethOpt, errors, calledMethTrace = 
-
         match calledMethGroup, candidates with 
-        | _, [calledMeth] when not isOpConversion -> 
-            Some calledMeth, CompleteD, NoTrace
+        | _, [calledMeth] when not isOpConversion ->
+            // See what candidates we have based on static/virtual/abstract
+            // OK: static virtual TResult operator checked i.e. IAdditionOperators.op_CheckedAddition
```
Comment (psfinaki) [inline src/Compiler/Checking/ConstraintSolver.fs:2948]: Did you mean "e.g."? :)

File: src/Compiler/Checking/ConstraintSolver.fs [hunk 3]
```diff
@@ -2942,10 +2942,16 @@ and ResolveOverloading
...
+            // Error: static abstract TResult operator i.e. IAdditionOperators.op_Addition
+            match calledMeth.Method with
+            | ILMeth(ilMethInfo= ilMethInfo) when ilMethInfo.IsStatic && ilMethInfo.IsVirtual && ilMethInfo.IsAbstract ->
+                // Do don't want to make available via completion, as it will lead to the compile time error. I.e. not usable if it's non-virtual
```
[the remark this answers is not in the document]
Comment (psfinaki) [reply src/Compiler/Checking/ConstraintSolver.fs:2952]: Do or do not :) sorry for nitpicking

File: tests/FSharp.Compiler.ComponentTests/Conformance/Types/TypeConstraints/IWSAMsAndSRTPs/IWSAMsAndSRTPsTests.fs [hunk 4]
```diff
@@ -1183,4 +1195,50 @@ let execute = IPrintable.Say("hello")
...
+    let ``ConstrainedAndInterfaceCalls.fs`` compilation =
+        compilation 
+        |> withOptions [ "--nowarn:3536" ; "--nowarn:3535" ]
+        |> verifyCompile
+        |> shouldFail
+        |> withDiagnostics [
+            (Error 509, Line 12, Col 82, Line 12, Col 126, "Method or object constructor 'op_Addition' not found")
+            (Error 509, Line 13, Col 82, Line 13, Col 126, "Method or object constructor 'op_Addition' not found")
+            (Error 509, Line 15, Col 82, Line 15, Col 129, "Method or object constructor 'Parse' not found")
+        ]
```
[the remark this answers is not in the document]
Comment (edgarfgp) [reply tests/FSharp.Compiler.ComponentTests/Conformance/Types/TypeConstraints/IWSAMsAndSRTPs/IWSAMsAndSRTPsTests.fs]: Yes. I think a specific error message would be better here. Thanks for the suggestion.

**Comment by edgarfgp** [comment]
This is ready :)

**Review by brianrourkeboll — APPROVED** [review]

**Comment by brianrourkeboll** [comment]
@edgarfgp It looks like the release notes are still referencing the old PR:

https://github.com/dotnet/fsharp/blob/888382bc07b038773ba23e98c405e06a0e01eb8f/docs/release-notes/.FSharp.Compiler.Service/8.0.400.md?plain=1#L3

File: docs/release-notes/.FSharp.Compiler.Service/8.0.400.md [hunk 5]
```diff
@@ -1,4 +1,5 @@
 ### Fixed
 
-Various parenthesization API fixes. ([PR #16977](https://github.com/dotnet/fsharp/pull/16977))
+* Disallow calling abstract methods directly on interfaces. ([PR #16319](https://github.com/dotnet/fsharp/pull/16319))
```
[the remark this answers is not in the document]
Comment (edgarfgp) [reply docs/release-notes/.FSharp.Compiler.Service/8.0.400.md]: Thanks @brianrourkeboll

File: docs/release-notes/.FSharp.Compiler.Service/8.0.400.md [hunk 6]
```diff
@@ -1,4 +1,5 @@
 ### Fixed
 
-Various parenthesization API fixes. ([PR #16977](https://github.com/dotnet/fsharp/pull/16977))
+* Disallow calling abstract methods directly on interfaces. ([PR #17021](https://github.com/dotnet/fsharp/pull/17021))
```
Comment (brianrourkeboll) [inline docs/release-notes/.FSharp.Compiler.Service/8.0.400.md:3]: Sorry, forgot this:

```suggestion
* Disallow calling abstract methods directly on interfaces. ([Issue #14012](https://github.com/dotnet/fsharp/issues/14012), [Issue #16299](https://github.com/dotnet/fsharp/issues/16299), [PR #17021](https://github.com/dotnet/fsharp/pull/17021))
```

Comment (brianrourkeboll) [reply docs/release-notes/.FSharp.Compiler.Service/8.0.400.md:3]: You can add "Fixes #16299" to the PR description, too.

**Comment by edgarfgp** [comment]
PR to update the IWASM design notes https://github.com/fsharp/fslang-design/pull/767

File: src/Compiler/FSComp.txt [hunk 7]
```diff
@@ -1745,4 +1745,5 @@ featureReuseSameFieldsInStructUnions,"Share underlying fields in a [<Struct>] di
 3862,parsStaticMemberImcompleteSyntax,"Incomplete declaration of a static construct. Use 'static let','static do','static member' or 'static val' for declaration."
 3863,parsExpectingField,"Expecting record field"
 3864,tooManyMethodsInDotNetTypeWritingAssembly,"The type '%s' has too many methods. Found: '%d', maximum: '%d'"
-3865,parsOnlySimplePatternsAreAllowedInConstructors,"Only simple patterns are allowed in primary constructors"
\ No newline at end of file
+3865,parsOnlySimplePatternsAreAllowedInConstructors,"Only simple patterns are allowed in primary constructors"
+3866,chkStaticAbstractInterfaceMembers,"A static abstract interface member can be accessed only on a type parameter."
```
Comment (vzarytovskii) [inline src/Compiler/FSComp.txt:1749]: I think this might sound a bit more specific:
```suggestion
3866,chkStaticAbstractInterfaceMembers,"A static abstract non-virtual interface member should only be called via type parameter."
```

Also, an extra mile can be adding a parameter to this message, `3866,chkStaticAbstractInterfaceMembers,"A static abstract non-virtual interface member should only be called via type parameter (for example: %s)."`, and pass a one-liner of which method user is trying to call, like "'T.Parse(...)".

Comment (edgarfgp) [reply src/Compiler/FSComp.txt]: @vzarytovskii  Done. See my last commit.

**Review by vzarytovskii — APPROVED** [review]

**Comment by edgarfgp** [comment]
`##[error]The job running on agent Azure Pipelines 68 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134`

**Review by psfinaki — APPROVED** [review]
Great stuff @edgarfgp and thanks @brianrourkeboll for the thorough review and suggestions.

**Comment by edgarfgp** [comment]
One less internal error :). Lets go to the next one
